import type { ToolDefinition } from "@/features/tools/types";
import type { Locale } from "@/lib/site";

type ToolText = {
  title: string;
  description: string;
};

type CommonText = {
  copyAll: string;
  clear: string;
  sample: string;
  placeholder: string;
  paragraphs: string;
  generatedText: string;
  charCountWithSpaces: string;
  charCountWithoutSpaces: string;
  whichPosition: string;
  backToTools: string;
  copied: string;
  languageSelect: string;
  highlightHelp: string;
  allTools: string;
  footerNote1: string;
  footerNote2: string;
  koLabel: string;
  enLabel: string;
  textCategory: string;
  utilityCategory: string;
  positionPlaceholder: string;
  twelveHour: string;
  twentyFourHour: string;
  fontSize: string;
  customColor: string;
  customColor: string;
  presetColors: string;
  homeTitle: string;
  homeSubtitle: string;
  rulerHowTo: string;
  rulerStep1: string;
  rulerStep2: string;
  rulerStep3: string;
  rulerEnterCardWidth: string;
  rulerExample: string;
  rulerTip: string;
  calibrate: string;
  changeTo: string;
  exitFullscreen: string;
  fullscreen: string;
  frLabel: string;
  jaLabel: string;
  zhLabel: string;
  zhTWLabel: string;
  ptLabel: string;
  esLabel: string;
  deLabel: string;
  arLabel: string;
};

const TOOL_TEXTS: Record<Locale, { tools: Record<string, ToolText>; common: CommonText }> = {
  en: {
    tools: {
      ruler: { title: "Online Ruler", description: "Measure screen distances with zero-point placement, credit-card calibration, and cm/inch toggles." },
      wordcounter: { title: "Word Counter", description: "Count characters, spaces, and character positions as you type." },
      countdown: { title: "Countdown Timer", description: "Set a timer, pause it, resume it, and keep track in fullscreen or night mode." },
      digitalclock: { title: "Digital Clock", description: "Check the current time in real time with a fullscreen view." },
      screenlamp: { title: "Screen Lights", description: "Turn the screen into a solid color light with fullscreen and custom color choices." },
      qrgenerator: { title: "QR Generator", description: "Create QR codes instantly from any text or URL." },
      barcodegenerator: { title: "Barcode Generator", description: "Create many barcode formats for labels, inventory, and packaging." },
      dummytext: { title: "Lorem Ipsum", description: "Generate placeholder paragraphs with a chosen length." },
    },
    common: {
      copyAll: "Copy All",
      clear: "Clear",
      sample: "Sample text",
      placeholder: "Paste or type text here...",
      paragraphs: "Paragraphs",
      generatedText: "Generated Text",
      charCountWithSpaces: "Character count (with spaces)",
      charCountWithoutSpaces: "Character count (without spaces)",
      whichPosition: "Which character position would you like to find?",
      backToTools: "Back to all tools",
      copied: "Copied to clipboard!",
      languageSelect: "Select Content Language",
      highlightHelp: "* The character at the specified index is highlighted in real-time within the text area above.",
      allTools: "All Tools",
      footerNote1: "This tool is part of the apps24 utility suite.",
      footerNote2: "All processing happens locally in your browser for maximum privacy and speed.",
      koLabel: "Korean",
      enLabel: "English",
      textCategory: "Text",
      utilityCategory: "Utility",
      positionPlaceholder: "Position",
      twelveHour: "12H",
      twentyFourHour: "24H",
      fontSize: "Size",
      customColor: "Custom",
      presetColors: "Presets",
      homeTitle: "Fast Multilingual Tools",
      homeSubtitle: "Simple utilities for quick tasks, perfectly localized for your language.",
      rulerHowTo: "How to Use the Online Ruler",
      rulerStep1: "Place a credit card horizontally at the zero mark.",
      rulerStep2: "Enter the measured width of the card and click 'Calibrate'.",
      rulerStep3: "Now you can measure the desired object.",
      rulerEnterCardWidth: "Enter the credit card width",
      rulerExample: "Example: If the width is 10.4 cm, enter 10.4",
      rulerTip: "Tip: Use the blue handle at the bottom-right corner of the canvas to resize it.",
      calibrate: "Calibrate",
      changeTo: "Change to",
      exitFullscreen: "Exit full screen",
      fullscreen: "Full screen",
      frLabel: "French",
      jaLabel: "Japanese",
      zhLabel: "Chinese (Simplified)",
      zhTWLabel: "Chinese (Traditional)",
      ptLabel: "Portuguese",
      esLabel: "Spanish",
      deLabel: "German",
      arLabel: "Arabic",
    },
  },
  ko: {
    tools: {
      ruler: { title: "온라인 자", description: "영점 설정, 신용카드 보정, cm/inch 전환으로 화면 길이를 측정합니다." },
      wordcounter: { title: "글자 수 세기", description: "입력한 텍스트의 글자 수와 공백 포함/제외 수를 즉시 계산합니다." },
      countdown: { title: "카운트다운 타이머", description: "시간을 설정하고 일시정지, 재개, 전체화면, 나이트 모드를 사용할 수 있습니다." },
      digitalclock: { title: "디지털 시계", description: "현재 시간을 실시간으로 확인하고 전체화면으로 볼 수 있습니다." },
      screenlamp: { title: "스크린 라이트", description: "전체화면과 사용자 색상으로 화면 전체를 단색 조명으로 바꿉니다." },
      qrgenerator: { title: "QR 생성기", description: "텍스트나 URL로 QR 코드를 바로 생성합니다." },
      barcodegenerator: { title: "바코드 생성기", description: "라벨, 재고, 포장용 여러 바코드 형식을 생성합니다." },
      dummytext: { title: "로렘 입숨", description: "문단 수를 정해 자리표시자 텍스트를 생성합니다." },
    },
    common: {
      copyAll: "전체 복사",
      clear: "지우기",
      sample: "샘플 텍스트",
      placeholder: "여기에 텍스트를 입력하거나 붙여넣으세요...",
      paragraphs: "문단 수",
      generatedText: "생성된 텍스트",
      charCountWithSpaces: "글자 수 (공백 포함)",
      charCountWithoutSpaces: "글자 수 (공백 제외)",
      whichPosition: "찾고 싶은 글자 위치는 어디인가요?",
      backToTools: "전체 도구로 돌아가기",
      copied: "클립보드에 복사되었습니다!",
      languageSelect: "콘텐츠 언어 선택",
      highlightHelp: "* 지정된 인덱스의 글자가 상단 입력창 내에서 실시간으로 강조되어 표시됩니다.",
      allTools: "모든 도구",
      footerNote1: "이 도구는 apps24 유틸리티 제품군의 일부입니다.",
      footerNote2: "모든 처리는 개인 정보 보호와 속도를 위해 브라우저에서 로컬로 수행됩니다.",
      koLabel: "한국어",
      enLabel: "영어",
      textCategory: "텍스트",
      utilityCategory: "유틸리티",
      positionPlaceholder: "위치",
      twelveHour: "12시간",
      twentyFourHour: "24시간",
      fontSize: "크기",
      customColor: "선택",
      presetColors: "프리셋",
      homeTitle: "빠른 다국어 도구 모음",
      homeSubtitle: "간단한 작업을 위한 유틸리티, 당신의 언어에 완벽하게 맞춰져 있습니다.",
      rulerHowTo: "온라인 자 사용법",
      rulerStep1: "신용카드를 가로로 0점 표시 부분에 놓습니다.",
      rulerStep2: "카드의 실제 너비를 입력하고 '보정' 버튼을 누릅니다.",
      rulerStep3: "이제 원하는 물체를 측정할 수 있습니다.",
      rulerEnterCardWidth: "신용카드 너비를 입력하세요",
      rulerExample: "예시: 너비가 10.4 cm인 경우 10.4 입력",
      rulerTip: "팁: 캔버스 우측 하단의 파란색 핸들을 드래그하여 크기를 조절할 수 있습니다.",
      calibrate: "보정하기",
      changeTo: "단위 변경:",
      exitFullscreen: "전체화면 종료",
      fullscreen: "전체화면",
      frLabel: "프랑스어",
      jaLabel: "일본어",
      zhLabel: "중국어(간체)",
      zhTWLabel: "중국어(번체)",
      ptLabel: "포르투갈어",
      esLabel: "스페인어",
      deLabel: "독일어",
      arLabel: "아랍어",
    },
  },
  fr: {
    tools: {
      ruler: { title: "Règle en ligne", description: "Mesurez les distances à l'écran avec étalonnage par carte de crédit." },
      wordcounter: { title: "Compteur de mots", description: "Comptez les caractères et les mots en temps réel." },
      countdown: { title: "Compte à rebours", description: "Réglez une minuterie avec mode plein écran et nuit." },
      digitalclock: { title: "Horloge numérique", description: "Consultez l'heure actuelle en temps réel." },
      screenlamp: { title: "Lampe d'écran", description: "Transformez votre écran en une source lumineuse colorée." },
      qrgenerator: { title: "Générateur de QR", description: "Créeez instantanément des codes QR." },
      barcodegenerator: { title: "Générateur de codes-barres", description: "Créez divers formats de codes-barres." },
      dummytext: { title: "Lorem Ipsum", description: "Générez des paragraphes de texte de remplacement." },
    },
    common: {
      copyAll: "Tout copier",
      clear: "Effacer",
      sample: "Texte d'exemple",
      placeholder: "Collez ou tapez votre texte ici...",
      paragraphs: "Paragraphes",
      generatedText: "Texte généré",
      charCountWithSpaces: "Nombre de caractères (avec espaces)",
      charCountWithoutSpaces: "Nombre de caractères (sans espaces)",
      whichPosition: "Quelle position de caractère voulez-vous trouver?",
      backToTools: "Retour aux outils",
      copied: "Copié dans le presse-papiers!",
      languageSelect: "Choisir la langue du contenu",
      highlightHelp: "* Le caractère à l'index spécifié est mis en évidence en temps réel dans la zone de texte ci-dessus.",
      allTools: "Toutes les outils",
      footerNote1: "Cet outil fait partie de la suite utilitaire apps24.",
      footerNote2: "Tout le traitement se fait localement dans votre navigateur pour une confidentialité et une rapidité maximales.",
      koLabel: "Coréen",
      enLabel: "Anglais",
      textCategory: "Texte",
      utilityCategory: "Utilitaire",
      positionPlaceholder: "Position",
      twelveHour: "12H",
      twentyFourHour: "24H",
      fontSize: "Taille",
      customColor: "Couleur",
      presetColors: "Préréglages",
      homeTitle: "Outils multilingues rapides",
      homeSubtitle: "Des utilitaires simples pour des tâches rapides, parfaitement localisés pour votre langue.",
      rulerHowTo: "Comment utiliser la règle en ligne",
      rulerStep1: "Placez une carte de crédit horizontalement sur la marque zéro.",
      rulerStep2: "Entrez la largeur mesurée de la carte et cliquez sur 'Calibrer'.",
      rulerStep3: "Vous pouvez maintenant mesurer l'objet souhaité.",
      rulerEnterCardWidth: "Entrez la largeur de la carte de crédit",
      rulerExample: "Exemple : Si la largeur est de 10,4 cm, entrez 10,4",
      rulerTip: "Conseil : Utilisez la poignée bleue dans le coin inférieur droit du canevas pour le redimensionner.",
      calibrate: "Calibrer",
      changeTo: "Passer à",
      exitFullscreen: "Quitter le plein écran",
      fullscreen: "Plein écran",
      frLabel: "Français",
      jaLabel: "Japonais",
      zhLabel: "Chinois (Simplifié)",
      zhTWLabel: "Chinois (Traditionnel)",
      ptLabel: "Portugais",
      esLabel: "Espagnol",
      deLabel: "Allemand",
      arLabel: "Arabe",
    },
  },
  ja: {
    tools: {
      ruler: { title: "定規オンライン", description: "カード調整機能付きで画面上の長さを測定します。" },
      wordcounter: { title: "文字数カウント", description: "リアルタイムで文字数や単語数をカウントします。" },
      countdown: { title: "カウントダウン", description: "タイマーの設定、一時停止、再開が可能です。" },
      digitalclock: { title: "デジタル時計", description: "現在時間をリアルタイムで確認でき、全画面で表示可能です。" },
      screenlamp: { title: "スクリーンライト", description: "画面を単色の照明として使用できます。" },
      qrgenerator: { title: "QR作成", description: "テキストやURLからQRコードを即座に作成します。" },
      barcodegenerator: { title: "バーコード作成", description: "各種フォーマットのバーコードを作成します。" },
      dummytext: { title: "ダミーテキスト", description: "プレースホルダー用の文章を生成します。" },
    },
    common: {
      copyAll: "すべてコピー",
      clear: "クリア",
      sample: "サンプルテキスト",
      placeholder: "ここにテキストを入力または貼り付けてください...",
      paragraphs: "段落数",
      generatedText: "生成된 텍스트",
      charCountWithSpaces: "文字数 (空白含む)",
      charCountWithoutSpaces: "文字数 (空白なし)",
      whichPosition: "どの文字位置を確認しますか？",
      backToTools: "ツール一覧に戻る",
      copied: "クリップボード에 복사되었습니다！",
      languageSelect: "コンテンツの言語を選択",
      highlightHelp: "* 指定されたインデックスの文字が、上のテキストエリア内でリアルタイムに強調表示されます。",
      allTools: "すべてのツール",
      footerNote1: "このツールはapps24ユーティリティスイートの一部です。",
      footerNote2: "すべての処理は、最大限의 プライバシーと速度のためにブラウザ内でローカルに行われます。",
      koLabel: "韓国語",
      enLabel: "英語",
      textCategory: "テキスト",
      utilityCategory: "ユーティリティ",
      positionPlaceholder: "位置",
      twelveHour: "12H",
      twentyFourHour: "24H",
      fontSize: "サイズ",
      customColor: "色",
      presetColors: "プリセット",
      homeTitle: "高速多言語ツール",
      homeSubtitle: "あなたの言語に完璧にローカライズされた、迅速なタスクのためのシンプルなユーティリティ。",
      rulerHowTo: "オンライン定規の使い方",
      rulerStep1: "クレジットカードを0の目盛りに水平に置いてください。",
      rulerStep2: "カードの測定された幅を入力し、「調整」をクリックします。",
      rulerStep3: "これで目的の対象物を測定できます。",
      rulerEnterCardWidth: "クレジットカードの幅を入力してください",
      rulerExample: "例：幅が10.4 cmの場合、10.4と入力してください",
      rulerTip: "ヒント：キャンバスの右下隅にある青いハンドルを使用してサイズを変更してください。",
      calibrate: "調整",
      changeTo: "単位変更:",
      exitFullscreen: "全画面表示を終了",
      fullscreen: "全画面表示",
      frLabel: "フランス語",
      jaLabel: "日本語",
      zhLabel: "中国語（簡体字）",
      zhTWLabel: "中国語（繁体字）",
      ptLabel: "ポルトガル語",
      esLabel: "スペイン語",
      deLabel: "ドイツ語",
      arLabel: "アラビア語",
    },
  },
  zh: {
    tools: {
      ruler: { title: "在线标尺", description: "使用信用卡校准测量屏幕距离。" },
      wordcounter: { title: "字数统计", description: "实时统计字符和单词数量。" },
      countdown: { title: "倒计时", description: "设置计时器，支持全屏和夜间模式。" },
      digitalclock: { title: "数字时钟", description: "实时查看当前时间。" },
      screenlamp: { title: "屏幕灯", description: "将屏幕变为单色照明灯。" },
      qrgenerator: { title: "QR生成器", description: "即时创建二维码。" },
      barcodegenerator: { title: "条形码生成器", description: "生成多种格式的条形码。" },
      dummytext: { title: "乱数假文", description: "生成占位段落文本。" },
    },
    common: {
      copyAll: "全部复制",
      clear: "清除",
      sample: "示例文本",
      placeholder: "在此处粘贴或输入文本...",
      paragraphs: "段落数",
      generatedText: "生成的文本",
      charCountWithSpaces: "字符数 (含空格)",
      charCountWithoutSpaces: "字符数 (不含空格)",
      whichPosition: "您想查找哪个字符位置？",
      backToTools: "返回工具列表",
      copied: "已复制到剪贴板！",
      languageSelect: "选择内容语言",
      highlightHelp: "* 指定索引处的字符将在上面的文本区域中实时突出显示。",
      allTools: "所有工具",
      footerNote1: "此工具是 apps24 实用工具套件的一部分。",
      footerNote2: "所有处理均在您的浏览器中本地完成，以实现最大的隐私和速度。",
      koLabel: "韩语",
      enLabel: "英语",
      textCategory: "文本",
      utilityCategory: "实用程序",
      positionPlaceholder: "位置",
      twelveHour: "12H",
      twentyFourHour: "24H",
      fontSize: "大小",
      customColor: "颜色",
      presetColors: "预设",
      homeTitle: "快速多语言工具",
      homeSubtitle: "为快速任务设计的简单实用程序，完全针对您的语言进行了本地化。",
      rulerHowTo: "如何使用在线标尺",
      rulerStep1: "将信用卡水平放在零刻度处。",
      rulerStep2: "输入测得的卡片宽度并点击“校准”。",
      rulerStep3: "现在您可以测量所需的物体。",
      rulerEnterCardWidth: "输入信用卡宽度",
      rulerExample: "例如：如果宽度为 10.4 厘米，输入 10.4",
      rulerTip: "提示：使用画布右下角的蓝色手柄调整其大小。",
      calibrate: "校准",
      changeTo: "切换至",
      exitFullscreen: "退出全屏",
      fullscreen: "全屏",
      frLabel: "法语",
      jaLabel: "日语",
      zhLabel: "中文 (简体)",
      zhTWLabel: "中文 (繁体)",
      ptLabel: "葡萄牙语",
      esLabel: "西班牙语",
      deLabel: "德语",
      arLabel: "阿拉伯语",
    },
  },
  "zh-TW": {
    tools: {
      ruler: { title: "線上尺子", description: "使用信用卡校準測量螢幕距離。" },
      wordcounter: { title: "字數統計", description: "即時統計字元核單字數量。" },
      countdown: { title: "倒數計時", description: "設置計時器，支持全螢幕和夜間模式。" },
      digitalclock: { title: "數位時鐘", description: "即時查看目前時間。" },
      screenlamp: { title: "螢幕燈", description: "將螢幕變為單色照明燈。" },
      qrgenerator: { title: "QR產生器", description: "即時建立二維碼。" },
      barcodegenerator: { title: "條形碼產生器", description: "建立多種格式의 條形碼。" },
      dummytext: { title: "Lorem Ipsum", description: "建立佔位段落文字。" },
    },
    common: {
      copyAll: "全部複製",
      clear: "清除",
      sample: "範例文字",
      placeholder: "在此處貼上或輸入文字...",
      paragraphs: "段落數",
      generatedText: "生成的文字",
      charCountWithSpaces: "字元數 (含空格)",
      charCountWithoutSpaces: "字元數 (不含空格)",
      whichPosition: "您想查找哪個字元位置？",
      backToTools: "返回工具列表",
      copied: "已複製到剪貼簿！",
      languageSelect: "選擇內容語言",
      highlightHelp: "* 指定索引處의 字元將在上面的文字區域中即時突出顯示。",
      allTools: "所有工具",
      footerNote1: "此工具是 apps24 實用工具套件的一部分。",
      footerNote2: "所有處理均在您的瀏覽器中本地完成，以實現最大的隱私和速度。",
      koLabel: "韓語",
      enLabel: "英語",
      textCategory: "文本",
      utilityCategory: "公用程式",
      positionPlaceholder: "位置",
      twelveHour: "12H",
      twentyFourHour: "24H",
      fontSize: "大小",
      customColor: "顏色",
      presetColors: "預設",
      homeTitle: "快速多語言工具",
      homeSubtitle: "為快速任務設計的簡單實用程序，完全針對您的語言進行了本地化。",
      rulerHowTo: "如何使用線上標尺",
      rulerStep1: "將信用卡水平放在零刻度處。",
      rulerStep2: "輸入測得的卡片寬度並點擊“校準”。",
      rulerStep3: "現在您可以測量所需的物體。",
      rulerEnterCardWidth: "輸入信用卡寬度",
      rulerExample: "例如：如果寬度為 10.4 厘米，輸入 10.4",
      rulerTip: "提示：使用畫布右下角的藍色手柄調整其大小。",
      calibrate: "校準",
      changeTo: "切換至",
      exitFullscreen: "退出全屏",
      fullscreen: "全屏",
      frLabel: "法語",
      jaLabel: "日語",
      zhLabel: "中文 (簡體)",
      zhTWLabel: "中文 (繁體)",
      ptLabel: "葡萄牙語",
      esLabel: "西班牙語",
      deLabel: "德語",
      arLabel: "阿拉伯語",
    },
  },
  pt: {
    tools: {
      ruler: { title: "Régua Online", description: "Meça distâncias na tela com calibração." },
      wordcounter: { title: "Contador de Palavras", description: "Conte caracteres e palavras em tempo real." },
      countdown: { title: "Cronômetro", description: "Defina temporizadores com modo tela cheia." },
      digitalclock: { title: "Relógio Digital", description: "Verifique a hora atual em tempo real." },
      screenlamp: { title: "Luz de Tela", description: "Transforme sua tela em uma luz colorida." },
      qrgenerator: { title: "Gerador de QR", description: "Crie códigos QR instantaneamente." },
      barcodegenerator: { title: "Gerador de Código de Barras", description: "Crie vários formatos de códigos de barras." },
      dummytext: { title: "Lorem Ipsum", description: "Gere parágrafos de texto fictício." },
    },
    common: {
      copyAll: "Copiar tudo",
      clear: "Limpar",
      sample: "Texto de exemplo",
      placeholder: "Cole ou digite o texto aqui...",
      paragraphs: "Parágrafos",
      generatedText: "Texto gerado",
      charCountWithSpaces: "Contagem de caracteres (com espaços)",
      charCountWithoutSpaces: "Contagem de caracteres (sem espaços)",
      whichPosition: "Qual posição de caractere você deseja encontrar?",
      backToTools: "Voltar para ferramentas",
      copied: "Copiado para a área de transferência!",
      languageSelect: "Selecionar idioma do conteúdo",
      highlightHelp: "* O caractere no índice especificado é realçado em tempo real na área de texto acima.",
      allTools: "Todas as ferramentas",
      footerNote1: "Esta ferramenta faz parte da suite de utilitários apps24.",
      footerNote2: "Todo o processamento ocorre localmente no seu navegador para máxima privacidade e velocidade.",
      koLabel: "Coreano",
      enLabel: "Inglês",
      textCategory: "Texto",
      utilityCategory: "Utilitário",
      positionPlaceholder: "Posição",
      twelveHour: "12H",
      twentyFourHour: "24H",
      fontSize: "Tamanho",
      customColor: "Cor",
      presetColors: "Predefinições",
      homeTitle: "Ferramentas Multilíngues Rápidas",
      homeSubtitle: "Utilitários simples para tarefas rápidas, perfeitamente localizados para o seu idioma.",
      rulerHowTo: "Como usar a régua online",
      rulerStep1: "Coloque um cartão de crédito horizontalmente na marca zero.",
      rulerStep2: "Insira a largura medida do cartão e clique em 'Calibrar'.",
      rulerStep3: "Agora você pode medir o objeto desejado.",
      rulerEnterCardWidth: "Insira a largura do cartão de crédito",
      rulerExample: "Exemplo: Se a largura for 10,4 cm, insira 10,4",
      rulerTip: "Dica: Use a alça azul no canto inferior direito da tela para redimensioná-la.",
      calibrate: "Calibrar",
      changeTo: "Mudar para",
      exitFullscreen: "Sair da tela cheia",
      fullscreen: "Tela cheia",
      frLabel: "Francês",
      jaLabel: "Japonês",
      zhLabel: "Chinês (Simplificado)",
      zhTWLabel: "Chinês (Tradicional)",
      ptLabel: "Português",
      esLabel: "Espanhol",
      deLabel: "Alemão",
      arLabel: "Árabe",
    },
  },
  es: {
    tools: {
      ruler: { title: "Regla en Línea", description: "Mida distancias en pantalla con calibración." },
      wordcounter: { title: "Contador de Palabras", description: "Cuente caracteres y palabras en tiempo real." },
      countdown: { title: "Cuenta Regresiva", description: "Configure temporizadores con modo pantalla completa." },
      digitalclock: { title: "Reloj Digital", description: "Consulte la hora actual en tiempo real." },
      screenlamp: { title: "Luz de Pantalla", description: "Convierta su pantalla en una luz de color." },
      qrgenerator: { title: "Generador de QR", description: "Cree códigos QR al instante." },
      barcodegenerator: { title: "Generador de Códigos de Barras", description: "Cree varios formatos de códigos de barras." },
      dummytext: { title: "Lorem Ipsum", description: "Genere párrafos de texto de relleno." },
    },
    common: {
      copyAll: "Copiar todo",
      clear: "Limpiar",
      sample: "Texto de ejemplo",
      placeholder: "Pegue o escriba el texto aquí...",
      paragraphs: "Párrafos",
      generatedText: "Texto generado",
      charCountWithSpaces: "Recuento de caracteres (con espacios)",
      charCountWithoutSpaces: "Recuento de caracteres (sin espacios)",
      whichPosition: "¿Qué posición de carácter desea buscar?",
      backToTools: "Volver a herramientas",
      copied: "¡Copiado al portapapeles!",
      languageSelect: "Seleccionar idioma del contenido",
      highlightHelp: "* El carácter en el índice especificado se resalta en tiempo real dentro del área de texto de arriba.",
      allTools: "Todas las herramientas",
      footerNote1: "Esta herramienta es parte de la suite de utilidades apps24.",
      footerNote2: "Todo el procesamiento se realiza localmente en su navegador para una máxima privacidad y velocidad.",
      koLabel: "Coreano",
      enLabel: "Inglés",
      textCategory: "Texto",
      utilityCategory: "Utilidad",
      positionPlaceholder: "Posición",
      twelveHour: "12H",
      twentyFourHour: "24H",
      fontSize: "Tamaño",
      customColor: "Color",
      presetColors: "Preajustes",
      homeTitle: "Herramientas Multilingües Rápidas",
      homeSubtitle: "Utilidades sencillas para tareas rápidas, perfectamente localizadas para su idioma.",
      rulerHowTo: "Cómo usar la regla en línea",
      rulerStep1: "Coloque una tarjeta de crédito horizontalmente en la marca cero.",
      rulerStep2: "Ingrese el ancho medido de la tarjeta y haga clic en 'Calibrar'.",
      rulerStep3: "Ahora puede medir el objeto deseado.",
      rulerEnterCardWidth: "Ingrese el ancho de la tarjeta de crédito",
      rulerExample: "Ejemplo: si el ancho es de 10,4 cm, ingrese 10,4",
      rulerTip: "Sugerencia: use el asa azul en la esquina inferior derecha del lienzo para cambiar su tamaño.",
      calibrate: "Calibrar",
      changeTo: "Cambiar a",
      exitFullscreen: "Salir de pantalla completa",
      fullscreen: "Pantalla completa",
      frLabel: "Francés",
      jaLabel: "Japonés",
      zhLabel: "Chino (Simplificado)",
      zhTWLabel: "Chino (Tradicional)",
      ptLabel: "Português",
      esLabel: "Español",
      deLabel: "Alemán",
      arLabel: "Árabe",
    },
  },
  de: {
    tools: {
      ruler: { title: "Online-Lineal", description: "Messen Sie Bildschirmabstände mit Kalibrierung." },
      wordcounter: { title: "Wortzähler", description: "Zählen Sie Zeichen und Wörter in Echtzeit." },
      countdown: { title: "Countdown-Timer", description: "Stellen Sie Timer mit Vollbildmodus ein." },
      digitalclock: { title: "Digitale Uhr", description: "Überprüfen Sie die aktuelle Uhrzeit in Echtzeit." },
      screenlamp: { title: "Bildschirmlicht", description: "Verwandeln Sie Ihren Bildschirm in ein farbiges Licht." },
      qrgenerator: { title: "QR-Generator", description: "Erstellen Sie sofort QR-Codes." },
      barcodegenerator: { title: "Barcode-Generator", description: "Erstellen Sie verschiedene Barcode-Formate." },
      dummytext: { title: "Blindtext", description: "Generieren Sie Platzhaltertexte." },
    },
    common: {
      copyAll: "Alles kopieren",
      clear: "Löschen",
      sample: "Beispieltext",
      placeholder: "Text hier einfügen oder tippen...",
      paragraphs: "Absätze",
      generatedText: "Generierter Text",
      charCountWithSpaces: "Zeichenanzahl (mit Leerzeichen)",
      charCountWithoutSpaces: "Zeichenanzahl (ohne Leerzeichen)",
      whichPosition: "Welche Zeichenposition möchten Sie finden?",
      backToTools: "Zurück zu den Tools",
      copied: "In die Zwischenablage kopiert!",
      languageSelect: "Inhaltssprache auswählen",
      highlightHelp: "* Das Zeichen am angegebenen Index wird in Echtzeit im obigen Textbereich hervorgehoben.",
      allTools: "Alle Tools",
      footerNote1: "Dieses Tool ist Teil der apps24-Utility-Suite.",
      footerNote2: "Die gesamte Verarbeitung erfolgt lokal in Ihrem Browser für maximale Privatsphäre und Geschwindigkeit.",
      koLabel: "Koreanisch",
      enLabel: "Englisch",
      textCategory: "Text",
      utilityCategory: "Dienstprogramm",
      positionPlaceholder: "Position",
      twelveHour: "12H",
      twentyFourHour: "24H",
      fontSize: "Größe",
      customColor: "Farbe",
      presetColors: "Voreinstellungen",
      homeTitle: "Schnelle mehrsprachige Tools",
      homeSubtitle: "Einfache Dienstprogramme für schnelle Aufgaben, perfekt auf Ihre Sprache lokalisiert.",
      rulerHowTo: "So verwenden Sie das Online-Lineal",
      rulerStep1: "Legen Sie eine Kreditkarte horizontal auf die Nullmarkierung.",
      rulerStep2: "Geben Sie die gemessene Breite der Karte ein und klicken Sie auf 'Kalibrieren'.",
      rulerStep3: "Jetzt können Sie das gewünschte Objekt messen.",
      rulerEnterCardWidth: "Geben Sie die Kreditkartenbreite ein",
      rulerExample: "Beispiel: Wenn die Breite 10,4 cm beträgt, geben Sie 10,4 ein",
      rulerTip: "Tipp: Verwenden Sie den blauen Griff in der unteren rechten Ecke der Zeichenfläche, um deren Größe zu ändern.",
      calibrate: "Kalibrieren",
      changeTo: "Wechseln zu",
      exitFullscreen: "Vollbild beenden",
      fullscreen: "Vollbild",
      frLabel: "Französisch",
      jaLabel: "Japanisch",
      zhLabel: "Chinesisch (Vereinfacht)",
      zhTWLabel: "Chinesisch (Traditionell)",
      ptLabel: "Portugiesisch",
      esLabel: "Spanisch",
      deLabel: "Deutsch",
      arLabel: "Arabisch",
    },
  },
  ar: {
    tools: {
      ruler: { title: "مسطرة عبر الإنترنت", description: "قياس المسافات على الشاشة مع المعايرة." },
      wordcounter: { title: "عداد الكلمات", description: "عد الحروف والكلمات في الوقت الفعلي." },
      countdown: { title: "مؤقت العد التنازلي", description: "ضبط المؤقتات مع وضع ملء الشاشة." },
      digitalclock: { title: "ساعة رقمية", description: "التحقق من الوقت الحالي في الوقت الفعلي." },
      screenlamp: { title: "إضاءة الشاشة", description: "تحويل شاشتك إلى ضوء ملون." },
      qrgenerator: { title: "مولد QR", description: "إنشاء رموز QR على الفور." },
      barcodegenerator: { title: "مولد الباركود", description: "إنشاء تنسيقات باركود متعددة." },
      dummytext: { title: "نص لوريم إيبسوم", description: "توليد فقرات نصية بديلة." },
    },
    common: {
      copyAll: "نسخ الكل",
      clear: "مسح",
      sample: "نص تجريبي",
      placeholder: "الصق أو اكتب النص هنا...",
      paragraphs: "فقرات",
      generatedText: "النص الناتج",
      charCountWithSpaces: "عدد الحروف (مع المسافات)",
      charCountWithoutSpaces: "عدد الحروف (بدون مسافات)",
      whichPosition: "ما هو موقع الحرف الذي تريد العثور عليه؟",
      backToTools: "العودة إلى الأدوات",
      copied: "تم النسخ إلى الحافظة!",
      languageSelect: "اختر لغة المحتوى",
      highlightHelp: "* يتم تمييز الحرف الموجود في الفهرس المحدد في الوقت الفعلي داخل منطقة النص أعلاه.",
      allTools: "جميع الأدوات",
      footerNote1: "هذه الأداة هي جزء من مجموعة أدوات apps24.",
      footerNote2: "تتم جميع عمليات المعالجة محليًا في متصفحك لضمان أقصى قدر من الخصوصية والسرعة.",
      koLabel: "الكورية",
      enLabel: "الإنجليزية",
      textCategory: "نص",
      utilityCategory: "أداة",
      positionPlaceholder: "الموقع",
      twelveHour: "12H",
      twentyFourHour: "24H",
      fontSize: "الحجم",
      customColor: "لون",
      presetColors: "الإعدادات المسبقة",
      homeTitle: "أدوات سريعة متعددة اللغات",
      homeSubtitle: "أدوات مساعدة بسيطة للمهام السريعة، معربة بالكامل للغتك.",
      rulerHowTo: "كيفية استخدام المسطرة عبر الإنترنت",
      rulerStep1: "ضع بطاقة ائتمان أفقيًا عند علامة الصفر.",
      rulerStep2: "أدخل العرض المقاس للبطاقة وانقر على 'معايرة'.",
      rulerStep3: "الآن يمكنك قياس الشيء المطلوب.",
      rulerEnterCardWidth: "أدخل عرض بطاقة الائتمان",
      rulerExample: "مثال: إذا كان العرض 10.4 سم، أدخل 10.4",
      rulerTip: "نصيحة: استخدم المقبض الأزرق في الزاوية اليمنى السفلية من اللوحة لتغيير حجمها.",
      calibrate: "معايرة",
      changeTo: "تغيير إلى",
      exitFullscreen: "خروج من ملء الشاشة",
      fullscreen: "ملء الشاشة",
      frLabel: "الفرنسية",
      jaLabel: "اليابانية",
      zhLabel: "الصينية (المبسطة)",
      zhTWLabel: "الصينية (التقليدية)",
      ptLabel: "البرتغالية",
      esLabel: "الإسبانية",
      deLabel: "الألمانية",
      arLabel: "العربية",
    },
  },
};

export function getToolText(locale: Locale, tool: ToolDefinition): ToolText {
  return (
    TOOL_TEXTS[locale]?.tools[tool.id] ??
    TOOL_TEXTS.en?.tools[tool.id] ?? {
      title: tool.titleKey,
      description: tool.descriptionKey,
    }
  );
}

export function getCommonText(locale: Locale): CommonText {
  return TOOL_TEXTS[locale]?.common ?? TOOL_TEXTS.en.common;
}
