import type { ToolDefinition } from "@/features/tools/types";
import type { Locale } from "@/lib/site";

type ToolText = {
  title: string;
  description: string;
  seo?: string;
  longDescription?: string;
  usageContext?: string;
  howToUse?: string;
  faq?: { q: string; a: string }[];
};

type CommonText = {
  copyAll: string;
  clear: string;
  sample: string;
  placeholder: string;
  paragraphs: string;
  generatedText: string;
  charCountWithSpaces: string;
  charCountWithoutSpaces: string;
  whichPosition: string;
  backToTools: string;
  copied: string;
  languageSelect: string;
  highlightHelp: string;
  allTools: string;
  footerNote1: string;
  footerNote2: string;
  koLabel: string;
  enLabel: string;
  textCategory: string;
  utilityCategory: string;
  positionPlaceholder: string;
  twelveHour: string;
  twentyFourHour: string;
  fontSize: string;
  customColor: string;
  presetColors: string;
  homeTitle: string;
  homeSubtitle: string;
  rulerHowTo: string;
  rulerStep1: string;
  rulerStep2: string;
  rulerStep3: string;
  rulerEnterCardWidth: string;
  rulerExample: string;
  rulerTip: string;
  calibrate: string;
  changeTo: string;
  exitFullscreen: string;
  fullscreen: string;
  frLabel: string;
  jaLabel: string;
  zhLabel: string;
  zhTWLabel: string;
  ptLabel: string;
  esLabel: string;
  deLabel: string;
  arLabel: string;
  about: string;
  privacy: string;
  terms: string;
  contact: string;
  seoTitle: string;
  aboutPrefix: string;
  imageCategory: string;
  securityCategory: string;
  timeCategory: string;
  displayCategory: string;
  measurementCategory: string;
  generatorCategory: string;
  uploadImage: string;
  compress: string;
  convertToWebP: string;
  download: string;
  reset: string;
  original: string;
  compressed: string;
  size: string;
  format: string;
  validate: string;
  generatePassword: string;
  length: string;
  includeUppercase: string;
  includeLowercase: string;
  includeNumbers: string;
  includeSymbols: string;
  compare: string;
};

const TOOL_TEXTS: Record<Locale, { tools: Record<string, ToolText>; common: CommonText }> = {
  en: {
    tools: {
      imagecompressor: {
        title: "Image Compressor",
        description: "Compress images online",
        seo: "Compress and convert to webp.",
        longDescription: "Image Compressor is a browser-based tool that allows you to reduce file sizes of images without significantly sacrificing visual quality. It supports common formats like JPEG, PNG, and WebP.",
        usageContext: "Use this tool when you need to optimize images for web use, email attachments, or to save storage space on your devices.",
        howToUse: "1. Upload your image file.\n2. Adjust the compression quality settings.\n3. Preview the estimated file size.\n4. Download the compressed image.",
        faq: [{"q":"Is my data safe?","a":"Yes, all processing happens locally in your browser. Your images are never uploaded to our servers."},{"q":"What formats are supported?","a":"We support JPEG, PNG, and WebP formats."}]
      },
      caseconverter: {
        title: "Case Converter",
        description: "Change text case",
        seo: "Convert text to uppercase or lowercase.",
        longDescription: "Case Converter is a simple yet powerful text utility that helps you transform the casing of your text instantly. Whether you need Uppercase, Lowercase, or Title Case, this tool handles it all.",
        usageContext: "Ideal for developers, writers, and students who need to format text for code, titles, or general documentation quickly.",
        howToUse: "1. Paste your text into the input area.\n2. Click on the desired case button (Upper, Lower, etc.).\n3. Copy the transformed text to your clipboard.",
        faq: [{"q":"Does it support special characters?","a":"Yes, it preserves all special characters and numbers while changing letter cases."}]
      },
      jsonformatter: {
        title: "JSON Formatter",
        description: "Format and validate JSON",
        seo: "Format invalid JSON.",
        longDescription: "JSON Formatter is a specialized tool for developers to beautify, minify, and validate JSON data. It makes complex data structures readable and helps identify syntax errors.",
        usageContext: "Perfect for debugging API responses, formatting config files, or sharing clean data structures with teammates.",
        howToUse: "1. Enter your raw JSON text.\n2. Click 'Format' to beautify or 'Minify' to compress.\n3. Check the validation indicator for syntax errors.",
        faq: [{"q":"Can it handle large JSON files?","a":"It can handle files up to several megabytes depending on your browser's performance."}]
      },
      passwordgenerator: { title: "Password Generator", description: "Create secure passwords", seo: "Generate random passwords." },
      textdiffchecker: {
        title: "Text Diff Checker",
        description: "Compare texts",
        seo: "Find differences between texts.",
        longDescription: "Text Diff Checker identifies the exact differences between two pieces of text. It highlights additions, deletions, and modifications, making it easy to track changes across versions.",
        usageContext: "Highly useful for developers comparing code, editors reviewing drafts, or anyone needing to verify text consistency.",
        howToUse: "1. Paste the original text in the left panel.\n2. Paste the modified text in the right panel.\n3. Review the highlighted differences instantly.",
        faq: [{"q":"Does it support line-by-line comparison?","a":"Yes, the tool performs a detailed diff analysis to show exactly what changed in each line."}]
      },
      base64encoder: {
        title: "Base64 Encoder & Decoder",
        description: "Encode and Decode Base64 Online",
        seo: "Fast and reliable Base64 encoder and decoder. Convert text to Base64 format and decode Base64 strings instantly in your browser.",
        longDescription: "Base64 Encoder & Decoder is a reliable utility for converting text to Base64 format and vice versa. It uses standard encoding algorithms suitable for data transmission and various development tasks.",
        usageContext: "Commonly used for embedding images in HTML/CSS, transferring binary data over text-based protocols, or simple data obfuscation.",
        howToUse: "1. Enter the text you wish to encode or decode.\n2. Click the 'Encode' or 'Decode' button.\n3. Copy the resulting string from the output area.",
        faq: [{"q":"Is Base64 a form of encryption?","a":"No, Base64 is an encoding scheme meant for data representation, not for security or privacy."}]
      },
      colorconverter: {
        title: "Color Code Converter",
        description: "Convert HEX, RGB, and HSL Colors",
        seo: "Quickly convert color code formats. Input HEX, RGB, or use the color picker to instantly get HSL and RGB values with our browser-based tool.",
        longDescription: "Color Code Converter is a must-have tool for web designers and developers. It allows for seamless translation between HEX, RGB, and HSL color formats with a real-time preview.",
        usageContext: "Use it while designing websites or apps to quickly find the equivalent codes for your color palettes.",
        howToUse: "1. Enter a color code in any format (HEX, RGB, HSL) or use the color picker.\n2. View the converted values instantly.\n3. Click Copy next to any value to use it in your project.",
        faq: [{"q":"Does it support transparency (Alpha)?","a":"The current version focuses on standard colors. RGBA support is planned for future updates."}]
      },
      ruler: {
        title: "Online Ruler",
        description: "Measure screen distances with zero-point placement, credit-card calibration, and cm/inch toggles.",
        longDescription: "The Online Ruler is a high-precision measurement tool that allows you to measure objects directly on your screen. It features zero-point adjustment and calibration against standard objects like credit cards to ensure accuracy regardless of your screen resolution or size.",
        usageContext: "Perfect for designers, hobbyists, or anyone needing quick measurements of small physical objects or screen elements when a physical ruler isn't handy.",
        howToUse: "1. Select your preferred unit (cm or inch).\n2. Calibrate by entering the width of a standard object (like a credit card).\n3. Double-click on the ruler to set a zero point.\n4. Place your object against the screen to measure.",
        faq: [{"q":"How accurate is the screen ruler?","a":"Accuracy depends on calibration. Since screen sizes and resolutions vary, calibrating with a physical object (like a credit card) is essential for precision."}]
      },
      wordcounter: {
        title: "Word Counter",
        description: "Count characters, spaces, and character positions as you type.",
        longDescription: "Word Counter is a real-time text analysis tool that calculates the number of words, characters, and spaces in your text. It also provides detailed breakdowns such as character count without spaces and specific character positioning.",
        usageContext: "Essential for writers, students, and SEO professionals who need to meet specific length requirements for essays, articles, social media posts, or meta descriptions.",
        howToUse: "1. Type or paste your text into the input field.\n2. View the automatically updated counts below.\n3. Use the character position finder to locate specific indices in your text.",
        faq: [{"q":"Is there a limit to the text size?","a":"Our word counter can handle large volumes of text (up to hundreds of thousands of characters) efficiently within your browser."}]
      },
      countdown: {
        title: "Countdown Timer",
        description: "Set a timer, pause it, resume it, and keep track in fullscreen or night mode.",
        longDescription: "Our Countdown Timer is a versatile time management tool designed for productivity and focus. It features a clean, distraction-free interface with full-screen and night mode options.",
        usageContext: "Ideal for Pomodoro sessions, meditation, cooking, or managing presentation times.",
        howToUse: "1. Set the desired time using the input fields.\n2. Click Start to begin the countdown.\n3. Use Pause or Reset as needed.\n4. Toggle Night Mode or Fullscreen for better focus.",
        faq: [{"q":"Does the timer keep running if I switch tabs?","a":"Yes, the timer continues to run in the background as long as the tab remains open."}]
      },
      digitalclock: {
        title: "Digital Clock",
        description: "Check the current time in real time with a fullscreen view.",
        longDescription: "Digital Clock provides a sleek, high-visibility time display for any environment. It supports both 12-hour and 24-hour formats and includes a full-screen mode for use as a desk clock.",
        usageContext: "Great for use in offices, classrooms, or as a bedside clock using a tablet or laptop screen.",
        howToUse: "1. View the current time in the central display.\n2. Switch between 12H and 24H formats.\n3. Enable Fullscreen mode for a large, clear display.",
        faq: [{"q":"Is the time synced accurately?","a":"Yes, the clock uses your device's system time, which is typically synchronized with network time servers."}]
      },
      screenlamp: {
        title: "Screen Lights",
        description: "Turn the screen into a solid color light with fullscreen and custom color choices.",
        longDescription: "Screen Lights turns your entire display into a source of soft, uniform light. You can choose from preset colors or select a custom hue to create the perfect ambiance or use it for emergency lighting.",
        usageContext: "Useful as a soft reading light, a photography backlight, or for testing screen pixels (dead pixel check).",
        howToUse: "1. Choose a preset color or use the color picker for a custom hue.\n2. Adjust the lighting as needed.\n3. Use Fullscreen mode for maximum effect.",
        faq: [{"q":"Can this act as a blue light filter?","a":"By choosing a warm orange or red hue, you can reduce blue light emission from your screen manually."}]
      },
      qrgenerator: {
        title: "QR Generator",
        description: "Create QR codes instantly from any text or URL.",
        longDescription: "Our QR Generator allows you to create high-quality QR codes for URLs, text, and other data types. Use it to bridge the gap between physical and digital content.",
        usageContext: "Great for marketing materials, business cards, menus, and event check-ins.",
        howToUse: "1. Input the URL or text you want to encode.\n2. Customize the size or error correction if available.\n3. Download the generated QR code image.",
        faq: [{"q":"Are these QR codes permanent?","a":"Yes, they contain static information and will work as long as the linked content is available."}]
      },
      barcodegenerator: {
        title: "Barcode Generator",
        description: "Create many barcode formats for labels, inventory, and packaging.",
        longDescription: "Barcode Generator supports multiple professional barcode formats including Code 128, EAN, and UPC. It provides industrial-grade barcode rendering for various business needs.",
        usageContext: "Used for inventory management, product labeling, and retail operations.",
        howToUse: "1. Select the barcode symbology (e.g., Code 128).\n2. Enter the data to be encoded.\n3. Generate and download the high-resolution barcode image.",
        faq: [{"q":"Which formats are available?","a":"We support Code 128, EAN-13, UPC-A, and several others."}]
      },
      dummytext: { title: "Lorem Ipsum", description: "Generate placeholder paragraphs with a chosen length." },
    },
    common: {
      copyAll: "Copy All",
      clear: "Clear",
      sample: "Sample text",
      placeholder: "Paste or type text here...",
      paragraphs: "Paragraphs",
      generatedText: "Generated Text",
      charCountWithSpaces: "Character count (with spaces)",
      charCountWithoutSpaces: "Character count (without spaces)",
      whichPosition: "Which character position would you like to find?",
      backToTools: "Back to all tools",
      copied: "Copied to clipboard!",
      languageSelect: "Select Content Language",
      highlightHelp: "* The character at the specified index is highlighted in real-time within the text area above.",
      allTools: "All Tools",
      footerNote1: "This tool is part of the apps24 utility suite.",
      footerNote2: "All processing happens locally in your browser for maximum privacy and speed.",
      koLabel: "Korean",
      enLabel: "English",
      textCategory: "Text",
      utilityCategory: "Utility",
      positionPlaceholder: "Position",
      twelveHour: "12H",
      twentyFourHour: "24H",
      fontSize: "Size",
      customColor: "Custom",
      presetColors: "Presets",
      homeTitle: "Fast Multilingual Tools",
      homeSubtitle: "Simple utilities for quick tasks, perfectly localized for your language.",
      rulerHowTo: "How to Use the Online Ruler",
      rulerStep1: "Place a credit card horizontally at the zero mark.",
      rulerStep2: "Enter the measured width of the card and click 'Calibrate'.",
      rulerStep3: "Now you can measure the desired object.",
      rulerEnterCardWidth: "Enter the credit card width",
      rulerExample: "Example: If the width is 10.4 cm, enter 10.4",
      rulerTip: "Tip: Double-click (or double-tap) anywhere on the ruler to set it as the zero point (0,0). Use the blue handle at the bottom-right to resize.",
      calibrate: "Calibrate",
      changeTo: "Change to",
      exitFullscreen: "Exit full screen",
      fullscreen: "Full screen",
      frLabel: "French",
      jaLabel: "Japanese",
      zhLabel: "Chinese (Simplified)",
      zhTWLabel: "Chinese (Traditional)",
      ptLabel: "Portuguese",
      esLabel: "Spanish",
      deLabel: "German",
      arLabel: "Arabic",
      about: "About Us",
      privacy: "Privacy Policy",
      terms: "Terms",
      contact: "Contact",
      seoTitle: "Professional Guide",
      aboutPrefix: "This free online tool is optimized...",
      imageCategory: "Image",
      securityCategory: "Security",
      timeCategory: "Time",
      displayCategory: "Display",
      measurementCategory: "Measurement",
      generatorCategory: "Generator",
      uploadImage: "Upload",
      compress: "Compress",
      convertToWebP: "Convert WebP",
      download: "Download",
      reset: "Reset",
      original: "Original",
      compressed: "Compressed",
      size: "Size",
      format: "Format JSON",
      validate: "Validate",
      generatePassword: "Generate Password",
      length: "Length",
      includeUppercase: "Uppercase",
      includeLowercase: "Lowercase",
      includeNumbers: "Numbers",
      includeSymbols: "Symbols",
      compare: "Compare",
    },
  },
  ko: {
    tools: {
      imagecompressor: {
        title: "이미지 압축기",
        description: "이미지 용량을 실시간으로 압축하세요.",
        seo: "이미지 압축 및 WebP 변환.",
        longDescription: "이미지 압축기는 시각적 품질을 크게 희생하지 않으면서 이미지 파일 크기를 줄일 수 있는 브라우저 기반 도구입니다. JPEG, PNG, WebP와 같은 일반적인 형식을 지원합니다.",
        usageContext: "웹 사용, 이메일 첨부 또는 기기의 저장 공간을 절약하기 위해 이미지를 최적화해야 할 때 이 도구를 사용하세요.",
        howToUse: "1. 이미지 파일을 업로드합니다.\n2. 압축 품질 설정을 조정합니다.\n3. 예상 파일 크기를 미리 확인합니다.\n4. 압축된 이미지를 다운로드합니다.",
        faq: [{"q":"제 데이터는 안전한가요?","a":"네, 모든 처리는 브라우저에서 로컬로 진행됩니다. 귀하의 이미지는 절대 저희 서버로 업로드되지 않습니다."},{"q":"어떤 형식을 지원하나요?","a":"JPEG, PNG, WebP 형식을 지원합니다."}]
      },
      caseconverter: {
        title: "대소문자 변환기",
        description: "텍스트 대소문자를 즉시 변환하세요.",
        seo: "대소문자 변환 및 텍스트 가공.",
        longDescription: "대소문자 변환기는 텍스트의 대소문자를 즉시 변환할 수 있도록 도와주는 간단하지만 강력한 텍스트 유틸리티입니다. 대문자, 소문자, 제목 대소문자 등 모든 것을 처리합니다.",
        usageContext: "코드, 제목 또는 일반 문서를 위해 텍스트 형식을 빠르게 지정해야 하는 개발자, 작가 및 학생에게 이상적입니다.",
        howToUse: "1. 입력 영역에 텍스트를 붙여넣습니다.\n2. 원하는 케이스 버튼(대문자, 소문자 등)을 클릭합니다.\n3. 변환된 텍스트를 클립보드에 복사합니다.",
        faq: [{"q":"특수 문자를 지원하나요?","a":"네, 대소문자를 변경하는 동안 모든 특수 문자와 숫자는 보존됩니다."}]
      },
      jsonformatter: {
        title: "JSON 포맷터",
        description: "JSON 코드를 예쁘게 정렬하고 검증하세요.",
        seo: "JSON 포맷팅 및 유효성 검사.",
        longDescription: "JSON 포맷터는 개발자가 JSON 데이터를 예쁘게 정렬하거나 압축하고 유효성을 검사할 수 있는 전문 도구입니다. 복잡한 데이터 구조를 읽기 쉽게 만들고 구문 오류를 찾는 데 도움을 줍니다.",
        usageContext: "API 응답 디버깅, 설정 파일 서식 지정 또는 팀원과 깔끔한 데이터 구조를 공유할 때 완벽합니다.",
        howToUse: "1. 원시 JSON 텍스트를 입력합니다.\n2. 'Format'을 클릭하여 정렬하거나 'Minify'를 클릭하여 압축합니다.\n3. 구문 오류에 대한 유효성 검사 표시를 확인합니다.",
        faq: [{"q":"대용량 JSON 파일을 처리할 수 있나요?","a":"브라우저의 성능에 따라 수 메가바이트 크기까지 처리할 수 있습니다."}]
      },
      passwordgenerator: { title: "비밀번호 생성기", description: "강력하고 안전한 비밀번호를 생성하세요.", seo: "무작위 비밀번호 생성기." },
      textdiffchecker: {
        title: "텍스트 비교기",
        description: "두 텍스트의 차이점을 한눈에 확인하세요.",
        seo: "텍스트 디프 체크 및 비교.",
        longDescription: "텍스트 비교기는 두 텍스트 사이의 정확한 차이점을 식별합니다. 추가, 삭제 및 수정된 내용을 강조 표시하여 버전 간 변경 내용을 쉽게 추적할 수 있습니다.",
        usageContext: "코드를 비교하는 개발자, 초안을 검토하는 편집자 또는 텍스트 일관성을 확인해야 하는 모든 분께 매우 유용합니다.",
        howToUse: "1. 왼쪽 패널에 원본 텍스트를 붙여넣습니다.\n2. 오른쪽 패널에 수정된 텍스트를 붙여넣습니다.\n3. 강조 표시된 차이점을 즉시 확인합니다.",
        faq: [{"q":"한 줄씩 비교 기능을 지원하나요?","a":"네, 각 줄에서 변경된 내용을 정확히 보여주기 위해 상세한 비교 분석을 수행합니다."}]
      },
      base64encoder: {
        title: "Base64 인코더 / 디코더",
        description: "온라인 Base64 텍스트 인코딩 및 디코딩",
        seo: "빠르고 안정적인 Base64 인코더 및 디코더입니다. 브라우저에서 텍스트를 즉시 Base64로 변환하거나 해독해보세요.",
        longDescription: "Base64 인코더 및 디코더는 텍스트를 Base64 형식으로 변환하거나 그 반대로 변환하는 신뢰할 수 있는 유틸리티입니다. 데이터 전송 및 다양한 개발 작업에 적합한 표준 인코딩 알고리즘을 사용합니다.",
        usageContext: "HTML/CSS에 이미지를 포함하거나, 텍스트 기반 프로토콜을 통한 바이너리 데이터 전송, 또는 간단한 데이터 난독화에 흔히 사용됩니다.",
        howToUse: "1. 인코딩하거나 디코딩하려는 텍스트를 입력합니다.\n2. 'Encode' 또는 'Decode' 버튼을 클릭합니다.\n3. 결과창에서 변환된 문자열을 복사합니다.",
        faq: [{"q":"Base64는 암호화의 일종인가요?","a":"아니요, Base64는 보안이나 프라이버시를 위한 것이 아니라 데이터 표현을 위한 인코딩 방식입니다."}]
      },
      colorconverter: {
        title: "색상 코드 변환기",
        description: "HEX, RGB, HSL 색상 코드 실시간 변환",
        seo: "HEX, RGB 코드를 입력하거나 컬러 피커로 색을 선택해 HSL 등의 값을 즉시 확인하고 복사하세요.",
        longDescription: "색상 코드 변환기는 웹 디자이너와 개발자에게 꼭 필요한 도구입니다. 실시간 미리보기와 함께 HEX, RGB, HSL 색상 형식 사이의 완벽한 변환을 지원합니다.",
        usageContext: "웹사이트나 앱을 디자인하는 동안 컬러 팔레트의 동등한 코드를 빠르게 찾는 데 사용하세요.",
        howToUse: "1. 어떤 형식이든 색상 코드를 입력하거나 컬러 피커를 사용합니다.\n2. 즉시 변환된 값들을 확인합니다.\n3. 프로젝트에 사용하려는 값 옆의 'Copy'를 클릭합니다.",
        faq: [{"q":"투명도(Alpha)를 지원하나요?","a":"현재 버전은 표준 색상에 집중하고 있습니다. RGBA 지원은 향후 업데이트 예정입니다."}]
      },
      ruler: {
        title: "온라인 자",
        description: "영점 설정, 신용카드 보정, cm/inch 전환으로 화면 길이를 측정합니다.",
        longDescription: "온라인 자는 화면에서 직접 물체를 측정할 수 있게 해주는 고정밀 측정 도구입니다. 0점 조절 기능과 신용카드와 같은 표준 물체를 이용한 보정 기능을 갖추고 있어 화면 해상도나 크기에 상관없이 정확한 측정이 가능합니다.",
        usageContext: "디자이너, 취미 생활자 또는 실제 자가 없을 때 작은 물리적 물체나 화면 요소를 빠르게 측정해야 하는 모든 분께 완벽한 도구입니다.",
        howToUse: "1. 선호하는 단위(cm 또는 인치)를 선택합니다.\n2. 신용카드와 같은 표준 물체의 너비를 입력하여 보정합니다.\n3. 자 위의 아무 곳이나 더블 클릭하여 0점을 설정합니다.\n4. 측정할 물체를 화면에 대고 측정합니다.",
        faq: [{"q":"화면 자의 정확도는 어느 정도인가요?","a":"정확도는 보정에 달렸습니다. 화면 크기와 해상도가 다양하므로 실제 물체(신용카드 등)를 이용한 보정이 정밀한 측정에 필수적입니다."}]
      },
      wordcounter: {
        title: "글자 수 세기",
        description: "입력한 텍스트의 글자 수와 공백 포함/제외 수를 즉시 계산합니다.",
        longDescription: "글자 수 세기는 텍스트의 단어, 글자, 공백 수를 계산하는 실시간 텍스트 분석 도구입니다. 공백을 제외한 글자 수 및 특정 글자 위치 찾기 등 상세한 분석 결과도 제공합니다.",
        usageContext: "에세이, 기사, 소셜 미디어 게시물 또는 메타 설명의 특정 길이 요구 사항을 맞춰야 하는 작가, 학생 및 SEO 전문가에게 필수적입니다.",
        howToUse: "1. 입력 필드에 텍스트를 입력하거나 붙여넣습니다.\n2. 하단에서 자동 업데이트되는 카운트를 확인합니다.\n3. 글자 위치 찾기 기능을 사용하여 텍스트 내의 특정 인덱스를 찾습니다.",
        faq: [{"q":"텍스트 크기에 제한이 있나요?","a":"저희 글자 수 세기는 수십만 자에 달하는 대용량 텍스트도 브라우저 내에서 효율적으로 처리할 수 있습니다."}]
      },
      countdown: {
        title: "카운트다운 타이머",
        description: "시간을 설정하고 일시정지, 재개, 전체화면, 나이트 모드를 사용할 수 있습니다.",
        longDescription: "카운트다운 타이머는 생산성과 집중력을 위해 설계된 다목적 시간 관리 도구입니다. 전체 화면 및 나이트 모드 옵션과 함께 깔끔하고 방해가 없는 인터페이스를 제공합니다.",
        usageContext: "뽀모도로 세션, 명상, 요리 또는 발표 시간 관리에 이상적입니다.",
        howToUse: "1. 입력 필드를 사용하여 원하는 시간을 설정합니다.\n2. 'Start'를 클릭하여 카운트다운을 시작합니다.\n3. 필요한 경우 일시정지 또는 초기화를 사용합니다.\n4. 더 나은 집중을 위해 나이트 모드나 전체 화면으로 전환합니다.",
        faq: [{"q":"탭을 전환해도 타이머가 계속 작동하나요?","a":"네, 탭이 열려 있는 한 타이머는 백그라운드에서 계속 작동합니다."}]
      },
      digitalclock: {
        title: "디지털 시계",
        description: "현재 시간을 실시간으로 확인하고 전체화면으로 볼 수 있습니다.",
        longDescription: "디지털 시계는 어떤 환경에서도 잘 보이는 세련된 시간 디스플레이를 제공합니다. 12시간제와 24시간제를 모두 지원하며, 탁상시계로 활용 가능한 전체 화면 모드를 포함합니다.",
        usageContext: "사무실, 교실 또는 태블릿/노트북 화면을 이용한 침대 옆 시계로 사용하기 좋습니다.",
        howToUse: "1. 중앙 디스플레이에서 현재 시간을 확인합니다.\n2. 12H와 24H 형식 사이를 전환합니다.\n3. 크고 선명한 화면을 위해 전체 화면 모드를 활성화합니다.",
        faq: [{"q":"시간이 정확하게 동기화되나요?","a":"네, 시계는 기기의 시스템 시간을 사용하며, 이는 일반적으로 네트워크 시간 서버와 동기화됩니다."}]
      },
      screenlamp: {
        title: "스크린 라이트",
        description: "전체화면과 사용자 색상으로 화면 전체를 단색 조명으로 바꿉니다.",
        longDescription: "스크린 라이트는 전체 디스플레이를 부드럽고 균일한 광원으로 바꿔줍니다. 프리셋 색상을 선택하거나 커스텀 색상을 골라 완벽한 분위기를 조성하거나 비상 조명으로 사용할 수 있습니다.",
        usageContext: "부드러운 독서등, 촬영용 백라이트 또는 화면 픽셀 테스트(불량 화소 체크) 시 유용합니다.",
        howToUse: "1. 프리셋 색상을 선택하거나 컬러 피커를 사용하여 원하는 색상을 고릅니다.\n2. 필요에 따라 조명을 조정합니다.\n3. 최대 효과를 위해 전체 화면 모드를 사용합니다.",
        faq: [{"q":"블루라이트 차단 기능이 있나요?","a":"따뜻한 오렌지색이나 빨간색 계열을 선택하여 화면에서의 블루라이트 방출을 수동으로 줄일 수 있습니다."}]
      },
      qrgenerator: {
        title: "QR 생성기",
        description: "텍스트나 URL로 QR 코드를 바로 생성합니다.",
        longDescription: "저희 QR 생성기를 사용하면 URL, 텍스트 및 기타 데이터 유형에 대한 고품질 QR 코드를 만들 수 있습니다. 물리적 콘텐츠와 디지털 콘텐츠 사이의 격차를 해소하는 데 사용하세요.",
        usageContext: "마케팅 자료, 명함, 메뉴 및 이벤트 체크인에 적합합니다.",
        howToUse: "1. 인코딩하려는 URL이나 텍스트를 입력합니다.\n2. 크기나 오류 수정을 조정합니다.\n3. 생성된 QR 코드 이미지를 다운로드합니다.",
        faq: [{"q":"이 QR 코드는 영구적인가요?","a":"네, 정적 정보를 포함하고 있으며 연결된 콘텐츠가 유효한 한 영구적으로 작동합니다."}]
      },
      barcodegenerator: {
        title: "바코드 생성기",
        description: "라벨, 재고, 포장용 여러 바코드 형식을 생성합니다.",
        longDescription: "바코드 생성기는 Code 128, EAN, UPC를 포함한 여러 전문 바코드 형식을 지원합니다. 다양한 비즈니스 요구에 적합한 산업 등급의 바코드 렌더링을 제공합니다.",
        usageContext: "재고 관리, 제품 라벨링 및 소매 업무에 사용됩니다.",
        howToUse: "1. 바코드 종류(예: Code 128)를 선택합니다.\n2. 인코딩할 데이터를 입력합니다.\n3. 생성된 고해상도 바코드 이미지를 다운로드합니다.",
        faq: [{"q":"어떤 형식을 사용할 수 있나요?","a":"Code 128, EAN-13, UPC-A 및 여러 형식을 지원합니다."}]
      },
      dummytext: { title: "로렘 입숨", description: "문단 수를 정해 자리표시자 텍스트를 생성합니다." },
    },
    common: {
      copyAll: "전체 복사",
      clear: "지우기",
      sample: "샘플 텍스트",
      placeholder: "여기에 텍스트를 입력하거나 붙여넣으세요...",
      paragraphs: "문단 수",
      generatedText: "생성된 텍스트",
      charCountWithSpaces: "글자 수 (공백 포함)",
      charCountWithoutSpaces: "글자 수 (공백 제외)",
      whichPosition: "찾고 싶은 글자 위치는 어디인가요?",
      backToTools: "전체 도구로 돌아가기",
      copied: "클립보드에 복사되었습니다!",
      languageSelect: "콘텐츠 언어 선택",
      highlightHelp: "* 지정된 인덱스의 글자가 상단 입력창 내에서 실시간으로 강조되어 표시됩니다.",
      allTools: "모든 도구",
      footerNote1: "이 도구는 apps24 유틸리티 제품군의 일부입니다.",
      footerNote2: "모든 처리는 개인 정보 보호와 속도를 위해 브라우저에서 로컬로 수행됩니다.",
      koLabel: "한국어",
      enLabel: "영어",
      textCategory: "텍스트",
      utilityCategory: "유틸리티",
      positionPlaceholder: "위치",
      twelveHour: "12시간",
      twentyFourHour: "24시간",
      fontSize: "크기",
      customColor: "선택",
      presetColors: "프리셋",
      homeTitle: "빠른 다국어 도구 모음",
      homeSubtitle: "간단한 작업을 위한 유틸리티, 당신의 언어에 완벽하게 맞춰져 있습니다.",
      rulerHowTo: "온라인 자 사용법",
      rulerStep1: "신용카드를 가로로 0점 표시 부분에 놓습니다.",
      rulerStep2: "카드의 실제 너비를 입력하고 '보정' 버튼을 누릅니다.",
      rulerStep3: "이제 원하는 물체를 측정할 수 있습니다.",
      rulerEnterCardWidth: "신용카드 너비를 입력하세요",
      rulerExample: "예시: 너비가 10.4 cm인 경우 10.4 입력",
      rulerTip: "팁: 자 위의 아무 곳이나 더블 클릭(또는 더블 탭)하면 그 지점이 0점으로 설정됩니다. 우측 하단 파란색 핸들로 크기를 조절하세요.",
      calibrate: "보정하기",
      changeTo: "단위 변경:",
      exitFullscreen: "전체화면 종료",
      fullscreen: "전체화면",
      frLabel: "프랑스어",
      jaLabel: "일본어",
      zhLabel: "중국어(간체)",
      zhTWLabel: "중국어(번체)",
      ptLabel: "포르투갈어",
      esLabel: "스페인어",
      deLabel: "독일어",
      arLabel: "아랍어",
      about: "소개",
      privacy: "개인정보처리방침",
      terms: "이용약관",
      contact: "문의하기",
      seoTitle: "전문가 가이드",
      aboutPrefix: "이 무료 온라인 도구는...",
      imageCategory: "이미지",
      securityCategory: "보안",
      timeCategory: "시간",
      displayCategory: "디스플레이",
      measurementCategory: "측정",
      generatorCategory: "생성기",
      uploadImage: "업로드",
      compress: "압축",
      convertToWebP: "WebP 변환",
      download: "다운로드",
      reset: "초기화",
      original: "원본",
      compressed: "압축됨",
      size: "크기",
      format: "JSON 포맷팅",
      validate: "검증",
      generatePassword: "비밀번호 생성",
      length: "길이",
      includeUppercase: "대문자",
      includeLowercase: "소문자",
      includeNumbers: "숫자",
      includeSymbols: "기호",
      compare: "비교",
    },
  },
  fr: {
    tools: {
      imagecompressor: {
        title: "Image Compressor",
        description: "Compress images online",
        seo: "Compress and convert to webp.",
        longDescription: "Image Compressor is a browser-based tool that allows you to reduce file sizes of images without significantly sacrificing visual quality. It supports common formats like JPEG, PNG, and WebP.",
        usageContext: "Use this tool when you need to optimize images for web use, email attachments, or to save storage space on your devices.",
        howToUse: "1. Upload your image file.\n2. Adjust the compression quality settings.\n3. Preview the estimated file size.\n4. Download the compressed image.",
        faq: [{"q":"Is my data safe?","a":"Yes, all processing happens locally in your browser. Your images are never uploaded to our servers."},{"q":"What formats are supported?","a":"We support JPEG, PNG, and WebP formats."}]
      },
      caseconverter: {
        title: "Case Converter",
        description: "Change text case",
        seo: "Convert text to uppercase or lowercase.",
        longDescription: "Case Converter is a simple yet powerful text utility that helps you transform the casing of your text instantly. Whether you need Uppercase, Lowercase, or Title Case, this tool handles it all.",
        usageContext: "Ideal for developers, writers, and students who need to format text for code, titles, or general documentation quickly.",
        howToUse: "1. Paste your text into the input area.\n2. Click on the desired case button (Upper, Lower, etc.).\n3. Copy the transformed text to your clipboard.",
        faq: [{"q":"Does it support special characters?","a":"Yes, it preserves all special characters and numbers while changing letter cases."}]
      },
      jsonformatter: {
        title: "JSON Formatter",
        description: "Format and validate JSON",
        seo: "Format invalid JSON.",
        longDescription: "JSON Formatter is a specialized tool for developers to beautify, minify, and validate JSON data. It makes complex data structures readable and helps identify syntax errors.",
        usageContext: "Perfect for debugging API responses, formatting config files, or sharing clean data structures with teammates.",
        howToUse: "1. Enter your raw JSON text.\n2. Click 'Format' to beautify or 'Minify' to compress.\n3. Check the validation indicator for syntax errors.",
        faq: [{"q":"Can it handle large JSON files?","a":"It can handle files up to several megabytes depending on your browser's performance."}]
      },
      passwordgenerator: { title: "Password Generator", description: "Create secure passwords", seo: "Generate random passwords." },
      textdiffchecker: { title: "Text Diff Checker", description: "Compare texts", seo: "Find differences between texts." },
      base64encoder: { title: "Encodeur / Décodeur Base64", description: "Encoder et Décoder Base64 en ligne", seo: "Encodeur et décodeur Base64 rapide et fiable. Convertissez instantanément du texte en Base64 dans votre navigateur." },
      colorconverter: { title: "Convertisseur de Code Couleur", description: "Convertir HEX, RGB et HSL", seo: "Convertissez rapidement les formats de codes couleurs. Entrez HEX, RGB ou utilisez le sélecteur de couleurs pour obtenir instantanément des valeurs HSL." },
      ruler: {
        title: "Règle en ligne",
        description: "Mesurez les distances à l'écran avec étalonnage par carte de crédit.",
        longDescription: "The Online Ruler is a high-precision measurement tool that allows you to measure objects directly on your screen. It features zero-point adjustment and calibration against standard objects like credit cards to ensure accuracy regardless of your screen resolution or size.",
        usageContext: "Perfect for designers, hobbyists, or anyone needing quick measurements of small physical objects or screen elements when a physical ruler isn't handy.",
        howToUse: "1. Select your preferred unit (cm or inch).\n2. Calibrate by entering the width of a standard object (like a credit card).\n3. Double-click on the ruler to set a zero point.\n4. Place your object against the screen to measure.",
        faq: [{"q":"How accurate is the screen ruler?","a":"Accuracy depends on calibration. Since screen sizes and resolutions vary, calibrating with a physical object (like a credit card) is essential for precision."}]
      },
      wordcounter: {
        title: "Compteur de mots",
        description: "Comptez les caractères et les mots en temps réel.",
        longDescription: "Word Counter is a real-time text analysis tool that calculates the number of words, characters, and spaces in your text. It also provides detailed breakdowns such as character count without spaces and specific character positioning.",
        usageContext: "Essential for writers, students, and SEO professionals who need to meet specific length requirements for essays, articles, social media posts, or meta descriptions.",
        howToUse: "1. Type or paste your text into the input field.\n2. View the automatically updated counts below.\n3. Use the character position finder to locate specific indices in your text.",
        faq: [{"q":"Is there a limit to the text size?","a":"Our word counter can handle large volumes of text (up to hundreds of thousands of characters) efficiently within your browser."}]
      },
      countdown: { title: "Compte à rebours", description: "Réglez une minuterie avec mode plein écran et nuit." },
      digitalclock: { title: "Horloge numérique", description: "Consultez l'heure actuelle en temps réel." },
      screenlamp: { title: "Lampe d'écran", description: "Transformez votre écran en une source lumineuse colorée." },
      qrgenerator: {
        title: "Générateur de QR",
        description: "Créeez instantanément des codes QR.",
        longDescription: "Our QR Generator allows you to create high-quality QR codes for URLs, text, and other data types. Use it to bridge the gap between physical and digital content.",
        usageContext: "Great for marketing materials, business cards, menus, and event check-ins.",
        howToUse: "1. Input the URL or text you want to encode.\n2. Customize the size or error correction if available.\n3. Download the generated QR code image.",
        faq: [{"q":"Are these QR codes permanent?","a":"Yes, they contain static information and will work as long as the linked content is available."}]
      },
      barcodegenerator: {
        title: "Générateur de codes-barres",
        description: "Créez divers formats de codes-barres.",
        longDescription: "Barcode Generator supports multiple professional barcode formats including Code 128, EAN, and UPC. It provides industrial-grade barcode rendering for various business needs.",
        usageContext: "Used for inventory management, product labeling, and retail operations.",
        howToUse: "1. Select the barcode symbology (e.g., Code 128).\n2. Enter the data to be encoded.\n3. Generate and download the high-resolution barcode image.",
        faq: [{"q":"Which formats are available?","a":"We support Code 128, EAN-13, UPC-A, and several others."}]
      },
      dummytext: { title: "Lorem Ipsum", description: "Générez des paragraphes de texte de remplacement." },
    },
    common: {
      copyAll: "Tout copier",
      clear: "Effacer",
      sample: "Texte d'exemple",
      placeholder: "Collez ou tapez votre texte ici...",
      paragraphs: "Paragraphes",
      generatedText: "Texte généré",
      charCountWithSpaces: "Nombre de caractères (avec espaces)",
      charCountWithoutSpaces: "Nombre de caractères (sans espaces)",
      whichPosition: "Quelle position de caractère voulez-vous trouver?",
      backToTools: "Retour aux outils",
      copied: "Copié dans le presse-papiers!",
      languageSelect: "Choisir la langue du contenu",
      highlightHelp: "* Le caractère à l'index spécifié est mis en évidence en temps réel dans la zone de texte ci-dessus.",
      allTools: "Toutes les outils",
      footerNote1: "Cet outil fait partie de la suite utilitaire apps24.",
      footerNote2: "Tout le traitement se fait localement dans votre navigateur pour une confidentialité et une rapidité maximales.",
      koLabel: "Coréen",
      enLabel: "Anglais",
      textCategory: "Texte",
      utilityCategory: "Utilitaire",
      positionPlaceholder: "Position",
      twelveHour: "12H",
      twentyFourHour: "24H",
      fontSize: "Taille",
      customColor: "Couleur",
      presetColors: "Préréglages",
      homeTitle: "Outils multilingues rapides",
      homeSubtitle: "Des utilitaires simples pour des tâches rapides, parfaitement localisés pour votre langue.",
      rulerHowTo: "Comment utiliser la règle en ligne",
      rulerStep1: "Placez une carte de crédit horizontalement sur la marque zéro.",
      rulerStep2: "Entrez la largeur mesurée de la carte et cliquez sur 'Calibrer'.",
      rulerStep3: "Vous pouvez maintenant mesurer l'objet souhaité.",
      rulerEnterCardWidth: "Entrez la largeur de la carte de crédit",
      rulerExample: "Exemple : Si la largeur est de 10,4 cm, entrez 10,4",
      rulerTip: "Conseil : Utilisez la poignée bleue dans le coin inférieur droit du canevas pour le redimensionner.",
      calibrate: "Calibrer",
      changeTo: "Passer à",
      exitFullscreen: "Quitter le plein écran",
      fullscreen: "Plein écran",
      frLabel: "Français",
      jaLabel: "Japonais",
      zhLabel: "Chinois (Simplifié)",
      zhTWLabel: "Chinois (Traditionnel)",
      ptLabel: "Portugais",
      esLabel: "Espagnol",
      deLabel: "Allemand",
      arLabel: "Arabe",
      about: "About Us",
      privacy: "Privacy Policy",
      terms: "Terms",
      contact: "Contact",
      seoTitle: "Professional Guide",
      aboutPrefix: "This free online tool...",
      imageCategory: "Image",
      securityCategory: "Security",
      timeCategory: "Time",
      displayCategory: "Display",
      measurementCategory: "Measurement",
      generatorCategory: "Generator",
      uploadImage: "Upload",
      compress: "Compress",
      convertToWebP: "Convert WebP",
      download: "Download",
      reset: "Reset",
      original: "Original",
      compressed: "Compressed",
      size: "Size",
      format: "Format JSON",
      validate: "Validate",
      generatePassword: "Generate Password",
      length: "Length",
      includeUppercase: "Uppercase",
      includeLowercase: "Lowercase",
      includeNumbers: "Numbers",
      includeSymbols: "Symbols",
      compare: "Compare",
    },
  },
  ja: {
    tools: {
      imagecompressor: {
        title: "Image Compressor",
        description: "Compress images online",
        seo: "Compress and convert to webp.",
        longDescription: "이미지 압축기는 시각적 품질을 크게 희생하지 않으면서 이미지 파일 크기를 줄일 수 있는 브라우저 기반 도구입니다. JPEG, PNG, WebP와 같은 일반적인 형식을 지원합니다.",
        usageContext: "웹 사용, 이메일 첨부 또는 기기의 저장 공간을 절약하기 위해 이미지를 최적화해야 할 때 이 도구를 사용하세요.",
        howToUse: "1. 이미지 파일을 업로드합니다.\n2. 압축 품질 설정을 조정합니다.\n3. 예상 파일 크기를 미리 확인합니다.\n4. 압축된 이미지를 다운로드합니다.",
        faq: [{"q":"제 데이터는 안전한가요?","a":"네, 모든 처리는 브라우저에서 로컬로 진행됩니다. 귀하의 이미지는 절대 저희 서버로 업로드되지 않습니다."},{"q":"어떤 형식을 지원하나요?","a":"JPEG, PNG, WebP 형식을 지원합니다."}]
      },
      caseconverter: {
        title: "Case Converter",
        description: "Change text case",
        seo: "Convert text to uppercase or lowercase.",
        longDescription: "대소문자 변환기는 텍스트의 대소문자를 즉시 변환할 수 있도록 도와주는 간단하지만 강력한 텍스트 유틸리티입니다. 대문자, 소문자, 제목 대소문자 등 모든 것을 처리합니다.",
        usageContext: "코드, 제목 또는 일반 문서를 위해 텍스트 형식을 빠르게 지정해야 하는 개발자, 작가 및 학생에게 이상적입니다.",
        howToUse: "1. 입력 영역에 텍스트를 붙여넣습니다.\n2. 원하는 케이스 버튼(대문자, 소문자 등)을 클릭합니다.\n3. 변환된 텍스트를 클립보드에 복사합니다.",
        faq: [{"q":"특수 문자를 지원하나요?","a":"네, 대소문자를 변경하는 동안 모든 특수 문자와 숫자는 보존됩니다."}]
      },
      jsonformatter: {
        title: "JSON Formatter",
        description: "Format and validate JSON",
        seo: "Format invalid JSON.",
        longDescription: "JSON 포맷터는 개발자가 JSON 데이터를 예쁘게 정렬하거나 압축하고 유효성을 검사할 수 있는 전문 도구입니다. 복잡한 데이터 구조를 읽기 쉽게 만들고 구문 오류를 찾는 데 도움을 줍니다.",
        usageContext: "API 응답 디버깅, 설정 파일 서식 지정 또는 팀원과 깔끔한 데이터 구조를 공유할 때 완벽합니다.",
        howToUse: "1. 원시 JSON 텍스트를 입력합니다.\n2. 'Format'을 클릭하여 정렬하거나 'Minify'를 클릭하여 압축합니다.\n3. 구문 오류에 대한 유효성 검사 표시를 확인합니다.",
        faq: [{"q":"대용량 JSON 파일을 처리할 수 있나요?","a":"브라우저의 성능에 따라 수 메가바이트 크기까지 처리할 수 있습니다."}]
      },
      passwordgenerator: { title: "Password Generator", description: "Create secure passwords", seo: "Generate random passwords." },
      textdiffchecker: { title: "Text Diff Checker", description: "Compare texts", seo: "Find differences between texts." },
      base64encoder: { title: "Base64 エンコーダ / デコーダ", description: "オンラインでBase64をエンコード・デコード", seo: "高速で信頼性の高いBase64エンコーダおよびデコーダ。ブラウザで即座にテキストをBase64形式に変換または解読できます。" },
      colorconverter: { title: "カラーコード変換", description: "HEX、RGB、HSLカラーを変換", seo: "カラーコード形式をすばやく変換します。HEX、RGBを入力するか、カラーピッカーを使用して、即座にHSLおよびRGB値を取得します。" },
      ruler: {
        title: "定規オンライン",
        description: "カード調整機能付きで画面上の長さを測定します。",
        longDescription: "온라인 자는 화면에서 직접 물체를 측정할 수 있게 해주는 고정밀 측정 도구입니다. 0점 조절 기능과 신용카드와 같은 표준 물체를 이용한 보정 기능을 갖추고 있어 화면 해상도나 크기에 상관없이 정확한 측정이 가능합니다.",
        usageContext: "디자이너, 취미 생활자 또는 실제 자가 없을 때 작은 물리적 물체나 화면 요소를 빠르게 측정해야 하는 모든 분께 완벽한 도구입니다.",
        howToUse: "1. 선호하는 단위(cm 또는 인치)를 선택합니다.\n2. 신용카드와 같은 표준 물체의 너비를 입력하여 보정합니다.\n3. 자 위의 아무 곳이나 더블 클릭하여 0점을 설정합니다.\n4. 측정할 물체를 화면에 대고 측정합니다.",
        faq: [{"q":"화면 자의 정확도는 어느 정도인가요?","a":"정확도는 보정에 달렸습니다. 화면 크기와 해상도가 다양하므로 실제 물체(신용카드 등)를 이용한 보정이 정밀한 측정에 필수적입니다."}]
      },
      wordcounter: {
        title: "文字数カウント",
        description: "リアルタイムで文字数や単語数をカウントします。",
        longDescription: "글자 수 세기는 텍스트의 단어, 글자, 공백 수를 계산하는 실시간 텍스트 분석 도구입니다. 공백을 제외한 글자 수 및 특정 글자 위치 찾기 등 상세한 분석 결과도 제공합니다.",
        usageContext: "에세이, 기사, 소셜 미디어 게시물 또는 메타 설명의 특정 길이 요구 사항을 맞춰야 하는 작가, 학생 및 SEO 전문가에게 필수적입니다.",
        howToUse: "1. 입력 필드에 텍스트를 입력하거나 붙여넣습니다.\n2. 하단에서 자동 업데이트되는 카운트를 확인합니다.\n3. 글자 위치 찾기 기능을 사용하여 텍스트 내의 특정 인덱스를 찾습니다.",
        faq: [{"q":"텍스트 크기에 제한이 있나요?","a":"저희 글자 수 세기는 수십만 자에 달하는 대용량 텍스트도 브라우저 내에서 효율적으로 처리할 수 있습니다."}]
      },
      countdown: { title: "カウントダウン", description: "タイマーの設定、一時停止、再開が可能です。" },
      digitalclock: { title: "デジタル時計", description: "現在時間をリアルタイムで確認でき、全画面で表示可能です。" },
      screenlamp: { title: "スクリーンライト", description: "画面を単色の照明として使用できます。" },
      qrgenerator: {
        title: "QR作成",
        description: "テキストやURLからQRコードを即座に作成します。",
        longDescription: "저희 QR 생성기를 사용하면 URL, 텍스트 및 기타 데이터 유형에 대한 고품질 QR 코드를 만들 수 있습니다. 물리적 콘텐츠와 디지털 콘텐츠 사이의 격차를 해소하는 데 사용하세요.",
        usageContext: "마케팅 자료, 명함, 메뉴 및 이벤트 체크인에 적합합니다.",
        howToUse: "1. 인코딩하려는 URL이나 텍스트를 입력합니다.\n2. 크기나 오류 수정을 조정합니다.\n3. 생성된 QR 코드 이미지를 다운로드합니다.",
        faq: [{"q":"이 QR 코드는 영구적인가요?","a":"네, 정적 정보를 포함하고 있으며 연결된 콘텐츠가 유효한 한 영구적으로 작동합니다."}]
      },
      barcodegenerator: {
        title: "バーコード作成",
        description: "各種フォーマットのバーコードを作成します。",
        longDescription: "바코드 생성기는 Code 128, EAN, UPC를 포함한 여러 전문 바코드 형식을 지원합니다. 다양한 비즈니스 요구에 적합한 산업 등급의 바코드 렌더링을 제공합니다.",
        usageContext: "재고 관리, 제품 라벨링 및 소매 업무에 사용됩니다.",
        howToUse: "1. 바코드 종류(예: Code 128)를 선택합니다.\n2. 인코딩할 데이터를 입력합니다.\n3. 생성된 고해상도 바코드 이미지를 다운로드합니다.",
        faq: [{"q":"어떤 형식을 사용할 수 있나요?","a":"Code 128, EAN-13, UPC-A 및 여러 형식을 지원합니다."}]
      },
      dummytext: { title: "ダミーテキスト", description: "プレースホルダー用の文章を生成します。" },
    },
    common: {
      copyAll: "すべてコピー",
      clear: "クリア",
      sample: "サンプルテキスト",
      placeholder: "ここにテキストを入力または貼り付けてください...",
      paragraphs: "段落数",
      generatedText: "生成된 텍스트",
      charCountWithSpaces: "文字数 (空白含む)",
      charCountWithoutSpaces: "文字数 (空白なし)",
      whichPosition: "どの文字位置を確認しますか？",
      backToTools: "ツール一覧に戻る",
      copied: "クリップボード에 복사되었습니다！",
      languageSelect: "コンテンツの言語を選択",
      highlightHelp: "* 指定されたインデックスの文字が、上のテキストエリア内でリアルタイムに強調表示されます。",
      allTools: "すべてのツール",
      footerNote1: "このツールはapps24ユーティリティスイートの一部です。",
      footerNote2: "すべての処理は、最大限의 プライバシーと速度のためにブラウザ内でローカルに行われます。",
      koLabel: "韓国語",
      enLabel: "英語",
      textCategory: "テキスト",
      utilityCategory: "ユーティリティ",
      positionPlaceholder: "位置",
      twelveHour: "12H",
      twentyFourHour: "24H",
      fontSize: "サイズ",
      customColor: "色",
      presetColors: "プリセット",
      homeTitle: "高速多言語ツール",
      homeSubtitle: "あなたの言語に完璧にローカライズされた、迅速なタスクのためのシンプルなユーティリティ。",
      rulerHowTo: "オンライン定規の使い方",
      rulerStep1: "クレジットカードを0の目盛りに水平に置いてください。",
      rulerStep2: "カードの測定された幅を入力し、「調整」をクリックします。",
      rulerStep3: "これで目的の対象物を測定できます。",
      rulerEnterCardWidth: "クレジットカードの幅を入力してください",
      rulerExample: "例：幅が10.4 cmの場合、10.4と入力してください",
      rulerTip: "ヒント：キャンバスの右下隅にある青いハンドルを使用してサイズを変更してください。",
      calibrate: "調整",
      changeTo: "単位変更:",
      exitFullscreen: "全画面表示を終了",
      fullscreen: "全画面表示",
      frLabel: "フランス語",
      jaLabel: "日本語",
      zhLabel: "中国語（簡体字）",
      zhTWLabel: "中国語（繁体字）",
      ptLabel: "ポルトガル語",
      esLabel: "スペイン語",
      deLabel: "ドイツ語",
      arLabel: "アラビア語",
      about: "About Us",
      privacy: "Privacy Policy",
      terms: "Terms",
      contact: "Contact",
      seoTitle: "Professional Guide",
      aboutPrefix: "This free online tool...",
      imageCategory: "Image",
      securityCategory: "Security",
      timeCategory: "Time",
      displayCategory: "Display",
      measurementCategory: "Measurement",
      generatorCategory: "Generator",
      uploadImage: "Upload",
      compress: "Compress",
      convertToWebP: "Convert WebP",
      download: "Download",
      reset: "Reset",
      original: "Original",
      compressed: "Compressed",
      size: "Size",
      format: "Format JSON",
      validate: "Validate",
      generatePassword: "Generate Password",
      length: "Length",
      includeUppercase: "Uppercase",
      includeLowercase: "Lowercase",
      includeNumbers: "Numbers",
      includeSymbols: "Symbols",
      compare: "Compare",
    },
  },
  zh: {
    tools: {
      imagecompressor: { title: "Image Compressor", description: "Compress images online", seo: "Compress and convert to webp." },
      caseconverter: { title: "Case Converter", description: "Change text case", seo: "Convert text to uppercase or lowercase." },
      jsonformatter: { title: "JSON Formatter", description: "Format and validate JSON", seo: "Format invalid JSON." },
      passwordgenerator: { title: "Password Generator", description: "Create secure passwords", seo: "Generate random passwords." },
      textdiffchecker: { title: "Text Diff Checker", description: "Compare texts", seo: "Find differences between texts." },
      base64encoder: { title: "Base64 编码 / 解码器", description: "在线进行Base64编码与解码", seo: "快速可靠的Base64编码和解码器。在浏览器中即时将文本转换为Base64格式并解码。" },
      colorconverter: { title: "颜色代码转换器", description: "转换 HEX、RGB 和 HSL 颜色", seo: "快速转换颜色代码格式。输入HEX、RGB或使用颜色选择器即时获取HSL和RGB值。" },
      ruler: { title: "在线标尺", description: "使用信用卡校准测量屏幕距离。" },
      wordcounter: { title: "字数统计", description: "实时统计字符和单词数量。" },
      countdown: { title: "倒计时", description: "设置计时器，支持全屏和夜间模式。" },
      digitalclock: { title: "数字时钟", description: "实时查看当前时间。" },
      screenlamp: { title: "屏幕灯", description: "将屏幕变为单色照明灯。" },
      qrgenerator: { title: "QR生成器", description: "即时创建二维码。" },
      barcodegenerator: { title: "条形码生成器", description: "生成多种格式的条形码。" },
      dummytext: { title: "乱数假文", description: "生成占位段落文本。" },
    },
    common: {
      copyAll: "全部复制",
      clear: "清除",
      sample: "示例文本",
      placeholder: "在此处粘贴或输入文本...",
      paragraphs: "段落数",
      generatedText: "生成的文本",
      charCountWithSpaces: "字符数 (含空格)",
      charCountWithoutSpaces: "字符数 (不含空格)",
      whichPosition: "您想查找哪个字符位置？",
      backToTools: "返回工具列表",
      copied: "已复制到剪贴板！",
      languageSelect: "选择内容语言",
      highlightHelp: "* 指定索引处的字符将在上面的文本区域中实时突出显示。",
      allTools: "所有工具",
      footerNote1: "此工具是 apps24 实用工具套件的一部分。",
      footerNote2: "所有处理均在您的浏览器中本地完成，以实现最大的隐私和速度。",
      koLabel: "韩语",
      enLabel: "英语",
      textCategory: "文本",
      utilityCategory: "实用程序",
      positionPlaceholder: "位置",
      twelveHour: "12H",
      twentyFourHour: "24H",
      fontSize: "大小",
      customColor: "颜色",
      presetColors: "预设",
      homeTitle: "快速多语言工具",
      homeSubtitle: "为快速任务设计的简单实用程序，完全针对您的语言进行了本地化。",
      rulerHowTo: "如何使用在线标尺",
      rulerStep1: "将信用卡水平放在零刻度处。",
      rulerStep2: "输入测得的卡片宽度并点击“校准”。",
      rulerStep3: "现在您可以测量所需的物体。",
      rulerEnterCardWidth: "输入信用卡宽度",
      rulerExample: "例如：如果宽度为 10.4 厘米，输入 10.4",
      rulerTip: "提示：使用画布右下角的蓝色手柄调整其大小。",
      calibrate: "校准",
      changeTo: "切换至",
      exitFullscreen: "退出全屏",
      fullscreen: "全屏",
      frLabel: "法语",
      jaLabel: "日语",
      zhLabel: "中文 (简体)",
      zhTWLabel: "中文 (繁体)",
      ptLabel: "葡萄牙语",
      esLabel: "西班牙语",
      deLabel: "德语",
      arLabel: "阿拉伯语",
      about: "About Us",
      privacy: "Privacy Policy",
      terms: "Terms",
      contact: "Contact",
      seoTitle: "Professional Guide",
      aboutPrefix: "This free online tool...",
      imageCategory: "Image",
      securityCategory: "Security",
      timeCategory: "Time",
      displayCategory: "Display",
      measurementCategory: "Measurement",
      generatorCategory: "Generator",
      uploadImage: "Upload",
      compress: "Compress",
      convertToWebP: "Convert WebP",
      download: "Download",
      reset: "Reset",
      original: "Original",
      compressed: "Compressed",
      size: "Size",
      format: "Format JSON",
      validate: "Validate",
      generatePassword: "Generate Password",
      length: "Length",
      includeUppercase: "Uppercase",
      includeLowercase: "Lowercase",
      includeNumbers: "Numbers",
      includeSymbols: "Symbols",
      compare: "Compare",
    },
  },
  "zh-TW": {
    tools: {
      imagecompressor: { title: "Image Compressor", description: "Compress images online", seo: "Compress and convert to webp." },
      caseconverter: { title: "Case Converter", description: "Change text case", seo: "Convert text to uppercase or lowercase." },
      jsonformatter: { title: "JSON Formatter", description: "Format and validate JSON", seo: "Format invalid JSON." },
      passwordgenerator: { title: "Password Generator", description: "Create secure passwords", seo: "Generate random passwords." },
      textdiffchecker: { title: "Text Diff Checker", description: "Compare texts", seo: "Find differences between texts." },
      base64encoder: { title: "Base64 編碼 / 解碼器", description: "線上進行Base64編碼與解碼", seo: "快速可靠的Base64編碼和解碼器。在瀏覽器中即時將文本轉換為Base64格式並解碼。" },
      colorconverter: { title: "顏色代碼轉換器", description: "轉換 HEX、RGB 和 HSL 顏色", seo: "快速轉換顏色代碼格式。輸入HEX、RGB或使用顏色選擇器即時獲取HSL和RGB值。" },
      ruler: { title: "線上尺子", description: "使用信用卡校準測量螢幕距離。" },
      wordcounter: { title: "字數統計", description: "即時統計字元核單字數量。" },
      countdown: { title: "倒數計時", description: "設置計時器，支持全螢幕和夜間模式。" },
      digitalclock: { title: "數位時鐘", description: "即時查看目前時間。" },
      screenlamp: { title: "螢幕燈", description: "將螢幕變為單色照明燈。" },
      qrgenerator: { title: "QR產生器", description: "即時建立二維碼。" },
      barcodegenerator: { title: "條形碼產生器", description: "建立多種格式의 條形碼。" },
      dummytext: { title: "Lorem Ipsum", description: "建立佔位段落文字。" },
    },
    common: {
      copyAll: "全部複製",
      clear: "清除",
      sample: "範例文字",
      placeholder: "在此處貼上或輸入文字...",
      paragraphs: "段落數",
      generatedText: "生成的文字",
      charCountWithSpaces: "字元數 (含空格)",
      charCountWithoutSpaces: "字元數 (不含空格)",
      whichPosition: "您想查找哪個字元位置？",
      backToTools: "返回工具列表",
      copied: "已複製到剪貼簿！",
      languageSelect: "選擇內容語言",
      highlightHelp: "* 指定索引處의 字元將在上面的文字區域中即時突出顯示。",
      allTools: "所有工具",
      footerNote1: "此工具是 apps24 實用工具套件的一部分。",
      footerNote2: "所有處理均在您的瀏覽器中本地完成，以實現最大的隱私和速度。",
      koLabel: "韓語",
      enLabel: "英語",
      textCategory: "文本",
      utilityCategory: "公用程式",
      positionPlaceholder: "位置",
      twelveHour: "12H",
      twentyFourHour: "24H",
      fontSize: "大小",
      customColor: "顏色",
      presetColors: "預設",
      homeTitle: "快速多語言工具",
      homeSubtitle: "為快速任務設計的簡單實用程序，完全針對您的語言進行了本地化。",
      rulerHowTo: "如何使用線上標尺",
      rulerStep1: "將信用卡水平放在零刻度處。",
      rulerStep2: "輸入測得的卡片寬度並點擊“校準”。",
      rulerStep3: "現在您可以測量所需的物體。",
      rulerEnterCardWidth: "輸入信用卡寬度",
      rulerExample: "例如：如果寬度為 10.4 厘米，輸入 10.4",
      rulerTip: "提示：使用畫布右下角的藍色手柄調整其大小。",
      calibrate: "校準",
      changeTo: "切換至",
      exitFullscreen: "退出全屏",
      fullscreen: "全屏",
      frLabel: "法語",
      jaLabel: "日語",
      zhLabel: "中文 (簡體)",
      zhTWLabel: "中文 (繁體)",
      ptLabel: "葡萄牙語",
      esLabel: "西班牙語",
      deLabel: "德語",
      arLabel: "阿拉伯語",
      about: "About Us",
      privacy: "Privacy Policy",
      terms: "Terms",
      contact: "Contact",
      seoTitle: "Professional Guide",
      aboutPrefix: "This free online tool...",
      imageCategory: "Image",
      securityCategory: "Security",
      timeCategory: "Time",
      displayCategory: "Display",
      measurementCategory: "Measurement",
      generatorCategory: "Generator",
      uploadImage: "Upload",
      compress: "Compress",
      convertToWebP: "Convert WebP",
      download: "Download",
      reset: "Reset",
      original: "Original",
      compressed: "Compressed",
      size: "Size",
      format: "Format JSON",
      validate: "Validate",
      generatePassword: "Generate Password",
      length: "Length",
      includeUppercase: "Uppercase",
      includeLowercase: "Lowercase",
      includeNumbers: "Numbers",
      includeSymbols: "Symbols",
      compare: "Compare",
    },
  },
  pt: {
    tools: {
      imagecompressor: { title: "Image Compressor", description: "Compress images online", seo: "Compress and convert to webp." },
      caseconverter: { title: "Case Converter", description: "Change text case", seo: "Convert text to uppercase or lowercase." },
      jsonformatter: { title: "JSON Formatter", description: "Format and validate JSON", seo: "Format invalid JSON." },
      passwordgenerator: { title: "Password Generator", description: "Create secure passwords", seo: "Generate random passwords." },
      textdiffchecker: { title: "Text Diff Checker", description: "Compare texts", seo: "Find differences between texts." },
      base64encoder: { title: "Codificador / Decodificador Base64", description: "Codificar e Decodificar Base64 Online", seo: "Codificador e decodificador Base64 rápido e confiável. Converta texto para Base64 e decodifique no seu navegador." },
      colorconverter: { title: "Conversor de Código de Cor", description: "Converter cores HEX, RGB e HSL", seo: "Converta rapidamente formatos de código de cores. Insira HEX ou RGB para obter instantaneamente valores HSL no navegador." },
      ruler: { title: "Régua Online", description: "Meça distâncias na tela com calibração." },
      wordcounter: { title: "Contador de Palavras", description: "Conte caracteres e palavras em tempo real." },
      countdown: { title: "Cronômetro", description: "Defina temporizadores com modo tela cheia." },
      digitalclock: { title: "Relógio Digital", description: "Verifique a hora atual em tempo real." },
      screenlamp: { title: "Luz de Tela", description: "Transforme sua tela em uma luz colorida." },
      qrgenerator: { title: "Gerador de QR", description: "Crie códigos QR instantaneamente." },
      barcodegenerator: { title: "Gerador de Código de Barras", description: "Crie vários formatos de códigos de barras." },
      dummytext: { title: "Lorem Ipsum", description: "Gere parágrafos de texto fictício." },
    },
    common: {
      copyAll: "Copiar tudo",
      clear: "Limpar",
      sample: "Texto de exemplo",
      placeholder: "Cole ou digite o texto aqui...",
      paragraphs: "Parágrafos",
      generatedText: "Texto gerado",
      charCountWithSpaces: "Contagem de caracteres (com espaços)",
      charCountWithoutSpaces: "Contagem de caracteres (sem espaços)",
      whichPosition: "Qual posição de caractere você deseja encontrar?",
      backToTools: "Voltar para ferramentas",
      copied: "Copiado para a área de transferência!",
      languageSelect: "Selecionar idioma do conteúdo",
      highlightHelp: "* O caractere no índice especificado é realçado em tempo real na área de texto acima.",
      allTools: "Todas as ferramentas",
      footerNote1: "Esta ferramenta faz parte da suite de utilitários apps24.",
      footerNote2: "Todo o processamento ocorre localmente no seu navegador para máxima privacidade e velocidade.",
      koLabel: "Coreano",
      enLabel: "Inglês",
      textCategory: "Texto",
      utilityCategory: "Utilitário",
      positionPlaceholder: "Posição",
      twelveHour: "12H",
      twentyFourHour: "24H",
      fontSize: "Tamanho",
      customColor: "Cor",
      presetColors: "Predefinições",
      homeTitle: "Ferramentas Multilíngues Rápidas",
      homeSubtitle: "Utilitários simples para tarefas rápidas, perfeitamente localizados para o seu idioma.",
      rulerHowTo: "Como usar a régua online",
      rulerStep1: "Coloque um cartão de crédito horizontalmente na marca zero.",
      rulerStep2: "Insira a largura medida do cartão e clique em 'Calibrar'.",
      rulerStep3: "Agora você pode medir o objeto desejado.",
      rulerEnterCardWidth: "Insira a largura do cartão de crédito",
      rulerExample: "Exemplo: Se a largura for 10,4 cm, insira 10,4",
      rulerTip: "Dica: Use a alça azul no canto inferior direito da tela para redimensioná-la.",
      calibrate: "Calibrar",
      changeTo: "Mudar para",
      exitFullscreen: "Sair da tela cheia",
      fullscreen: "Tela cheia",
      frLabel: "Francês",
      jaLabel: "Japonês",
      zhLabel: "Chinês (Simplificado)",
      zhTWLabel: "Chinês (Tradicional)",
      ptLabel: "Português",
      esLabel: "Espanhol",
      deLabel: "Alemão",
      arLabel: "Árabe",
      about: "About Us",
      privacy: "Privacy Policy",
      terms: "Terms",
      contact: "Contact",
      seoTitle: "Professional Guide",
      aboutPrefix: "This free online tool...",
      imageCategory: "Image",
      securityCategory: "Security",
      timeCategory: "Time",
      displayCategory: "Display",
      measurementCategory: "Measurement",
      generatorCategory: "Generator",
      uploadImage: "Upload",
      compress: "Compress",
      convertToWebP: "Convert WebP",
      download: "Download",
      reset: "Reset",
      original: "Original",
      compressed: "Compressed",
      size: "Size",
      format: "Format JSON",
      validate: "Validate",
      generatePassword: "Generate Password",
      length: "Length",
      includeUppercase: "Uppercase",
      includeLowercase: "Lowercase",
      includeNumbers: "Numbers",
      includeSymbols: "Symbols",
      compare: "Compare",
    },
  },
  es: {
    tools: {
      imagecompressor: { title: "Image Compressor", description: "Compress images online", seo: "Compress and convert to webp." },
      caseconverter: { title: "Case Converter", description: "Change text case", seo: "Convert text to uppercase or lowercase." },
      jsonformatter: { title: "JSON Formatter", description: "Format and validate JSON", seo: "Format invalid JSON." },
      passwordgenerator: { title: "Password Generator", description: "Create secure passwords", seo: "Generate random passwords." },
      textdiffchecker: { title: "Text Diff Checker", description: "Compare texts", seo: "Find differences between texts." },
      base64encoder: { title: "Codificador / Decodificador Base64", description: "Codificar y Decodificar Base64 en Línea", seo: "Codificador y decodificador Base64 rápido y confiable. Convierta texto al instante." },
      colorconverter: { title: "Conversor de Código de Color", description: "Convertir colores HEX, RGB y HSL", seo: "Convierta rápidamente formatos de código de colores. Introduzca HEX, RGB o elija un color para sus valores HSL." },
      ruler: { title: "Regla en Línea", description: "Mida distancias en pantalla con calibración." },
      wordcounter: { title: "Contador de Palabras", description: "Cuente caracteres y palabras en tiempo real." },
      countdown: { title: "Cuenta Regresiva", description: "Configure temporizadores con modo pantalla completa." },
      digitalclock: { title: "Reloj Digital", description: "Consulte la hora actual en tiempo real." },
      screenlamp: { title: "Luz de Pantalla", description: "Convierta su pantalla en una luz de color." },
      qrgenerator: { title: "Generador de QR", description: "Cree códigos QR al instante." },
      barcodegenerator: { title: "Generador de Códigos de Barras", description: "Cree varios formatos de códigos de barras." },
      dummytext: { title: "Lorem Ipsum", description: "Genere párrafos de texto de relleno." },
    },
    common: {
      copyAll: "Copiar todo",
      clear: "Limpiar",
      sample: "Texto de ejemplo",
      placeholder: "Pegue o escriba el texto aquí...",
      paragraphs: "Párrafos",
      generatedText: "Texto generado",
      charCountWithSpaces: "Recuento de caracteres (con espacios)",
      charCountWithoutSpaces: "Recuento de caracteres (sin espacios)",
      whichPosition: "¿Qué posición de carácter desea buscar?",
      backToTools: "Volver a herramientas",
      copied: "¡Copiado al portapapeles!",
      languageSelect: "Seleccionar idioma del contenido",
      highlightHelp: "* El carácter en el índice especificado se resalta en tiempo real dentro del área de texto de arriba.",
      allTools: "Todas las herramientas",
      footerNote1: "Esta herramienta es parte de la suite de utilidades apps24.",
      footerNote2: "Todo el procesamiento se realiza localmente en su navegador para una máxima privacidad y velocidad.",
      koLabel: "Coreano",
      enLabel: "Inglés",
      textCategory: "Texto",
      utilityCategory: "Utilidad",
      positionPlaceholder: "Posición",
      twelveHour: "12H",
      twentyFourHour: "24H",
      fontSize: "Tamaño",
      customColor: "Color",
      presetColors: "Preajustes",
      homeTitle: "Herramientas Multilingües Rápidas",
      homeSubtitle: "Utilidades sencillas para tareas rápidas, perfectamente localizadas para su idioma.",
      rulerHowTo: "Cómo usar la regla en línea",
      rulerStep1: "Coloque una tarjeta de crédito horizontalmente en la marca cero.",
      rulerStep2: "Ingrese el ancho medido de la tarjeta y haga clic en 'Calibrar'.",
      rulerStep3: "Ahora puede medir el objeto deseado.",
      rulerEnterCardWidth: "Ingrese el ancho de la tarjeta de crédito",
      rulerExample: "Ejemplo: si el ancho es de 10,4 cm, ingrese 10,4",
      rulerTip: "Sugerencia: use el asa azul en la esquina inferior derecha del lienzo para cambiar su tamaño.",
      calibrate: "Calibrar",
      changeTo: "Cambiar a",
      exitFullscreen: "Salir de pantalla completa",
      fullscreen: "Pantalla completa",
      frLabel: "Francés",
      jaLabel: "Japonés",
      zhLabel: "Chino (Simplificado)",
      zhTWLabel: "Chino (Tradicional)",
      ptLabel: "Português",
      esLabel: "Español",
      deLabel: "Alemán",
      arLabel: "Árabe",
      about: "About Us",
      privacy: "Privacy Policy",
      terms: "Terms",
      contact: "Contact",
      seoTitle: "Professional Guide",
      aboutPrefix: "This free online tool...",
      imageCategory: "Image",
      securityCategory: "Security",
      timeCategory: "Time",
      displayCategory: "Display",
      measurementCategory: "Measurement",
      generatorCategory: "Generator",
      uploadImage: "Upload",
      compress: "Compress",
      convertToWebP: "Convert WebP",
      download: "Download",
      reset: "Reset",
      original: "Original",
      compressed: "Compressed",
      size: "Size",
      format: "Format JSON",
      validate: "Validate",
      generatePassword: "Generate Password",
      length: "Length",
      includeUppercase: "Uppercase",
      includeLowercase: "Lowercase",
      includeNumbers: "Numbers",
      includeSymbols: "Symbols",
      compare: "Compare",
    },
  },
  de: {
    tools: {
      imagecompressor: { title: "Image Compressor", description: "Compress images online", seo: "Compress and convert to webp." },
      caseconverter: { title: "Case Converter", description: "Change text case", seo: "Convert text to uppercase or lowercase." },
      jsonformatter: { title: "JSON Formatter", description: "Format and validate JSON", seo: "Format invalid JSON." },
      passwordgenerator: { title: "Password Generator", description: "Create secure passwords", seo: "Generate random passwords." },
      textdiffchecker: { title: "Text Diff Checker", description: "Compare texts", seo: "Find differences between texts." },
      base64encoder: { title: "Base64 Encoder / Decoder", description: "Base64 online verschlüsseln und entschlüsseln", seo: "Schneller und zuverlässiger Base64-Encoder und -Decoder. Konvertieren Sie Text im Browser sofort." },
      colorconverter: { title: "Farbcode-Konverter", description: "HEX, RGB und HSL konvertieren", seo: "Farbcodeformate schnell konvertieren. Geben Sie HEX oder RGB ein, um sofort HSL-Werte zu erhalten." },
      ruler: { title: "Online-Lineal", description: "Messen Sie Bildschirmabstände mit Kalibrierung." },
      wordcounter: { title: "Wortzähler", description: "Zählen Sie Zeichen und Wörter in Echtzeit." },
      countdown: { title: "Countdown-Timer", description: "Stellen Sie Timer mit Vollbildmodus ein." },
      digitalclock: { title: "Digitale Uhr", description: "Überprüfen Sie die aktuelle Uhrzeit in Echtzeit." },
      screenlamp: { title: "Bildschirmlicht", description: "Verwandeln Sie Ihren Bildschirm in ein farbiges Licht." },
      qrgenerator: { title: "QR-Generator", description: "Erstellen Sie sofort QR-Codes." },
      barcodegenerator: { title: "Barcode-Generator", description: "Erstellen Sie verschiedene Barcode-Formate." },
      dummytext: { title: "Blindtext", description: "Generieren Sie Platzhaltertexte." },
    },
    common: {
      copyAll: "Alles kopieren",
      clear: "Löschen",
      sample: "Beispieltext",
      placeholder: "Text hier einfügen oder tippen...",
      paragraphs: "Absätze",
      generatedText: "Generierter Text",
      charCountWithSpaces: "Zeichenanzahl (mit Leerzeichen)",
      charCountWithoutSpaces: "Zeichenanzahl (ohne Leerzeichen)",
      whichPosition: "Welche Zeichenposition möchten Sie finden?",
      backToTools: "Zurück zu den Tools",
      copied: "In die Zwischenablage kopiert!",
      languageSelect: "Inhaltssprache auswählen",
      highlightHelp: "* Das Zeichen am angegebenen Index wird in Echtzeit im obigen Textbereich hervorgehoben.",
      allTools: "Alle Tools",
      footerNote1: "Dieses Tool ist Teil der apps24-Utility-Suite.",
      footerNote2: "Die gesamte Verarbeitung erfolgt lokal in Ihrem Browser für maximale Privatsphäre und Geschwindigkeit.",
      koLabel: "Koreanisch",
      enLabel: "Englisch",
      textCategory: "Text",
      utilityCategory: "Dienstprogramm",
      positionPlaceholder: "Position",
      twelveHour: "12H",
      twentyFourHour: "24H",
      fontSize: "Größe",
      customColor: "Farbe",
      presetColors: "Voreinstellungen",
      homeTitle: "Schnelle mehrsprachige Tools",
      homeSubtitle: "Einfache Dienstprogramme für schnelle Aufgaben, perfekt auf Ihre Sprache lokalisiert.",
      rulerHowTo: "So verwenden Sie das Online-Lineal",
      rulerStep1: "Legen Sie eine Kreditkarte horizontal auf die Nullmarkierung.",
      rulerStep2: "Geben Sie die gemessene Breite der Karte ein und klicken Sie auf 'Kalibrieren'.",
      rulerStep3: "Jetzt können Sie das gewünschte Objekt messen.",
      rulerEnterCardWidth: "Geben Sie die Kreditkartenbreite ein",
      rulerExample: "Beispiel: Wenn die Breite 10,4 cm beträgt, geben Sie 10,4 ein",
      rulerTip: "Tipp: Verwenden Sie den blauen Griff in der unteren rechten Ecke der Zeichenfläche, um deren Größe zu ändern.",
      calibrate: "Kalibrieren",
      changeTo: "Wechseln zu",
      exitFullscreen: "Vollbild beenden",
      fullscreen: "Vollbild",
      frLabel: "Französisch",
      jaLabel: "Japanisch",
      zhLabel: "Chinesisch (Vereinfacht)",
      zhTWLabel: "Chinesisch (Traditionell)",
      ptLabel: "Portugiesisch",
      esLabel: "Spanisch",
      deLabel: "Deutsch",
      arLabel: "Arabisch",
      about: "About Us",
      privacy: "Privacy Policy",
      terms: "Terms",
      contact: "Contact",
      seoTitle: "Professional Guide",
      aboutPrefix: "This free online tool...",
      imageCategory: "Image",
      securityCategory: "Security",
      timeCategory: "Time",
      displayCategory: "Display",
      measurementCategory: "Measurement",
      generatorCategory: "Generator",
      uploadImage: "Upload",
      compress: "Compress",
      convertToWebP: "Convert WebP",
      download: "Download",
      reset: "Reset",
      original: "Original",
      compressed: "Compressed",
      size: "Size",
      format: "Format JSON",
      validate: "Validate",
      generatePassword: "Generate Password",
      length: "Length",
      includeUppercase: "Uppercase",
      includeLowercase: "Lowercase",
      includeNumbers: "Numbers",
      includeSymbols: "Symbols",
      compare: "Compare",
    },
  },
  ar: {
    tools: {
      imagecompressor: { title: "Image Compressor", description: "Compress images online", seo: "Compress and convert to webp." },
      caseconverter: { title: "Case Converter", description: "Change text case", seo: "Convert text to uppercase or lowercase." },
      jsonformatter: { title: "JSON Formatter", description: "Format and validate JSON", seo: "Format invalid JSON." },
      passwordgenerator: { title: "Password Generator", description: "Create secure passwords", seo: "Generate random passwords." },
      textdiffchecker: { title: "Text Diff Checker", description: "Compare texts", seo: "Find differences between texts." },
      base64encoder: { title: "تشفير / فك تشفير Base64", description: "تشفير وفك تشفير Base64 عبر الإنترنت", seo: "مشفر ومفكك Base64 سريع وموثوق. قم بتحويل النص إلى Base64 وفك التشفير على الفور." },
      colorconverter: { title: "محول كود الألوان", description: "تحويل ألوان HEX و RGB و HSL", seo: "تحويل تنسيقات رموز الألوان بسرعة. أدخل HEX أو RGB للحصول على قيم HSL على الفور." },
      ruler: { title: "مسطرة عبر الإنترنت", description: "قياس المسافات على الشاشة مع المعايرة." },
      wordcounter: { title: "عداد الكلمات", description: "عد الحروف والكلمات في الوقت الفعلي." },
      countdown: { title: "مؤقت العد التنازلي", description: "ضبط المؤقتات مع وضع ملء الشاشة." },
      digitalclock: { title: "ساعة رقمية", description: "التحقق من الوقت الحالي في الوقت الفعلي." },
      screenlamp: { title: "إضاءة الشاشة", description: "تحويل شاشتك إلى ضوء ملون." },
      qrgenerator: { title: "مولد QR", description: "إنشاء رموز QR على الفور." },
      barcodegenerator: { title: "مولد الباركود", description: "إنشاء تنسيقات باركود متعددة." },
      dummytext: { title: "نص لوريم إيبسوم", description: "توليد فقرات نصية بديلة." },
    },
    common: {
      copyAll: "نسخ الكل",
      clear: "مسح",
      sample: "نص تجريبي",
      placeholder: "الصق أو اكتب النص هنا...",
      paragraphs: "فقرات",
      generatedText: "النص الناتج",
      charCountWithSpaces: "عدد الحروف (مع المسافات)",
      charCountWithoutSpaces: "عدد الحروف (بدون مسافات)",
      whichPosition: "ما هو موقع الحرف الذي تريد العثور عليه؟",
      backToTools: "العودة إلى الأدوات",
      copied: "تم النسخ إلى الحافظة!",
      languageSelect: "اختر لغة المحتوى",
      highlightHelp: "* يتم تمييز الحرف الموجود في الفهرس المحدد في الوقت الفعلي داخل منطقة النص أعلاه.",
      allTools: "جميع الأدوات",
      footerNote1: "هذه الأداة هي جزء من مجموعة أدوات apps24.",
      footerNote2: "تتم جميع عمليات المعالجة محليًا في متصفحك لضمان أقصى قدر من الخصوصية والسرعة.",
      koLabel: "الكورية",
      enLabel: "الإنجليزية",
      textCategory: "نص",
      utilityCategory: "أداة",
      positionPlaceholder: "الموقع",
      twelveHour: "12H",
      twentyFourHour: "24H",
      fontSize: "الحجم",
      customColor: "لون",
      presetColors: "الإعدادات المسبقة",
      homeTitle: "أدوات سريعة متعددة اللغات",
      homeSubtitle: "أدوات مساعدة بسيطة للمهام السريعة، معربة بالكامل للغتك.",
      rulerHowTo: "كيفية استخدام المسطرة عبر الإنترنت",
      rulerStep1: "ضع بطاقة ائتمان أفقيًا عند علامة الصفر.",
      rulerStep2: "أدخل العرض المقاس للبطاقة وانقر على 'معايرة'.",
      rulerStep3: "الآن يمكنك قياس الشيء المطلوب.",
      rulerEnterCardWidth: "أدخل عرض بطاقة الائتمان",
      rulerExample: "مثال: إذا كان العرض 10.4 سم، أدخل 10.4",
      rulerTip: "نصيحة: استخدم المقبض الأزرق في الزاوية اليمنى السفلية من اللوحة لتغيير حجمها.",
      calibrate: "معايرة",
      changeTo: "تغيير إلى",
      exitFullscreen: "خروج من ملء الشاشة",
      fullscreen: "ملء الشاشة",
      frLabel: "الفرنسية",
      jaLabel: "اليابانية",
      zhLabel: "الصينية (المبسطة)",
      zhTWLabel: "الصينية (التقليدية)",
      ptLabel: "البرتغالية",
      esLabel: "الإسبانية",
      deLabel: "الألمانية",
      arLabel: "العربية",
      about: "About Us",
      privacy: "Privacy Policy",
      terms: "Terms",
      contact: "Contact",
      seoTitle: "Professional Guide",
      aboutPrefix: "This free online tool...",
      imageCategory: "Image",
      securityCategory: "Security",
      timeCategory: "Time",
      displayCategory: "Display",
      measurementCategory: "Measurement",
      generatorCategory: "Generator",
      uploadImage: "Upload",
      compress: "Compress",
      convertToWebP: "Convert WebP",
      download: "Download",
      reset: "Reset",
      original: "Original",
      compressed: "Compressed",
      size: "Size",
      format: "Format JSON",
      validate: "Validate",
      generatePassword: "Generate Password",
      length: "Length",
      includeUppercase: "Uppercase",
      includeLowercase: "Lowercase",
      includeNumbers: "Numbers",
      includeSymbols: "Symbols",
      compare: "Compare",
    },
  },
};

export function getToolText(locale: Locale, tool: ToolDefinition): ToolText {
  return (
    TOOL_TEXTS[locale]?.tools[tool.id] ??
    TOOL_TEXTS.en?.tools[tool.id] ?? {
      title: tool.titleKey,
      description: tool.descriptionKey,
    }
  );
}

export function getCommonText(locale: Locale): CommonText {
  return TOOL_TEXTS[locale]?.common ?? TOOL_TEXTS.en.common;
}
