import type { ToolDefinition } from "@/features/tools/types";
import type { Locale } from "@/lib/site";
import type { LocaleData, ToolText, CommonText } from "./types_locales";

export type { ToolText, CommonText };

const dictionaries: Record<Locale, () => Promise<{ default: LocaleData }>> = {
  en: () => import("./locales/en"),
  ko: () => import("./locales/ko"),
  fr: () => import("./locales/fr"),
  ja: () => import("./locales/ja"),
  zh: () => import("./locales/zh"),
  "zh-TW": () => import("./locales/zh-TW"),
  pt: () => import("./locales/pt"),
  es: () => import("./locales/es"),
  de: () => import("./locales/de"),
  ar: () => import("./locales/ar"),
};

const COMMON_OVERRIDES: Partial<Record<Locale, Partial<CommonText>>> = {
  en: {
    networkCategory: "Network",
  },
  ar: {
    about: "حول",
    privacy: "الخصوصية",
    terms: "الشروط",
    contact: "تواصل",
    seoTitle: "دليل احترافي",
    aboutPrefix: "هذه الأداة المجانية عبر الإنترنت محسّنة لـ",
    imageCategory: "صورة",
    securityCategory: "أمان",
    timeCategory: "الوقت",
    displayCategory: "العرض",
    measurementCategory: "القياس",
    generatorCategory: "مولّد",
    networkCategory: "الشبكة",
    uploadImage: "رفع",
    compress: "ضغط",
    convertToWebP: "تحويل إلى WebP",
    download: "تنزيل",
    reset: "إعادة الضبط",
    original: "الأصل",
    compressed: "مضغوط",
    size: "الحجم",
    format: "تنسيق",
    validate: "تحقق",
    generatePassword: "توليد كلمة مرور",
    length: "الطول",
    includeUppercase: "تضمين أحرف كبيرة",
    includeLowercase: "تضمين أحرف صغيرة",
    includeNumbers: "تضمين أرقام",
    includeSymbols: "تضمين رموز",
    compare: "مقارنة",
    whatIs: "ما هو {0}؟",
    whenToUse: "متى تستخدم هذه الأداة؟",
    howToUseTitle: "كيفية استخدام {0}",
    faqTitle: "الأسئلة الشائعة",
    howItWorks: "كيف يعمل",
    whyUseTitle: "لماذا تستخدم {0}؟",
    popularConversionsTitle: "التحويلات الشائعة",
    relatedToolsTitle: "الأدوات ذات الصلة",
    unitLength: "الطول",
    unitWeight: "الوزن",
    unitArea: "المساحة",
    unitVolume: "الحجم",
    unitTemperature: "درجة الحرارة",
    unitSpeed: "السرعة",
    unitDigital: "رقمي",
    from: "من",
    to: "إلى",
    unitAccuracyNote: "* تحويل عالي الدقة.",
    quality: "الجودة",
    dimensions: "الأبعاد",
    width: "العرض",
    height: "الارتفاع",
    enterQrText: "نص أو رابط QR",
    enterBarcodeText: "أدخل بيانات الباركود",
    type: "النوع",
    copy: "نسخ",
  },
  de: {
    about: "Über uns",
    privacy: "Datenschutz",
    terms: "Nutzungsbedingungen",
    contact: "Kontakt",
    seoTitle: "Professioneller Leitfaden",
    aboutPrefix: "Dieses kostenlose Online-Tool ist optimiert für",
    imageCategory: "Bild",
    securityCategory: "Sicherheit",
    timeCategory: "Zeit",
    displayCategory: "Anzeige",
    measurementCategory: "Messung",
    generatorCategory: "Generator",
    networkCategory: "Netzwerk",
    uploadImage: "Hochladen",
    compress: "Komprimieren",
    convertToWebP: "In WebP umwandeln",
    download: "Herunterladen",
    reset: "Zurücksetzen",
    original: "Original",
    compressed: "Komprimiert",
    size: "Größe",
    format: "Format",
    validate: "Validieren",
    generatePassword: "Passwort generieren",
    length: "Länge",
    includeUppercase: "Großbuchstaben",
    includeLowercase: "Kleinbuchstaben",
    includeNumbers: "Zahlen",
    includeSymbols: "Symbole",
    compare: "Vergleichen",
    whatIs: "Was ist {0}?",
    whenToUse: "Wann sollte man dieses Tool verwenden?",
    howToUseTitle: "So verwenden Sie {0}",
    faqTitle: "Häufig gestellte Fragen",
    howItWorks: "So funktioniert es",
    whyUseTitle: "Warum {0} verwenden?",
    popularConversionsTitle: "Beliebte Umrechnungen",
    relatedToolsTitle: "Verwandte Tools",
    unitLength: "Länge",
    unitWeight: "Gewicht",
    unitArea: "Fläche",
    unitVolume: "Volumen",
    unitTemperature: "Temperatur",
    unitSpeed: "Geschwindigkeit",
    unitDigital: "Digital",
    from: "Von",
    to: "Nach",
    unitAccuracyNote: "* Hochpräzise Umrechnung.",
    quality: "Qualität",
    dimensions: "Größe",
    width: "Breite",
    height: "Höhe",
    enterQrText: "QR-Text oder URL",
    enterBarcodeText: "Barcode-Daten eingeben",
    type: "Typ",
    copy: "Kopieren",
  },
  ko: {
    networkCategory: "네트워크",
  },
  es: {
    about: "Acerca de",
    privacy: "Privacidad",
    terms: "Términos",
    contact: "Contacto",
    seoTitle: "Guía profesional",
    aboutPrefix: "Esta herramienta en línea gratuita está optimizada para",
    imageCategory: "Imagen",
    securityCategory: "Seguridad",
    timeCategory: "Tiempo",
    displayCategory: "Pantalla",
    measurementCategory: "Medición",
    generatorCategory: "Generador",
    networkCategory: "Red",
    uploadImage: "Subir",
    compress: "Comprimir",
    convertToWebP: "Convertir a WebP",
    download: "Descargar",
    reset: "Restablecer",
    original: "Original",
    compressed: "Comprimido",
    size: "Tamaño",
    format: "Formato",
    validate: "Validar",
    generatePassword: "Generar contraseña",
    length: "Longitud",
    includeUppercase: "Incluir mayúsculas",
    includeLowercase: "Incluir minúsculas",
    includeNumbers: "Incluir números",
    includeSymbols: "Incluir símbolos",
    compare: "Comparar",
    whatIs: "¿Qué es {0}?",
    whenToUse: "¿Cuándo usar esta herramienta?",
    howToUseTitle: "Cómo usar {0}",
    faqTitle: "Preguntas frecuentes",
    howItWorks: "Cómo funciona",
    whyUseTitle: "¿Por qué usar {0}?",
    popularConversionsTitle: "Conversiones populares",
    relatedToolsTitle: "Herramientas relacionadas",
    unitLength: "Longitud",
    unitWeight: "Peso",
    unitArea: "Área",
    unitVolume: "Volumen",
    unitTemperature: "Temperatura",
    unitSpeed: "Velocidad",
    unitDigital: "Digital",
    from: "Desde",
    to: "Hasta",
    unitAccuracyNote: "* Conversión de alta precisión.",
    quality: "Calidad",
    dimensions: "Dimensiones",
    width: "Ancho",
    height: "Alto",
    enterQrText: "Texto o URL del QR",
    enterBarcodeText: "Ingrese datos del código de barras",
    type: "Tipo",
    copy: "Copiar",
  },
  fr: {
    about: "À propos",
    privacy: "Confidentialité",
    terms: "Conditions",
    contact: "Contact",
    seoTitle: "Guide professionnel",
    aboutPrefix: "Cet outil en ligne gratuit est optimisé pour",
    imageCategory: "Image",
    securityCategory: "Sécurité",
    timeCategory: "Temps",
    displayCategory: "Affichage",
    measurementCategory: "Mesure",
    generatorCategory: "Générateur",
    networkCategory: "Réseau",
    uploadImage: "Importer",
    compress: "Compresser",
    convertToWebP: "Convertir en WebP",
    download: "Télécharger",
    reset: "Réinitialiser",
    original: "Original",
    compressed: "Compressé",
    size: "Taille",
    format: "Format",
    validate: "Valider",
    generatePassword: "Générer un mot de passe",
    length: "Longueur",
    includeUppercase: "Majuscules",
    includeLowercase: "Minuscules",
    includeNumbers: "Nombres",
    includeSymbols: "Symboles",
    compare: "Comparer",
    whatIs: "Qu'est-ce que {0} ?",
    whenToUse: "Quand utiliser cet outil ?",
    howToUseTitle: "Comment utiliser {0}",
    faqTitle: "Questions fréquentes",
    howItWorks: "Comment ça marche",
    whyUseTitle: "Pourquoi utiliser {0} ?",
    popularConversionsTitle: "Conversions populaires",
    relatedToolsTitle: "Outils connexes",
    unitLength: "Longueur",
    unitWeight: "Poids",
    unitArea: "Surface",
    unitVolume: "Volume",
    unitTemperature: "Température",
    unitSpeed: "Vitesse",
    unitDigital: "Numérique",
    from: "De",
    to: "À",
    unitAccuracyNote: "* Conversion de haute précision.",
    quality: "Qualité",
    dimensions: "Dimensions",
    width: "Largeur",
    height: "Hauteur",
    enterQrText: "Texte ou URL QR",
    enterBarcodeText: "Saisir les données du code-barres",
    type: "Type",
    copy: "Copier",
  },
  ja: {
    about: "概要",
    privacy: "プライバシー",
    terms: "利用規約",
    contact: "お問い合わせ",
    seoTitle: "プロ向けガイド",
    aboutPrefix: "この無料オンラインツールは",
    imageCategory: "画像",
    securityCategory: "セキュリティ",
    timeCategory: "時間",
    displayCategory: "表示",
    measurementCategory: "測定",
    generatorCategory: "生成",
    networkCategory: "ネットワーク",
    uploadImage: "アップロード",
    compress: "圧縮",
    convertToWebP: "WebPに変換",
    download: "ダウンロード",
    reset: "リセット",
    original: "元の画像",
    compressed: "圧縮後",
    size: "サイズ",
    format: "形式",
    validate: "検証",
    generatePassword: "パスワード生成",
    length: "長さ",
    includeUppercase: "大文字",
    includeLowercase: "小文字",
    includeNumbers: "数字",
    includeSymbols: "記号",
    compare: "比較",
    whatIs: "{0}とは？",
    whenToUse: "このツールはいつ使いますか？",
    howToUseTitle: "{0}の使い方",
    faqTitle: "よくある質問",
    howItWorks: "使い方",
    whyUseTitle: "{0}を使う理由は？",
    popularConversionsTitle: "人気の変換",
    relatedToolsTitle: "関連ツール",
    unitLength: "長さ",
    unitWeight: "重さ",
    unitArea: "面積",
    unitVolume: "容量",
    unitTemperature: "温度",
    unitSpeed: "速度",
    unitDigital: "デジタル",
    from: "変換元",
    to: "変換先",
    unitAccuracyNote: "* 高精度の変換結果です。",
    quality: "品質",
    dimensions: "サイズ変更",
    width: "幅",
    height: "高さ",
    enterQrText: "QRコードのテキストまたはURL",
    enterBarcodeText: "バーコードデータを入力",
    type: "種類",
    copy: "コピー",
  },
  pt: {
    about: "Sobre",
    privacy: "Privacidade",
    terms: "Termos",
    contact: "Contato",
    seoTitle: "Guia profissional",
    aboutPrefix: "Esta ferramenta online gratuita é otimizada para",
    imageCategory: "Imagem",
    securityCategory: "Segurança",
    timeCategory: "Tempo",
    displayCategory: "Exibição",
    measurementCategory: "Medição",
    generatorCategory: "Gerador",
    networkCategory: "Rede",
    uploadImage: "Enviar",
    compress: "Compactar",
    convertToWebP: "Converter para WebP",
    download: "Baixar",
    reset: "Redefinir",
    original: "Original",
    compressed: "Comprimido",
    size: "Tamanho",
    format: "Formato",
    validate: "Validar",
    generatePassword: "Gerar senha",
    length: "Comprimento",
    includeUppercase: "Incluir maiúsculas",
    includeLowercase: "Incluir minúsculas",
    includeNumbers: "Incluir números",
    includeSymbols: "Incluir símbolos",
    compare: "Comparar",
    whatIs: "O que é {0}?",
    whenToUse: "Quando usar esta ferramenta?",
    howToUseTitle: "Como usar {0}",
    faqTitle: "Perguntas frequentes",
    howItWorks: "Como funciona",
    whyUseTitle: "Por que usar {0}?",
    popularConversionsTitle: "Conversões populares",
    relatedToolsTitle: "Ferramentas relacionadas",
    unitLength: "Comprimento",
    unitWeight: "Peso",
    unitArea: "Área",
    unitVolume: "Volume",
    unitTemperature: "Temperatura",
    unitSpeed: "Velocidade",
    unitDigital: "Digital",
    from: "De",
    to: "Para",
    unitAccuracyNote: "* Conversão de alta precisão.",
    quality: "Qualidade",
    dimensions: "Dimensões",
    width: "Largura",
    height: "Altura",
    enterQrText: "Texto ou URL do QR",
    enterBarcodeText: "Insira os dados do código de barras",
    type: "Tipo",
    copy: "Copiar",
  },
  zh: {
    about: "关于我们",
    privacy: "隐私政策",
    terms: "条款",
    contact: "联系我们",
    seoTitle: "专业指南",
    aboutPrefix: "这款免费的在线工具经过优化，适用于",
    imageCategory: "图片",
    securityCategory: "安全",
    timeCategory: "时间",
    displayCategory: "显示",
    measurementCategory: "测量",
    generatorCategory: "生成器",
    networkCategory: "网络",
    uploadImage: "上传",
    compress: "压缩",
    convertToWebP: "转换为 WebP",
    download: "下载",
    reset: "重置",
    original: "原图",
    compressed: "压缩后",
    size: "大小",
    format: "格式",
    validate: "验证",
    generatePassword: "生成密码",
    length: "长度",
    includeUppercase: "包含大写字母",
    includeLowercase: "包含小写字母",
    includeNumbers: "包含数字",
    includeSymbols: "包含符号",
    compare: "比较",
    whatIs: "{0} 是什么？",
    whenToUse: "什么时候使用此工具？",
    howToUseTitle: "如何使用 {0}",
    faqTitle: "常见问题",
    howItWorks: "工作原理",
    whyUseTitle: "为什么要使用 {0}？",
    popularConversionsTitle: "热门转换",
    relatedToolsTitle: "相关工具",
    unitLength: "长度",
    unitWeight: "重量",
    unitArea: "面积",
    unitVolume: "体积",
    unitTemperature: "温度",
    unitSpeed: "速度",
    unitDigital: "数字存储",
    from: "从",
    to: "到",
    unitAccuracyNote: "* 高精度转换。",
    quality: "质量",
    dimensions: "尺寸",
    width: "宽度",
    height: "高度",
    enterQrText: "二维码文本或网址",
    enterBarcodeText: "输入条形码数据",
    type: "类型",
    copy: "复制",
  },
  "zh-TW": {
    about: "關於我們",
    privacy: "隱私政策",
    terms: "條款",
    contact: "聯絡我們",
    seoTitle: "專業指南",
    aboutPrefix: "這個免費線上工具經過最佳化，適用於",
    imageCategory: "圖片",
    securityCategory: "安全",
    timeCategory: "時間",
    displayCategory: "顯示",
    measurementCategory: "測量",
    generatorCategory: "產生器",
    networkCategory: "網路",
    uploadImage: "上傳",
    compress: "壓縮",
    convertToWebP: "轉換為 WebP",
    download: "下載",
    reset: "重設",
    original: "原始",
    compressed: "壓縮後",
    size: "大小",
    format: "格式",
    validate: "驗證",
    generatePassword: "產生密碼",
    length: "長度",
    includeUppercase: "包含大寫字母",
    includeLowercase: "包含小寫字母",
    includeNumbers: "包含數字",
    includeSymbols: "包含符號",
    compare: "比較",
    whatIs: "{0} 是什麼？",
    whenToUse: "什麼時候使用此工具？",
    howToUseTitle: "如何使用 {0}",
    faqTitle: "常見問題",
    howItWorks: "運作原理",
    whyUseTitle: "為什麼要使用 {0}？",
    popularConversionsTitle: "熱門轉換",
    relatedToolsTitle: "相關工具",
    unitLength: "長度",
    unitWeight: "重量",
    unitArea: "面積",
    unitVolume: "體積",
    unitTemperature: "溫度",
    unitSpeed: "速度",
    unitDigital: "數位儲存",
    from: "從",
    to: "到",
    unitAccuracyNote: "* 高精度轉換。",
    quality: "品質",
    dimensions: "尺寸",
    width: "寬度",
    height: "高度",
    enterQrText: "QR Code 文字或網址",
    enterBarcodeText: "輸入條碼資料",
    type: "類型",
    copy: "複製",
  },
};

export async function getDictionary(locale: Locale) {
  const load = dictionaries[locale] || dictionaries.en;
  return (await load()).default;
}

export async function getToolText(locale: Locale, tool: ToolDefinition): Promise<ToolText> {
  const dict = await getDictionary(locale);
  const enDict = locale === "en" ? dict : await getDictionary("en");
  const base = (
    dict.tools[tool.id] ??
    enDict.tools[tool.id] ?? {
      title: tool.titleKey,
      description: tool.descriptionKey,
    }
  );

  return base;
}

export async function getCommonText(locale: Locale): Promise<CommonText> {
  const dict = await getDictionary(locale);
  const enDict = locale === "en" ? dict : await getDictionary("en");
  return {
    ...enDict.common,
    ...dict.common,
    ...(COMMON_OVERRIDES[locale] ?? {}),
  };
}
