import type { Locale } from "@/lib/site";
type DetailCopy = { modified: string; precision: string; formula: string; rounding: string; base64: string; utf8: string; privacy: string };
export const DETAIL_COPY: Record<Locale, DetailCopy> = {
  en: { modified: "Modified text", precision: "Decimal places", formula: "Conversion formula", rounding: "Results are rounded to the selected number of decimal places. Months and years use fixed durations, not calendar dates.", base64: "Invalid standard Base64 input.", utf8: "The decoded bytes are not valid UTF-8 text. Binary files are not supported.", privacy: "QR and barcode input is sent to the Apps24 server in a POST request to generate an image; it is not added to the page URL. This generator does not save the input in an application database. Hosting infrastructure may process operational request logs. Do not enter confidential data. Signboard messages and settings remain in this browser's localStorage until you clear the site's browser data." },
  ko: { modified: "수정문", precision: "소수 자릿수", formula: "변환 수식", rounding: "결과는 선택한 소수 자릿수로 반올림합니다. 월·년은 고정 기간이며 달력상의 날짜 계산이 아닙니다.", base64: "표준 Base64 입력 형식이 올바르지 않습니다.", utf8: "디코딩한 바이트가 유효한 UTF-8 텍스트가 아닙니다. 이진 파일은 지원하지 않습니다.", privacy: "QR·바코드 입력은 이미지 생성을 위해 POST 요청으로 Apps24 서버에 전송되며 페이지 URL에는 넣지 않습니다. 생성기는 입력을 애플리케이션 데이터베이스에 저장하지 않습니다. 호스팅 인프라는 운영 요청 로그를 처리할 수 있으므로 비밀정보를 입력하지 마세요. 전광판 문구와 설정은 이 브라우저의 localStorage에 남으며, 브라우저에서 이 사이트 데이터를 삭제하면 지울 수 있습니다." },
  fr: { modified: "Texte modifié", precision: "Décimales", formula: "Formule de conversion", rounding: "Le résultat est arrondi aux décimales choisies. Mois et années sont des durées fixes, pas des dates calendaires.", base64: "Format Base64 standard non valide.", utf8: "Les octets décodés ne sont pas du texte UTF-8 valide. Les fichiers binaires ne sont pas pris en charge.", privacy: "Les entrées QR et codes-barres sont envoyées au serveur Apps24 par POST pour créer une image, sans être ajoutées à l’URL. Le générateur ne les enregistre pas dans une base de données applicative. L’hébergement peut traiter des journaux opérationnels. N’entrez pas de données confidentielles. Messages et réglages du panneau restent dans le localStorage du navigateur jusqu’à la suppression des données du site." },
  de: { modified: "Geänderter Text", precision: "Dezimalstellen", formula: "Umrechnungsformel", rounding: "Ergebnisse werden auf die gewählten Dezimalstellen gerundet. Monate und Jahre sind feste Dauern, keine Kalenderdaten.", base64: "Ungültige Standard-Base64-Eingabe.", utf8: "Die dekodierten Bytes sind kein gültiger UTF-8-Text. Binärdateien werden nicht unterstützt.", privacy: "QR- und Barcode-Eingaben werden per POST an den Apps24-Server geschickt, um ein Bild zu erzeugen, nicht in der URL. Der Generator speichert sie nicht in einer Anwendungsdatenbank. Die Hosting-Infrastruktur kann Betriebsprotokolle verarbeiten. Keine vertraulichen Daten eingeben. Laufschrifttexte und Einstellungen bleiben im localStorage, bis Sie die Browserdaten dieser Website löschen." },
  es: { modified: "Texto modificado", precision: "Decimales", formula: "Fórmula de conversión", rounding: "Los resultados se redondean a los decimales elegidos. Meses y años son duraciones fijas, no fechas de calendario.", base64: "Formato Base64 estándar no válido.", utf8: "Los bytes decodificados no son texto UTF-8 válido. No se admiten archivos binarios.", privacy: "Las entradas QR y códigos de barras se envían al servidor Apps24 por POST para generar una imagen, sin añadirse a la URL. El generador no las guarda en una base de datos de aplicación. El alojamiento puede procesar registros operativos. No introduzca datos confidenciales. Los mensajes y ajustes del letrero quedan en localStorage hasta borrar los datos del sitio en el navegador." },
  pt: { modified: "Texto alterado", precision: "Casas decimais", formula: "Fórmula de conversão", rounding: "Os resultados são arredondados às casas escolhidas. Meses e anos são durações fixas, não datas de calendário.", base64: "Formato Base64 padrão inválido.", utf8: "Os bytes decodificados não são texto UTF-8 válido. Arquivos binários não são suportados.", privacy: "Entradas de QR e códigos de barras são enviadas ao servidor Apps24 por POST para gerar uma imagem, sem inclusão na URL. O gerador não as salva em banco de dados da aplicação. A hospedagem pode processar logs operacionais. Não insira dados confidenciais. Mensagens e ajustes do letreiro ficam no localStorage até limpar os dados deste site no navegador." },
  ja: { modified: "変更後のテキスト", precision: "小数桁数", formula: "変換式", rounding: "選択した小数桁数に丸めます。月と年は固定期間であり、暦の日付計算ではありません。", base64: "標準Base64の入力形式が正しくありません。", utf8: "デコードしたバイトは有効なUTF-8テキストではありません。バイナリファイルは非対応です。", privacy: "QRとバーコードの入力は画像生成のためPOSTでApps24サーバーへ送信され、ページURLには含めません。生成機能は入力をアプリケーションのデータベースに保存しません。ホスティング側は運用ログを処理する場合があります。秘密情報は入力しないでください。電光掲示板の文面と設定はブラウザのlocalStorageに残り、サイトデータの削除で消せます。" },
  zh: { modified: "修改后的文本", precision: "小数位数", formula: "换算公式", rounding: "结果按所选小数位数舍入。月和年是固定时长，不是日历日期计算。", base64: "标准Base64输入格式无效。", utf8: "解码字节不是有效UTF-8文本。不支持二进制文件。", privacy: "二维码和条形码输入通过POST发送至Apps24服务器生成图片，不加入页面网址。生成器不将输入存入应用数据库。托管基础设施可能处理运行请求日志，请勿输入机密信息。电子看板的文本和设置保留在浏览器localStorage中，可通过清除此站点浏览器数据删除。" },
  "zh-TW": { modified: "修改後的文字", precision: "小數位數", formula: "換算公式", rounding: "結果依所選小數位數捨入。月與年為固定時長，不是日曆日期計算。", base64: "標準Base64輸入格式無效。", utf8: "解碼位元組不是有效UTF-8文字。不支援二進位檔案。", privacy: "QR Code與條碼輸入透過POST傳送至Apps24伺服器產生圖片，不加入頁面網址。產生器不將輸入存入應用資料庫。託管基礎設施可能處理運作請求紀錄，請勿輸入機密資訊。電子看板文字與設定保留在瀏覽器localStorage中，可透過清除此網站的瀏覽器資料刪除。" },
  ar: { modified: "النص المعدّل", precision: "المنازل العشرية", formula: "صيغة التحويل", rounding: "تُقرّب النتائج للمنازل المختارة. الأشهر والسنوات مدد ثابتة وليست حسابات تقويمية.", base64: "صيغة Base64 القياسية غير صالحة.", utf8: "البايتات المفكوكة ليست نص UTF-8 صالحًا. الملفات الثنائية غير مدعومة.", privacy: "تُرسل مدخلات QR والباركود إلى خادم Apps24 بطلب POST لإنشاء صورة ولا تُضاف إلى رابط الصفحة. لا يحفظ المولد المدخلات في قاعدة بيانات التطبيق. قد تعالج الاستضافة سجلات الطلبات التشغيلية. لا تدخل معلومات سرية. تبقى رسائل اللوحة وإعداداتها في localStorage حتى تمسح بيانات الموقع من المتصفح." },
};
