import type { Locale } from "@/lib/site";
import type { ToolText } from "./types_locales";

const content = {
  countdown: {
    examples: ["00:01:30 = 90 s", "99:59:59"],
    note: {
      en: "Set hours (0–99), minutes and seconds (0–59), then start. Pause keeps the remaining duration; reset restores the entered duration. The timer uses the device clock and does not continue across a page reload. Sleeping devices and background-tab restrictions can delay the display or completion sound; this is not a safety-critical alarm. Duration and night-mode settings are saved on this browser.",
      ko: "시간은 0~99, 분·초는 0~59로 설정한 뒤 시작합니다. 일시정지는 남은 시간을 유지하고 초기화는 입력한 시간으로 되돌립니다. 기기 시계를 기준으로 계산하며 새로고침하면 실행 상태가 유지되지 않습니다. 기기 절전과 백그라운드 탭 제한으로 표시·완료음이 늦어질 수 있어 중요한 안전 알람으로 사용하지 마세요. 시간과 야간 모드 설정은 이 브라우저에 저장됩니다.",
      fr: "Réglez 0–99 heures et 0–59 minutes/secondes. Pause garde le temps restant ; réinitialiser reprend la durée saisie. Le minuteur dépend de l’horloge de l’appareil et ne survit pas au rechargement. Veille et onglets en arrière-plan peuvent retarder affichage et son : pas une alarme de sécurité. Durée et mode nuit sont mémorisés dans ce navigateur.",
      de: "0–99 Stunden und 0–59 Minuten/Sekunden einstellen. Pause erhält die Restzeit; Zurücksetzen stellt die Eingabedauer wieder her. Geräteuhr-basiert, läuft nach Neuladen nicht weiter. Ruhezustand und Hintergrund-Tabs können Anzeige und Ton verzögern: kein Sicherheitsalarm. Dauer und Nachtmodus werden im Browser gespeichert.",
      es: "Ajuste 0–99 horas y 0–59 minutos/segundos. Pausa conserva el tiempo restante; reiniciar vuelve a la duración indicada. Usa el reloj del dispositivo y no continúa tras recargar. El reposo y las pestañas de fondo pueden retrasar pantalla y sonido: no es una alarma de seguridad. Duración y modo nocturno se guardan en este navegador.",
      pt: "Defina 0–99 horas e 0–59 minutos/segundos. Pausar mantém o restante; redefinir restaura a duração informada. Usa o relógio do dispositivo e não continua após recarregar. Suspensão e abas em segundo plano podem atrasar exibição e som: não é alarme de segurança. Duração e modo noturno ficam neste navegador.",
      ja: "時間は0〜99、分・秒は0〜59です。一時停止は残り時間を保持し、リセットは入力した長さに戻します。端末時計を使い、再読み込み後は継続しません。スリープや背景タブの制限で表示・終了音が遅れるため、安全上重要なアラームには使わないでください。時間と夜間設定はブラウザに保存します。",
      zh: "设置0–99小时及0–59分钟、秒。暂停保留剩余时间，重置恢复输入时长。计时基于设备时钟，刷新后不会继续。设备休眠和后台标签限制可能延迟显示及声音，不适合作为安全警报。时长及夜间模式保存在此浏览器。",
      "zh-TW": "設定0–99小時及0–59分鐘、秒。暫停保留剩餘時間，重設恢復輸入時長。計時依據裝置時鐘，重新載入後不會繼續。休眠和背景分頁限制可能延遲顯示及聲音，不適合作為安全警報。時長與夜間模式保存在此瀏覽器。",
      ar: "اضبط 0–99 ساعة و0–59 دقيقة وثانية. يحفظ الإيقاف المؤقت الوقت المتبقي وتعيد إعادة الضبط المدة المدخلة. يعتمد على ساعة الجهاز ولا يستمر بعد إعادة تحميل الصفحة. قد يؤخر السكون وقيود التبويبات الخلفية العرض والصوت؛ ليس إنذار سلامة. تُحفظ المدة والوضع الليلي في هذا المتصفح.",
    },
    reference: ["Browser timer restrictions", "https://developer.mozilla.org/en-US/docs/Web/API/Window/setTimeout"],
  },
  digitalclock: {
    examples: ["13:05:09 ↔ 01:05:09 PM", "24 h / 12 h"],
    note: {
      en: "The clock displays your device’s current time in its local time zone, with date and 12/24-hour options. It does not query an atomic clock or synchronize your system clock. If the time is wrong, check the device date, time zone and automatic-time setting. Display updates can slow in background tabs. Color, format and size settings remain in this browser.",
      ko: "기기의 현재 시각과 시간대를 사용해 날짜와 12·24시간 표시를 제공합니다. 원자시계 조회나 시스템 시각 동기화 기능은 없습니다. 시각이 다르면 기기의 날짜·시간대·자동 시간 설정을 확인하세요. 백그라운드 탭에서는 화면 갱신이 늦어질 수 있습니다. 색상·표시 형식·크기 설정은 이 브라우저에 남습니다.",
      fr: "Affiche l’heure et le fuseau de votre appareil, avec date et format 12/24 heures. Ne consulte pas d’horloge atomique et ne synchronise pas le système. Vérifiez date, fuseau et réglage automatique en cas d’écart. Les onglets de fond peuvent ralentir l’affichage. Couleur, format et taille restent dans ce navigateur.",
      de: "Zeigt Gerätezeit und lokale Zeitzone mit Datum und 12/24-Stunden-Format. Keine Atomuhr-Abfrage oder Synchronisierung. Bei Abweichungen Datum, Zeitzone und automatische Zeit prüfen. Hintergrund-Tabs können seltener aktualisieren. Farbe, Format und Größe bleiben im Browser.",
      es: "Muestra la hora y zona del dispositivo, con fecha y formato de 12/24 horas. No consulta un reloj atómico ni sincroniza el sistema. Si hay diferencias, revise fecha, zona y hora automática. El fondo puede retrasar actualizaciones. Color, formato y tamaño quedan en este navegador.",
      pt: "Mostra a hora e o fuso do dispositivo, com data e formato de 12/24 horas. Não consulta relógio atômico nem sincroniza o sistema. Confira data, fuso e hora automática se houver diferença. Abas de fundo podem atualizar mais devagar. Cor, formato e tamanho ficam neste navegador.",
      ja: "端末の時刻と現地時間帯を使い、日付と12・24時間表示を提供します。原子時計の照会や時刻同期はしません。ずれている場合は端末の日付・時間帯・自動時刻設定を確認してください。背景タブで更新が遅れることがあります。色・形式・サイズはブラウザに保存します。",
      zh: "显示设备时间和本地时区，支持日期及12/24小时格式。不查询原子钟，也不同步系统。时间不对时请检查设备日期、时区和自动时间。后台标签可能降低更新频率。颜色、格式和大小保存在此浏览器。",
      "zh-TW": "顯示裝置時間與本地時區，支援日期及12/24小時格式。不查詢原子鐘，也不同步系統。時間不對時請檢查裝置日期、時區與自動時間。背景分頁可能降低更新頻率。色彩、格式與大小保存在此瀏覽器。",
      ar: "يعرض وقت الجهاز ومنطقته الزمنية مع التاريخ وصيغة 12/24 ساعة. لا يستعلم ساعة ذرية ولا يزامن النظام. عند اختلاف الوقت راجع تاريخ الجهاز والمنطقة وإعداد الوقت التلقائي. قد تتباطأ تحديثات التبويبات الخلفية. تُحفظ الألوان والصيغة والحجم في هذا المتصفح.",
    },
    reference: ["JavaScript device time", "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date"],
  },
  screenlamp: {
    examples: ["#ffffff", "#000000"],
    note: {
      en: "Choose a solid background color and optionally enter full screen. This changes webpage pixels, not the monitor’s hardware brightness. A white screen can provide a simple visual background, but is not a calibrated light source, colorimeter or eye-health tool. Appearance depends on your display settings. Avoid uncomfortable brightness; the chosen color is stored in this browser.",
      ko: "단색 배경을 선택하고 필요하면 전체 화면으로 표시합니다. 웹페이지의 픽셀 색만 바꾸며 모니터 자체 밝기를 조절하지 않습니다. 흰 화면을 간단한 배경으로 쓸 수 있지만 보정된 조명·색도계·눈 건강 도구가 아닙니다. 실제 보이는 색과 밝기는 기기 설정에 따라 다릅니다. 불편한 밝기는 피하고, 선택한 색상은 이 브라우저에 저장됩니다.",
      fr: "Choisissez une couleur unie, éventuellement en plein écran. Seuls les pixels de la page changent, pas la luminosité matérielle. Un fond blanc n’est ni une lumière étalonnée, ni un colorimètre, ni un outil de santé visuelle. Le rendu dépend de l’écran. Évitez une luminosité inconfortable ; la couleur est mémorisée ici.",
      de: "Volltonfarbe wählen und optional Vollbild nutzen. Ändert Webseitenpixel, nicht die Hardware-Helligkeit. Weißer Hintergrund ist keine kalibrierte Lichtquelle, kein Farbmessgerät und kein Augengesundheits-Tool. Die Darstellung hängt vom Display ab. Unangenehme Helligkeit meiden; Farbe wird im Browser gespeichert.",
      es: "Elija un fondo liso y, si desea, pantalla completa. Cambia los píxeles de la página, no el brillo físico del monitor. No es una luz calibrada, colorímetro ni herramienta de salud visual. El aspecto depende de la pantalla. Evite brillo incómodo; el color se guarda en este navegador.",
      pt: "Escolha uma cor sólida e, se quiser, tela cheia. Altera os pixels da página, não o brilho físico do monitor. Não é luz calibrada, colorímetro nem ferramenta de saúde ocular. A aparência depende da tela. Evite brilho desconfortável; a cor fica neste navegador.",
      ja: "単色背景を選び、必要に応じ全画面にします。ページの画素色を変えるだけで、機器の輝度は調整しません。白い画面は校正済み照明・色彩計・目の健康ツールではありません。表示は端末設定に依存します。不快な明るさを避けてください。色はブラウザに保存します。",
      zh: "选择纯色背景，可进入全屏。只改变网页像素，不调整显示器硬件亮度。白色背景不是校准光源、色度计或眼部健康工具。外观依赖设备设置，请避免不舒适的亮度。选定颜色保存在此浏览器。",
      "zh-TW": "選擇純色背景，可進入全螢幕。只改變網頁像素，不調整顯示器硬體亮度。白色背景不是校正光源、色度計或眼睛健康工具。外觀依賴裝置設定，請避免不舒適的亮度。選定色彩保存在此瀏覽器。",
      ar: "اختر خلفية موحدة مع عرض ملء الشاشة اختياريًا. تتغير بكسلات الصفحة لا سطوع الشاشة المادي. الخلفية البيضاء ليست مصدر ضوء معايرًا أو مقياس ألوان أو أداة لصحة العين. يعتمد المظهر على إعدادات الشاشة؛ تجنب السطوع المزعج. يُحفظ اللون في هذا المتصفح.",
    },
    reference: ["Browser full-screen display", "https://developer.mozilla.org/en-US/docs/Web/API/Fullscreen_API"],
  },
  signboard: {
    examples: ["OPEN", "←"],
    note: {
      en: "Enter a message, choose text/background colors and use static, scrolling, blinking or glowing display. Full screen may use a page-sized fallback on some devices. The message itself and settings are saved in localStorage: shared-device users should remove the message or clear this site’s browser data afterward. This does not control external LED hardware or certify public signage. Prefer static text when motion or flashing is uncomfortable.",
      ko: "문구·글자색·배경색을 설정하고 고정·스크롤·깜빡임·발광 효과를 선택합니다. 일부 기기에서는 브라우저 전체 화면 대신 페이지 전체 표시를 사용합니다. 설정뿐 아니라 문구 자체가 localStorage에 남으므로 공용 기기에서는 사용 후 문구를 지우거나 이 사이트의 브라우저 데이터를 삭제하세요. 외부 LED 장비 제어나 공공 표지 인증 기능은 없습니다. 움직임·깜빡임이 불편하면 고정 표시를 선택하세요.",
      fr: "Saisissez un message, réglez les couleurs et choisissez fixe, défilement, clignotement ou lueur. Certains appareils utilisent un plein écran de page. Message et réglages restent dans localStorage : effacez le message ou les données du site sur un appareil partagé. Aucun contrôle de panneau LED externe ni certification. Préférez le texte fixe si l’animation gêne.",
      de: "Nachricht und Farben einstellen, statisch, laufend, blinkend oder leuchtend anzeigen. Manche Geräte nutzen einen seitenfüllenden Ersatz. Nachricht und Einstellungen bleiben in localStorage; auf gemeinsam genutzten Geräten Nachricht oder Website-Daten löschen. Keine Steuerung externer LED-Geräte oder Beschilderungszertifizierung. Bei unangenehmer Bewegung statischen Text wählen.",
      es: "Escriba el mensaje y elija colores y efectos fijo, desplazamiento, parpadeo o brillo. Algunos dispositivos usan una vista que ocupa la página. Mensaje y ajustes quedan en localStorage: borre el mensaje o los datos del sitio en equipos compartidos. No controla LED externos ni certifica señalización. Prefiera texto fijo si la animación molesta.",
      pt: "Digite a mensagem, escolha cores e efeitos estático, rolagem, piscar ou brilho. Alguns dispositivos usam uma exibição que ocupa a página. Mensagem e ajustes ficam no localStorage; em aparelhos compartilhados, apague a mensagem ou os dados do site. Não controla LED externo nem certifica sinalização. Prefira texto estático se a animação incomodar.",
      ja: "文言と色を設定し、固定・スクロール・点滅・発光を選びます。一部端末ではページ内の全画面表示を使います。文言と設定はlocalStorageに残るため、共有端末では文言かサイトのブラウザデータを削除してください。外部LED制御や公共標識の認証機能はありません。動きや点滅が不快なら固定表示にします。",
      zh: "输入文案、设置文字和背景颜色，并选择静止、滚动、闪烁或发光。部分设备使用填满页面的替代全屏。文案和设置保存在localStorage，共用设备使用后请清空文案或删除本站浏览器数据。不控制外部LED，也不认证公共标识。动画不适时请选择静止。",
      "zh-TW": "輸入文字、設定文字與背景色，並選擇靜止、捲動、閃爍或發光。部分裝置使用填滿頁面的替代全螢幕。文字與設定保存在localStorage，共用裝置使用後請清空文字或刪除本站瀏覽器資料。不控制外部LED，也不認證公共標誌。動畫不適時請選擇靜止。",
      ar: "أدخل الرسالة واختر الألوان والعرض الثابت أو المتحرك أو الوامض أو المتوهج. تستخدم بعض الأجهزة عرضًا يملأ الصفحة بدل ملء الشاشة الأصلي. تُحفظ الرسالة والإعدادات في localStorage؛ احذف الرسالة أو بيانات الموقع بعد استعمال جهاز مشترك. لا يتحكم بلوحات LED خارجية ولا يعتمد لافتات عامة. اختر العرض الثابت إذا كانت الحركة مزعجة.",
    },
    reference: ["Browser localStorage", "https://developer.mozilla.org/en-US/docs/Web/API/Window/localStorage"],
  },
  dummytext: {
    examples: ["1 → 100", "4 / 5 / 6"],
    note: {
      en: "Generate 1–100 placeholder paragraphs for layout tests. Each paragraph combines 4, 5 or 6 sentences from a fixed set; output is deterministic, not unique generated writing. The page language and English are available (English only on the English page). Some language sets contain declaration or constitutional excerpts. These samples are not current legal advice or publication-ready articles. Paragraph count is saved in this browser.",
      ko: "레이아웃 시험용 문단을 1~100개 만듭니다. 고정 문장 모음에서 문단마다 4·5·6문장을 조합하므로 고유한 글을 자동 작성하는 기능이 아닙니다. 현재 페이지 언어와 영어를 선택하며 영어 페이지는 영어만 제공합니다. 일부 언어 문장은 선언문·헌법의 발췌·축약문으로, 현행 법률 안내나 게시용 글이 아닙니다. 문단 수 설정은 이 브라우저에 저장됩니다.",
      fr: "Crée 1–100 paragraphes pour tester une mise en page, avec 4, 5 ou 6 phrases d’un ensemble fixe. Résultat déterministe, pas une rédaction originale. Langue de la page et anglais disponibles, anglais seul sur la page anglaise. Certains textes reprennent des déclarations ou constitutions : pas un conseil juridique ni un article à publier. Nombre de paragraphes mémorisé ici.",
      de: "Erzeugt 1–100 Layout-Testabsätze mit 4, 5 oder 6 Sätzen aus einem festen Bestand. Deterministisch, keine originellen Artikel. Seitensprache und Englisch verfügbar, auf Englisch nur Englisch. Manche Bestände enthalten Erklärungs- oder Verfassungsauszüge; keine aktuelle Rechtsberatung oder Veröffentlichungstexte. Absatzanzahl bleibt im Browser.",
      es: "Genera 1–100 párrafos de prueba con 4, 5 o 6 frases de un conjunto fijo. Es determinista, no escritura original. Ofrece el idioma de la página e inglés; en la página inglesa solo inglés. Algunos textos incluyen declaraciones o constituciones: no son asesoría jurídica ni artículos listos para publicar. Guarda el número de párrafos en este navegador.",
      pt: "Gera 1–100 parágrafos de teste com 4, 5 ou 6 frases de um conjunto fixo. É determinístico, não redação original. Idioma da página e inglês disponíveis; página inglesa apenas inglês. Alguns textos contêm declarações ou constituições: não são orientação jurídica nem artigos prontos. A quantidade fica neste navegador.",
      ja: "レイアウト確認用に1〜100段落を作ります。固定文から4・5・6文を組み合わせるため、独自記事の自動執筆ではありません。ページ言語と英語を選べ、英語ページは英語のみです。一部は宣言・憲法の抜粋で、現行法の助言や公開用記事ではありません。段落数はブラウザに保存します。",
      zh: "生成1–100个排版测试段落。每段组合固定句库中的4、5或6句，是确定性样本文字，并非原创写作。可选页面语言和英语，英语页仅提供英语。部分句库含宣言或宪法摘录，不是现行法律建议或可直接发表的文章。段落数量保存在此浏览器。",
      "zh-TW": "產生1–100個排版測試段落。每段組合固定句庫中的4、5或6句，是確定性範本文字，並非原創寫作。可選頁面語言和英語，英語頁僅提供英語。部分句庫含宣言或憲法摘錄，不是現行法律建議或可直接發表的文章。段落數量保存在此瀏覽器。",
      ar: "ينشئ 1–100 فقرة لاختبار التخطيط، تجمع كل فقرة 4 أو 5 أو 6 جمل من مجموعة ثابتة. ليست كتابة أصلية. تتوفر لغة الصفحة والإنجليزية؛ الصفحة الإنجليزية تقدم الإنجليزية فقط. تضم بعض المجموعات مقتطفات من إعلانات أو دساتير، لا استشارة قانونية حديثة ولا مقالات للنشر. يُحفظ عدد الفقرات في المتصفح.",
    },
    reference: ["Declaration text used in sample sets", "https://www.ohchr.org/en/human-rights/universal-declaration/translations"],
  },
  backgroundremover: {
    examples: ["JPG / PNG / WebP → PNG", "384 px → mask → original size"],
    note: {
      en: "Select one JPG, PNG or WebP up to 10 MB. A BiRefNet model runs in a browser worker; initial model downloads need a network connection, but the input image is processed locally. The input is reduced to a maximum 384-pixel edge before preprocessing, then the mask is resized to the original dimensions. Fine hair, transparent objects and similar foreground/background colors may lose detail. Inspect the PNG on light and dark backgrounds before use; a white or black background is optional.",
      ko: "10MB 이하 JPG·PNG·WebP 한 장을 선택합니다. BiRefNet 모델을 브라우저 작업자에서 실행하며 첫 모델 다운로드에는 연결이 필요하지만 입력 이미지는 기기에서 처리합니다. 전처리 전에 최대 변을 384px로 줄인 뒤 생성한 마스크를 원래 크기로 확대하므로 머리카락·투명한 물체·배경과 비슷한 색의 경계가 손상될 수 있습니다. 밝고 어두운 배경에서 PNG 결과를 확인하세요. 흰색·검정 배경도 선택할 수 있습니다.",
      fr: "Choisissez un JPG, PNG ou WebP jusqu’à 10 Mo. BiRefNet fonctionne dans un worker du navigateur ; le premier téléchargement du modèle nécessite Internet, mais l’image est traitée localement. Le grand côté est limité à 384 px avant prétraitement, puis le masque est agrandi à l’original. Cheveux, transparence et couleurs proches peuvent perdre des détails. Vérifiez le PNG sur fonds clair et sombre ; fond blanc/noir possible.",
      de: "Ein JPG, PNG oder WebP bis 10 MB wählen. BiRefNet läuft im Browser-Worker; der erste Modelldownload braucht Internet, die Bildverarbeitung bleibt lokal. Vor Verarbeitung wird die längste Kante auf 384 px begrenzt, die Maske danach auf Originalgröße skaliert. Haare, Transparenz und ähnliche Farben können Details verlieren. PNG auf hellen und dunklen Flächen prüfen; Weiß/Schwarz ist optional.",
      es: "Seleccione un JPG, PNG o WebP de hasta 10 MB. BiRefNet se ejecuta en un worker del navegador; descargar el modelo requiere conexión, pero procesa la imagen localmente. Reduce el lado mayor a 384 px antes del preprocesado y amplía la máscara al original. Pelo, transparencias y colores parecidos pueden perder detalle. Revise el PNG sobre fondos claros y oscuros; fondo blanco/negro opcional.",
      pt: "Selecione um JPG, PNG ou WebP de até 10 MB. BiRefNet roda em um worker do navegador; baixar o modelo exige conexão, mas a imagem é processada localmente. Reduz a maior borda a 384 px antes do pré-processamento e amplia a máscara ao original. Cabelos, transparências e cores semelhantes podem perder detalhes. Confira o PNG em fundos claros e escuros; branco/preto opcional.",
      ja: "10MB以下のJPG・PNG・WebPを1枚選びます。BiRefNetをブラウザのワーカーで実行し、初回モデル取得は通信が必要ですが画像処理は端末内です。前処理前に長辺を最大384pxに縮小し、マスクを元サイズへ拡大します。髪・透明物・背景と近い色は細部が欠けることがあります。明暗背景でPNGを確認してください。白・黒背景も選べます。",
      zh: "选择一张不超过10MB的JPG、PNG或WebP。BiRefNet在浏览器工作线程运行，首次下载模型需联网，图片在本机处理。预处理前将最长边缩至最多384px，再将蒙版放大到原尺寸。头发、透明物及与背景近似的颜色可能损失细节。请在明暗背景检查PNG，亦可选择白色或黑色背景。",
      "zh-TW": "選擇一張不超過10MB的JPG、PNG或WebP。BiRefNet在瀏覽器工作執行緒運作，首次下載模型需連線，圖片在本機處理。前處理前將最長邊縮至最多384px，再將遮罩放大至原尺寸。頭髮、透明物及與背景近似的色彩可能損失細節。請在明暗背景檢查PNG，也可選擇白色或黑色背景。",
      ar: "اختر صورة JPG أو PNG أو WebP حتى 10 ميغابايت. يعمل BiRefNet في عامل المتصفح؛ تنزيل النموذج أول مرة يحتاج اتصالًا لكن معالجة الصورة محلية. تُخفض الحافة الأطول إلى 384 بكسل قبل المعالجة ثم يُكبر القناع للحجم الأصلي. قد تضيع تفاصيل الشعر والشفافية والألوان المتشابهة. افحص PNG على خلفيات فاتحة وداكنة؛ الخلفية البيضاء أو السوداء اختيارية.",
    },
    reference: ["BiRefNet browser model", "https://huggingface.co/onnx-community/BiRefNet_512x512-ONNX"],
  },
  pixelconverter: {
    examples: ["160 px ÷ 16 = 10 rem", "1 in = 96 CSS px"],
    note: {
      en: "Enter a value and choose CSS units. rem uses the root font size, em the supplied current font size, % the supplied base, and vw/vh the supplied viewport. Defaults are 16 px for fonts/base and 1440 × 900 for viewport, not measurements of your page. Blank or non-positive references fall back to these defaults. Inches use 96 CSS px, not your display’s physical pixels or print DPI. Check the actual CSS context before applying the rounded result.",
      ko: "값과 CSS 단위를 선택합니다. rem은 루트 글꼴, em은 입력한 현재 글꼴, %는 입력한 기준값, vw·vh는 입력한 화면 크기를 사용합니다. 기본값은 글꼴·기준 16px, 화면 1440×900으로 현재 페이지를 측정한 값이 아닙니다. 비어 있거나 0 이하인 기준값은 기본값으로 계산합니다. 1in=96 CSS px이며 실제 화면 픽셀이나 인쇄 DPI가 아닙니다. 반올림 결과를 적용하기 전에 실제 CSS 맥락을 확인하세요.",
      fr: "rem dépend de la police racine, em de la police courante saisie, % de la base, vw/vh du viewport saisi. Valeurs par défaut : 16 px et 1440 × 900, pas des mesures de votre page. Références vides ou non positives : retour aux défauts. 1 in = 96 pixels CSS, pas les pixels physiques ni le DPI d’impression. Vérifiez le contexte CSS avant d’utiliser le résultat arrondi.",
      de: "rem nutzt die Wurzelschrift, em die eingegebene aktuelle Schrift, % die Basis, vw/vh den eingegebenen Viewport. Standard: 16 px und 1440 × 900, keine Messung Ihrer Seite. Leere oder nicht positive Referenzen nutzen Standards. 1 in = 96 CSS-Pixel, keine physischen Pixel oder Druck-DPI. CSS-Kontext vor Übernahme des gerundeten Werts prüfen.",
      es: "rem usa la fuente raíz, em la actual indicada, % la base y vw/vh el viewport indicado. Predeterminados: 16 px y 1440 × 900, no medidas de su página. Referencias vacías o no positivas usan los valores por defecto. 1 in = 96 píxeles CSS, no píxeles físicos ni DPI de impresión. Revise el contexto CSS antes de aplicar el resultado redondeado.",
      pt: "rem usa a fonte raiz, em a fonte atual informada, % a base e vw/vh o viewport informado. Padrões: 16 px e 1440 × 900, não medidas da página. Referências vazias ou não positivas usam padrões. 1 in = 96 pixels CSS, não pixels físicos nem DPI de impressão. Confira o contexto CSS antes de aplicar o resultado arredondado.",
      ja: "remはルート文字サイズ、emは入力した現在サイズ、%は入力基準、vw・vhは入力画面サイズです。既定は16pxと1440×900で実測値ではありません。空欄や0以下の基準は既定値を使います。1in=96 CSS pxで、物理画素や印刷DPIではありません。丸め結果の使用前に実際のCSS文脈を確認してください。",
      zh: "rem使用根字体大小，em使用输入的当前字体，%使用输入基准，vw/vh使用输入视口。默认16px及1440×900，不是页面测量值。空白或非正数基准回退到默认值。1in=96 CSS像素，不是物理像素或打印DPI。应用舍入结果前请确认实际CSS上下文。",
      "zh-TW": "rem使用根字體大小，em使用輸入的目前字體，%使用輸入基準，vw/vh使用輸入視窗。預設16px與1440×900，不是頁面測量值。空白或非正數基準回復預設值。1in=96 CSS像素，不是實體像素或列印DPI。套用捨入結果前請確認實際CSS情境。",
      ar: "يستخدم rem خط الجذر وem الخط الحالي المدخل و% الأساس وvw/vh أبعاد العرض المدخلة. القيم الافتراضية 16 بكسل و1440 × 900 ليست قياسًا لصفحتك. تُستبدل المراجع الفارغة أو غير الموجبة بالافتراضيات. 1 بوصة = 96 بكسل CSS، لا بكسلات مادية أو DPI طباعة. تحقق من سياق CSS قبل استخدام الناتج المقرب.",
    },
    reference: ["CSS length units", "https://developer.mozilla.org/en-US/docs/Web/CSS/Reference/Values/length"],
  },
  currencyconverter: {
    examples: ["100 × 0.8 = 80", "1.5 / 1,5"],
    note: {
      en: "Select currencies and enter an amount using the page’s decimal separator. The formula is amount × reference rate; 100 × 0.8 = 80 is an arithmetic example, not today’s quote. Frankfurter supplies central-bank reference rates, not live trading or executable bank prices. Each pair shows its own reference date; weekends and holidays can retain older rates. Fees, spreads and actual card/transfer rates are excluded. An unavailable rate is not estimated.",
      ko: "통화와 금액을 선택하고 페이지 언어의 소수 구분자로 입력합니다. 금액×기준 환율로 계산하며 100×0.8=80은 계산 예시이지 오늘의 환율이 아닙니다. Frankfurter의 중앙은행 기준 환율로 실시간 거래·은행 체결 가격이 아닙니다. 통화쌍마다 기준일을 표시하고 주말·공휴일에는 이전 값이 유지될 수 있습니다. 수수료·환전 스프레드·실제 카드 및 송금 환율은 포함하지 않으며 조회 불가 값을 추정하지 않습니다.",
      fr: "Saisissez le montant avec la virgule décimale. Calcul : montant × taux ; 100 × 0,8 = 80 est un exemple, pas la cotation du jour. Frankfurter fournit des taux de référence de banques centrales, pas des prix négociables en direct. Chaque paire affiche sa date ; week-ends et jours fériés peuvent garder un ancien taux. Frais et marges exclus. Aucun taux manquant n’est estimé.",
      de: "Betrag mit dem Dezimaltrennzeichen der Seite eingeben. Betrag × Kurs; 100 × 0,8 = 80 ist ein Rechenbeispiel, kein Tageskurs. Frankfurter liefert Zentralbank-Referenzkurse, keine handelbaren Echtzeitpreise. Jedes Paar zeigt sein Datum; an Feiertagen können ältere Kurse gelten. Gebühren und Spreads fehlen. Fehlende Kurse werden nicht geschätzt.",
      es: "Introduzca el importe con el separador decimal del idioma. Importe × tasa; 100 × 0,8 = 80 es un ejemplo, no la cotización actual. Frankfurter ofrece referencias de bancos centrales, no precios de negociación en vivo. Cada par muestra su fecha; fines de semana y festivos pueden conservar tasas anteriores. No incluye comisiones ni márgenes. No estima tasas ausentes.",
      pt: "Informe o valor com o separador decimal do idioma. Valor × taxa; 100 × 0,8 = 80 é exemplo, não cotação atual. Frankfurter fornece referências de bancos centrais, não preços negociáveis em tempo real. Cada par mostra sua data; fins de semana e feriados podem manter taxas antigas. Taxas e spreads não incluídos. Não estima taxas ausentes.",
      ja: "ページ言語の小数区切りで金額を入力します。金額×基準レートで計算し、100×0.8=80は計算例で今日の相場ではありません。Frankfurterの中央銀行基準値で、リアルタイム取引価格ではありません。通貨ペアごとに基準日を表示し、休日は古い値が残ることがあります。手数料・スプレッド・実際のカードや送金レートを含まず、欠測は推定しません。",
      zh: "按页面语言的小数分隔符输入金额。金额×参考汇率，100×0.8=80只是计算示例，不是今日报价。Frankfurter提供央行参考值，不是实时交易或银行成交价。每个货币对显示各自日期，周末和假期可能保留旧值。不包括费用、价差及实际卡片或汇款汇率，不估算缺失汇率。",
      "zh-TW": "依頁面語言的小數分隔符輸入金額。金額×參考匯率，100×0.8=80只是計算範例，不是今日報價。Frankfurter提供央行參考值，不是即時交易或銀行成交價。每個貨幣對顯示各自日期，週末和假期可能保留舊值。不包含費用、價差及實際卡片或匯款匯率，不估算缺失匯率。",
      ar: "أدخل المبلغ بفاصل لغة الصفحة. المبلغ × السعر المرجعي؛ 100 × 0.8 = 80 مثال حسابي لا سعر اليوم. يقدم Frankfurter مراجع البنوك المركزية لا أسعار التداول الفورية أو التنفيذ البنكي. لكل زوج تاريخ مرجعي؛ قد تبقى أسعار أقدم في العطل. لا تُشمل الرسوم والفوارق وأسعار البطاقة أو التحويل الفعلية، ولا تُقدر الأسعار المفقودة.",
    },
    reference: ["Frankfurter reference-rate API", "https://frankfurter.dev/"],
  },
  unitconverter: {
    examples: ["1 m → 100 cm (0)", "32 °F → 0 °C"],
    note: { en: "Length, mass, area and volume use conversion ratios; temperature also uses an offset. Choose 0, 2, 4 or 6 decimal places. US and UK gallons differ. A year is fixed at 31,556,952 seconds (365.2425 days), and a month is one twelfth of that, not an actual calendar month. This is not a calendar calculator or precision measurement instrument.", ko: "길이·질량·면적·부피는 단위 비율을, 온도는 기준점 차이까지 반영합니다. 표시 소수 자릿수는 0·2·4·6자리이며 반올림된 결과입니다. 미국 갤런과 영국 갤런은 다릅니다. 년은 31,556,952초(365.2425일), 월은 그 1/12의 고정값이므로 실제 달력의 월·년 기간이나 정밀 측정 장비를 대신하지 않습니다.", fr: "Longueurs, masses, surfaces et volumes utilisent des rapports ; la température ajoute un décalage. Arrondi à 0, 2, 4 ou 6 décimales. Gallons US et UK diffèrent. Année fixe de 31 556 952 secondes (365,2425 jours), mois d’un douzième : pas un mois calendaire ni un instrument de précision.", de: "Länge, Masse, Fläche und Volumen nutzen Verhältnisse; Temperatur auch einen Versatz. Anzeige mit 0, 2, 4 oder 6 Dezimalstellen. US- und UK-Gallonen unterscheiden sich. Ein Jahr sind feste 31.556.952 Sekunden (365,2425 Tage), ein Monat ein Zwölftel. Kein Kalenderrechner oder Präzisionsmessgerät.", es: "Longitud, masa, área y volumen usan proporciones; temperatura también un desplazamiento. Redondea a 0, 2, 4 o 6 decimales. Galones US y UK difieren. Año fijo de 31.556.952 segundos (365,2425 días), mes de una doceava parte: no son fechas ni mediciones de precisión.", pt: "Comprimento, massa, área e volume usam proporções; temperatura também um deslocamento. Arredonda a 0, 2, 4 ou 6 casas. Galões US e UK diferem. Ano fixo de 31.556.952 segundos (365,2425 dias), mês de um doze avos: não calcula calendário nem substitui medições de precisão.", ja: "長さ・質量・面積・体積は比率、温度は基準点の差も使います。0・2・4・6桁へ丸めます。米国と英国のガロンは異なります。年は31,556,952秒（365.2425日）、月はその1/12固定で、暦の日付計算や精密測定の代用ではありません。", zh: "长度、质量、面积和体积使用比例，温度还考虑基准差。舍入到0、2、4或6位小数。美制与英制加仑不同。年固定31,556,952秒（365.2425天），月为其1/12，不是实际日历月份或精密测量仪器。", "zh-TW": "長度、質量、面積與體積使用比例，溫度還考慮基準差。捨入至0、2、4或6位小數。美制與英制加侖不同。年固定31,556,952秒（365.2425天），月為其1/12，不是實際日曆月份或精密測量儀器。", ar: "تستخدم الأطوال والكتل والمساحات والأحجام نسبًا وتضيف الحرارة فرق المرجع. التقريب إلى 0 أو 2 أو 4 أو 6 منازل. يختلف الغالون الأمريكي والبريطاني. السنة ثابتة عند 31,556,952 ثانية (365.2425 يومًا) والشهر جزء من اثني عشر منها، لا شهر تقويمي. ليست أداة قياس دقيقة." },
    reference: ["NIST SI guide", "https://www.nist.gov/pml/special-publication-811"],
  },
  percentagecalculator: {
    examples: ["200 × 25 ÷ 100 = 50", "100 → 120: (120 − 100) ÷ 100 × 100 = 20%"],
    note: { en: "Value mode multiplies the base by a percentage. Increase and decrease compare the change to the original value; a zero original has no defined percentage change. Discount returns the remaining price, not the amount saved. Results update as you type and are displayed to two decimals. Signed values follow the algebraic formula; they are not a financial recommendation.", ko: "비율 모드는 기준값에 퍼센트를 곱합니다. 증가·감소율은 원래 값 대비 변화이며 기준이 0이면 정의할 수 없습니다. 할인 모드는 할인액이 아니라 할인 후 가격을 보여줍니다. 입력하면 자동 계산하고 소수 둘째 자리까지 표시합니다. 음수는 수식을 그대로 적용하므로 금융적 판단을 대신하지 않습니다.", fr: "Valeur multiplie la base par le pourcentage. Hausse et baisse rapportent l’écart à l’original ; zéro n’a pas de variation définie. Remise donne le prix restant, pas l’économie. Calcul automatique à deux décimales. Les valeurs signées suivent la formule, sans conseil financier.", de: "Wert multipliziert die Basis mit dem Prozentsatz. Zunahme und Abnahme beziehen sich auf den Ausgangswert; bei null nicht definiert. Rabatt zeigt den Restpreis. Automatische Anzeige mit zwei Dezimalstellen. Vorzeichen folgen der Formel, keine Finanzberatung.", es: "Valor multiplica la base por el porcentaje. Aumento y disminución comparan con el original; desde cero no se define. Descuento muestra el precio final. Se actualiza al escribir con dos decimales. Valores con signo siguen la fórmula, sin consejo financiero.", pt: "Valor multiplica a base pelo percentual. Aumento e redução comparam ao original; a partir de zero é indefinido. Desconto mostra o preço final. Atualiza ao digitar com duas casas. Valores com sinal seguem a fórmula, sem orientação financeira.", ja: "割合は基準値に百分率を掛けます。増減率は元の値との比較で、0からの変化率は定義できません。割引は割引額ではなく最終価格です。入力時に計算し小数2桁まで表示します。負数は数式どおりで、金融判断の代用ではありません。", zh: "数值模式将原值乘以百分比。增减率比较原值，原值为0时未定义。折扣显示最终价格，不是节省金额。输入时自动更新到两位小数。有符号值按代数公式计算，不是金融建议。", "zh-TW": "數值模式將原值乘以百分比。增減率比較原值，原值為0時未定義。折扣顯示最終價格而非節省金額。輸入時自動更新至兩位小數。有符號值按代數公式計算，不是金融建議。", ar: "تضرب القيمة الأساس في النسبة. تُنسب الزيادة والنقصان للأصل؛ الصفر لا يملك تغيرًا نسبيًا معرّفًا. يعرض الخصم السعر النهائي لا مبلغ التوفير. يتحدث الناتج أثناء الكتابة بمنزلتين. تتبع القيم الموقعة الصيغة وليست نصيحة مالية." },
    reference: ["JavaScript Number arithmetic", "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number"],
  },
  caseconverter: {
    examples: ["hello\\nworld → Hello\\nWorld", "hello\\tworld → Hello\\tWorld"],
    note: { en: "Upper and lower case use the page language. Title Case capitalizes the first letter after whitespace, including tabs and line breaks, and lowercases the rest. It is not an editorial headline rule: acronyms and words such as 'and' need manual review. Languages without case do not gain capital letters. The transformed text replaces the input, so keep a copy of your original.", ko: "대문자·소문자는 페이지 언어 기준으로 변환합니다. Title Case는 탭·줄바꿈을 포함한 공백 다음 첫 글자만 대문자로 만들고 나머지는 소문자로 바꿉니다. 편집상의 제목 규칙이 아니므로 약어와 and 같은 단어는 직접 검토하세요. 대소문자가 없는 언어에는 효과가 없습니다. 변환은 입력을 교체하므로 원문을 별도로 보관하세요.", fr: "Majuscules et minuscules suivent la langue de la page. Title Case met en capitale la première lettre après un espace, une tabulation ou un saut de ligne, et le reste en minuscules. Ce n’est pas une règle éditoriale ; vérifiez sigles et mots de liaison. Le résultat remplace l’entrée : gardez l’original.", de: "Groß- und Kleinschreibung folgt der Seitensprache. Title Case setzt nach Leerraum, Tabs und Umbrüchen die erste Letter groß, den Rest klein. Keine redaktionelle Titelregel; Abkürzungen prüfen. Sprachen ohne Großschreibung bleiben unverändert. Das Ergebnis ersetzt die Eingabe; Original behalten.", es: "Mayúsculas y minúsculas siguen el idioma de la página. Title Case capitaliza después de espacios, tabulaciones y saltos, y pone el resto en minúsculas. No es una norma editorial; revise siglas y conectores. El resultado reemplaza la entrada; conserve el original.", pt: "Maiúsculas e minúsculas seguem o idioma da página. Title Case capitaliza após espaços, tabs e quebras e deixa o restante minúsculo. Não é regra editorial; revise siglas e conectivos. O resultado substitui a entrada; guarde o original.", ja: "大文字・小文字はページの言語で変換します。Title Caseは空白・タブ・改行後の頭文字を大文字、残りを小文字にします。編集上の見出し規則ではないため略語を確認してください。大文字のない言語には効果がありません。入力が置き換わるので原文を残しましょう。", zh: "大小写按页面语言转换。Title Case将空格、制表符和换行后的首字母大写，其余小写。它不是编辑标题规则，缩写和连接词需人工检查。无大小写的语言不受影响。结果替换输入，请保留原文。", "zh-TW": "大小寫依頁面語言轉換。Title Case將空白、定位字元和換行後的首字母大寫，其餘小寫。不是編輯標題規則，縮寫與連接詞需人工檢查。無大小寫的語言不受影響。結果會替換輸入，請保留原文。", ar: "تتبع حالة الأحرف لغة الصفحة. تجعل Title Case أول حرف بعد الفراغ أو التبويب أو السطر الجديد كبيرًا والباقي صغيرًا. ليست قاعدة تحريرية؛ راجع الاختصارات. لا تؤثر على اللغات بلا حالة أحرف. يستبدل الناتج المدخل، فاحتفظ بالأصل." },
    reference: ["Unicode casing", "https://www.unicode.org/versions/latest/core-spec/chapter-3/"],
  },
  qrgenerator: {
    examples: ["https://example.com", "WIFI:T:WPA;S:ExampleWiFi;P:password123;;"],
    note: { en: "Enter a complete https:// URL or the exact text to encode; the preview updates automatically. This creates a static QR image, not a redirect or tracked link. The destination can still disappear. Input goes to the Apps24 server to render the PNG, so use only shareable values. Before printing, scan the actual download and check its destination. Keep a light margin and dark modules; Apps24 has not certified your print size or scanner.", ko: "완전한 https:// 주소 또는 인코딩할 원문을 입력하면 미리보기가 자동 갱신됩니다. 정적 QR 이미지이며 추적 링크나 리디렉션 서비스가 아닙니다. 연결된 페이지는 사라질 수 있습니다. PNG 생성을 위해 입력이 Apps24 서버로 전송되므로 공유 가능한 값만 입력하세요. 인쇄 전 실제 다운로드 파일을 스캔해 목적지를 확인하고, 밝은 여백과 어두운 무늬를 유지하세요. 인쇄 크기나 스캐너별 성공을 인증한 도구는 아닙니다.", fr: "Saisissez une URL https:// complète ou le texte exact. L’aperçu s’actualise automatiquement. QR statique, sans redirection ni suivi ; la destination peut disparaître. L’entrée est envoyée au serveur Apps24 pour le PNG : utilisez des données partageables. Scannez le téléchargement avant impression, vérifiez la destination et gardez marge claire et modules foncés. Aucune certification de taille ou scanner.", de: "Vollständige https://-URL oder Originaltext eingeben. Vorschau aktualisiert sich automatisch. Statischer QR ohne Tracking oder Weiterleitungsdienst; das Ziel kann verschwinden. Eingabe geht zur PNG-Erzeugung an Apps24: nur teilbare Daten. Download vor Druck scannen und Ziel prüfen. Hellen Rand und dunkle Module behalten. Keine Zertifizierung von Druckgröße oder Scanner.", es: "Introduzca URL https:// completa o texto exacto. Vista automática. QR estático sin seguimiento ni redirección; el destino puede desaparecer. El texto va al servidor Apps24 para crear PNG: solo datos compartibles. Escanee la descarga antes de imprimir y revise el destino. Mantenga margen claro y módulos oscuros. No certifica tamaño ni escáner.", pt: "Informe URL https:// completa ou texto exato. Prévia automática. QR estático sem rastreamento ou redirecionamento; o destino pode desaparecer. A entrada vai ao servidor Apps24 para gerar PNG: use dados compartilháveis. Escaneie o arquivo antes de imprimir e confira o destino. Preserve margem clara e módulos escuros. Sem certificação de tamanho ou leitor.", ja: "完全なhttps:// URLまたは原文を入れると自動更新します。追跡や転送サービスではない静的QRで、リンク先がなくなる可能性はあります。PNG生成でApps24サーバーへ送信するため共有可能な値だけ入力してください。印刷前に保存した画像を読み取り、行き先を確認します。明るい余白と暗い模様を保ち、印刷サイズや機種ごとの成功は保証しません。", zh: "输入完整https://网址或原文，预览自动更新。这是静态QR，不是跟踪或重定向服务，目标页面仍可能消失。输入发送到Apps24服务器生成PNG，请仅使用可分享数据。打印前扫描实际下载文件并确认目标，保留浅色边距和深色模块。本工具不认证打印尺寸或扫描设备。", "zh-TW": "輸入完整https://網址或原文，預覽自動更新。這是靜態QR，不是追蹤或重新導向服務，目標頁面仍可能消失。輸入會傳至Apps24伺服器產生PNG，請只使用可分享資料。列印前掃描實際下載檔案並確認目標，保留淺色邊界與深色模組。不認證列印尺寸或掃描裝置。", ar: "أدخل رابط https:// كاملًا أو النص الأصلي؛ تتحدث المعاينة تلقائيًا. QR ثابت بلا تتبع أو خدمة إعادة توجيه، وقد يختفي الموقع المقصود. تُرسل المدخلات لخادم Apps24 لإنشاء PNG؛ استخدم بيانات قابلة للمشاركة. افحص الملف المنزّل بالمسح قبل الطباعة وتحقق من الوجهة. حافظ على هامش فاتح ووحدات داكنة. لا نعتمد مقاس الطباعة أو جهاز المسح." },
    reference: ["QR contents (ZXing)", "https://github.com/zxing/zxing/wiki/Barcode-Contents"],
  },
  barcodegenerator: {
    examples: ["EAN-13: 590123412345 → 5901234123457", "Code 128: ITEM-001"],
    note: { en: "Select a format before entering data. Code 128 accepts text labels; EAN-13 needs a compatible retail number and check digit. The example's 12 digits produce a 13-digit symbol. Rendering a barcode does not issue a GS1 product number or establish ownership. Formats have different character and length limits. Input is sent to the Apps24 server. Test the downloaded image with the scanner used in your workflow before printing labels.", ko: "데이터 입력 전 형식을 선택하세요. Code 128은 문자 라벨에, EAN-13은 규격에 맞는 상품 번호와 체크디지트에 사용합니다. 예시의 12자리 입력은 13자리 심벌을 생성합니다. 이미지를 만드는 것이 GS1 상품 번호 발급이나 소유권 확인은 아닙니다. 형식별 길이와 허용 문자가 다르며 입력은 Apps24 서버로 전송됩니다. 라벨을 인쇄하기 전에 실제 업무에 쓰는 스캐너로 다운로드 파일을 확인하세요.", fr: "Choisissez le format avant la saisie. Code 128 accepte des libellés ; EAN-13 exige un numéro compatible et une clé. Les 12 chiffres de l’exemple produisent un symbole à 13 chiffres. Cela ne délivre pas de numéro GS1 ni de propriété. Longueurs et caractères varient. L’entrée va au serveur Apps24. Testez le fichier avec votre scanner avant impression.", de: "Zuerst Format wählen. Code 128 für Textlabels; EAN-13 braucht eine passende Nummer und Prüfziffer. Die 12 Beispielziffern ergeben ein 13-stelliges Symbol. Keine Vergabe von GS1-Nummern oder Eigentumsprüfung. Zeichen und Längen variieren. Eingabe geht an Apps24. Datei mit dem tatsächlichen Arbeitsscanner vor dem Druck prüfen.", es: "Elija formato antes de introducir datos. Code 128 acepta etiquetas; EAN-13 requiere número válido y dígito de control. Los 12 dígitos del ejemplo producen 13. No otorga números GS1 ni propiedad. Límites varían por formato. Se envía al servidor Apps24. Pruebe la descarga con su escáner antes de imprimir.", pt: "Escolha o formato antes dos dados. Code 128 aceita rótulos; EAN-13 exige número adequado e dígito verificador. Os 12 dígitos do exemplo produzem 13. Não emite números GS1 nem comprova propriedade. Limites variam por formato. Dados vão ao servidor Apps24. Teste o arquivo com seu leitor antes de imprimir.", ja: "入力前に形式を選びます。Code 128は文字ラベル、EAN-13は適切な商品番号とチェック桁に使います。例の12桁から13桁の記号を生成します。GS1番号の発行や所有権の確認ではありません。文字と長さの制約は形式で異なり、入力はApps24サーバーへ送ります。印刷前に実際の業務用スキャナーで保存画像を試してください。", zh: "先选择格式。Code 128支持文本标签，EAN-13需要符合规范的商品号码和校验位。示例12位输入产生13位符号。生成图片不等于发放GS1号码或确认所有权。字符和长度限制依格式而异，输入发送到Apps24服务器。打印前用实际工作扫描器检查下载文件。", "zh-TW": "先選擇格式。Code 128支援文字標籤，EAN-13需要符合規範的商品號碼與檢查碼。範例12位輸入產生13位符號。產生圖片不等於發放GS1號碼或確認所有權。字元與長度限制依格式而異，輸入傳至Apps24伺服器。列印前用實際工作掃描器檢查下載檔案。", ar: "اختر الصيغة أولًا. Code 128 للنصوص؛ يحتاج EAN-13 رقم منتج مناسبًا ورقم تحقق. تنتج الأرقام الاثنا عشر في المثال رمزًا من 13 رقمًا. إنشاء الصورة لا يمنح رقم GS1 أو ملكية. تختلف حدود الأحرف والطول. تُرسل المدخلات إلى Apps24. اختبر التنزيل بجهاز العمل قبل طباعة الملصقات." },
    reference: ["GS1 check digit", "https://www.gs1.org/services/check-digit-calculator"],
  },
  base64encoder: {
    examples: ["Hello → SGVsbG8=", "안녕하세요 → 7JWI64WV7ZWY7IS47JqU"],
    note: { en: "Encode UTF-8 text to standard Base64 or decode it back to text. Base64 is not encryption: anyone can decode it. A valid binary value such as /w== cannot be displayed as UTF-8 and gets a text-decoding error, not a format error. URL-safe alphabet and file conversion are not supported. Processing stays in this browser.", ko: "UTF-8 텍스트를 표준 Base64로 바꾸거나 다시 텍스트로 해석합니다. Base64는 암호화가 아니며 누구나 복원할 수 있습니다. /w==처럼 유효한 이진 값은 UTF-8로 표시할 수 없어 형식 오류가 아닌 문자 디코딩 오류로 안내합니다. URL-safe 문자와 파일 변환은 지원하지 않으며 처리는 브라우저 안에서 수행합니다.", fr: "Encodez du texte UTF-8 en Base64 standard ou décodez-le. Base64 n’est pas un chiffrement. Une valeur binaire valide comme /w== déclenche une erreur de décodage UTF-8, pas de format. L’alphabet URL-safe et les fichiers ne sont pas pris en charge. Le traitement reste dans le navigateur.", de: "UTF-8-Text in Standard-Base64 kodieren oder zurück dekodieren. Base64 ist keine Verschlüsselung. Gültige Binärwerte wie /w== lösen einen UTF-8-Dekodierfehler aus, keinen Formatfehler. URL-sicheres Alphabet und Dateien werden nicht unterstützt. Verarbeitung im Browser.", es: "Codifique texto UTF-8 en Base64 estándar o decodifíquelo. Base64 no es cifrado. Un binario válido como /w== da un error de texto UTF-8, no de formato. No se admiten alfabeto URL-safe ni archivos. Se procesa en el navegador.", pt: "Converta texto UTF-8 em Base64 padrão ou decodifique. Base64 não é criptografia. Um binário válido como /w== gera erro de texto UTF-8, não de formato. Alfabeto URL-safe e arquivos não são suportados. O processamento ocorre no navegador.", ja: "UTF-8テキストを標準Base64と相互変換します。暗号化ではなく誰でも復元できます。有効なバイナリ値/w==は形式エラーではなくUTF-8デコードエラーになります。URL-safeやファイル変換は非対応で、ブラウザ内で処理します。", zh: "在UTF-8文本和标准Base64之间转换。Base64不是加密。/w==等有效二进制会出现UTF-8文本解码错误，而非格式错误。不支持URL-safe字符及文件转换，处理在浏览器内进行。", "zh-TW": "在UTF-8文字與標準Base64之間轉換。Base64不是加密。/w==等有效二進位值會顯示UTF-8文字解碼錯誤，而非格式錯誤。不支援URL-safe字元及檔案轉換，在瀏覽器內處理。", ar: "حوّل نص UTF-8 إلى Base64 القياسي أو العكس. Base64 ليس تشفيرًا سريًا. القيمة الثنائية الصالحة /w== تسبب خطأ نص UTF-8 لا خطأ صيغة. لا تُدعم أبجدية URL-safe أو الملفات. المعالجة داخل المتصفح." },
    reference: ["RFC 4648", "https://www.rfc-editor.org/rfc/rfc4648#section-4"],
  },
  colorconverter: {
    examples: ["ff0000 → #ff0000 → rgb(255, 0, 0) → hsl(0, 100%, 50%)", "#0f0 → #00ff00 → rgb(0, 255, 0)"],
    note: { en: "Enter a 3- or 6-digit HEX color, with or without #, or use the picker. RGB and HSL are outputs, not editable inputs. The preview and copied HEX use the expanded 6-digit color. Alpha/transparency, named colors and color-profile conversion are not supported. HSL values are rounded to integers.", ko: "# 유무와 관계없이 3자리·6자리 HEX를 입력하거나 색상 선택기를 사용하세요. RGB와 HSL은 입력이 아닌 출력입니다. 미리보기와 복사값은 6자리로 정규화한 동일 색상을 사용합니다. 알파·투명도, 색상 이름, 색상 프로파일 변환은 지원하지 않으며 HSL은 정수로 반올림합니다.", fr: "Saisissez 3 ou 6 chiffres HEX avec ou sans #, ou utilisez le sélecteur. RGB et HSL sont des sorties. Aperçu et copie utilisent le HEX étendu à 6 chiffres. Transparence, noms de couleurs et profils ne sont pas pris en charge. HSL est arrondi à l’entier.", de: "3- oder 6-stelliges HEX mit oder ohne # eingeben oder Farbwähler nutzen. RGB und HSL sind Ausgaben. Vorschau und Kopie verwenden das 6-stellige HEX. Transparenz, Farbnamen und Profilumrechnung fehlen. HSL wird ganzzahlig gerundet.", es: "Introduzca HEX de 3 o 6 dígitos, con o sin #, o use el selector. RGB y HSL son salidas. Vista y copia usan HEX de 6 dígitos. No se admiten transparencia, nombres ni perfiles de color. HSL se redondea a enteros.", pt: "Informe HEX de 3 ou 6 dígitos, com ou sem #, ou use o seletor. RGB e HSL são saídas. Prévia e cópia usam HEX de 6 dígitos. Não há transparência, nomes ou conversão de perfis. HSL é arredondado a inteiros.", ja: "#あり・なしの3桁または6桁HEXを入力するか色を選択します。RGBとHSLは出力専用です。プレビューとコピーは同じ6桁HEXです。透明度、色名、プロファイル変換は非対応で、HSLは整数に丸めます。", zh: "输入带或不带#的3位、6位HEX，或使用选色器。RGB和HSL是输出而非输入。预览和复制使用同一6位HEX。不支持透明度、颜色名称及色彩配置转换，HSL舍入为整数。", "zh-TW": "輸入帶或不帶#的3位、6位HEX，或使用選色器。RGB與HSL為輸出而非輸入。預覽與複製使用同一6位HEX。不支援透明度、色彩名稱與色彩描述檔轉換，HSL捨入為整數。", ar: "أدخل HEX من 3 أو 6 خانات مع # أو بدونه أو استخدم منتقي اللون. RGB وHSL مخرجات لا مدخلات. تستخدم المعاينة والنسخ HEX من 6 خانات. لا تُدعم الشفافية أو أسماء الألوان أو تحويل ملفات اللون. تُقرّب قيم HSL إلى أعداد صحيحة." },
    reference: ["CSS hex colors", "https://developer.mozilla.org/en-US/docs/Web/CSS/hex-color"],
  },
  textdiffchecker: {
    examples: ["A / B / C → X / A / B / C: +X", "A / B / C → A / C: −B"],
    note: { en: "This is a line comparison: matching lines are aligned after insertions or deletions. Spaces, capitalization and empty lines matter. CRLF, LF and CR line endings are normalized, so differences only in line endings are not shown. It does not compare words or characters within a changed line. The two inputs together are limited to 200,000 characters and 4 million line pairs.", ko: "행 단위 비교로 삽입·삭제 이후의 같은 행을 정렬합니다. 공백, 대소문자, 빈 줄을 구분합니다. CRLF·LF·CR 줄바꿈은 통일하므로 줄바꿈 종류만 다른 경우에는 차이로 표시하지 않습니다. 변경 행 안의 단어나 글자 단위 비교는 하지 않습니다. 두 입력 합계 20만 자, 행 조합 400만 개까지 지원합니다.", fr: "Comparaison par lignes avec alignement après insertion ou suppression. Espaces, casse et lignes vides comptent. CRLF, LF et CR sont normalisés. Pas de comparaison mot à mot dans une ligne. Limites : 200 000 caractères au total et 4 millions de paires de lignes.", de: "Zeilenvergleich mit Ausrichtung nach Einfügungen oder Löschungen. Leerraum, Großschreibung und Leerzeilen zählen. CRLF, LF und CR werden vereinheitlicht. Kein Wortvergleich innerhalb einer Zeile. Insgesamt 200.000 Zeichen und 4 Millionen Zeilenpaare.", es: "Comparación de líneas con alineación tras inserciones o borrados. Distingue espacios, mayúsculas y líneas vacías. Normaliza CRLF, LF y CR. No compara palabras dentro de una línea. Límites: 200.000 caracteres totales y 4 millones de pares de líneas.", pt: "Compara linhas alinhadas após inserções ou exclusões. Espaços, maiúsculas e linhas vazias contam. Normaliza CRLF, LF e CR. Não compara palavras dentro da linha. Limites: 200.000 caracteres no total e 4 milhões de pares de linhas.", ja: "挿入・削除後の同じ行を整列して比較します。空白、大文字小文字、空行を区別します。CRLF・LF・CRを統一するため改行形式だけの差は出ません。行内の単語比較は行わず、合計20万文字、行組合せ400万件までです。", zh: "按行比较，在插入或删除后对齐相同行。区分空格、大小写和空行。CRLF、LF、CR统一处理，不显示仅换行类型的差别。不比较行内词语，合计最多20万字符、400万行组合。", "zh-TW": "按行比較，在插入或刪除後對齊相同行。區分空白、大小寫與空行。CRLF、LF、CR統一處理，不顯示僅換行類型的差異。不比較行內單詞，合計最多20萬字元、400萬行組合。", ar: "مقارنة أسطر مع محاذاة المتطابق بعد الإضافة أو الحذف. تميز المسافات وحالة الأحرف والأسطر الفارغة. توحّد CRLF وLF وCR. لا تقارن الكلمات داخل السطر. الحد 200 ألف حرف إجمالًا و4 ملايين زوج أسطر." },
    reference: ["Longest common subsequence", "https://xlinux.nist.gov/dads/HTML/longestCommonSubsequence.html"],
  },
  passwordgenerator: {
    examples: ["A-Z + a-z + 0-9 + !@#… → 16", "0-9 → 8–64"],
    note: { en: "Choose 8–64 characters and at least one character type. Every selected type appears at least once; remaining characters and their order use Web Crypto randomness. No types selected means no password. The password is generated locally, but anything copied enters your device clipboard. Do not reuse passwords; save each in a password manager. A displayed password is not a guarantee against account compromise.", ko: "8~64자 길이와 문자 종류를 하나 이상 선택합니다. 선택한 종류를 각각 한 글자 이상 포함하고 나머지 문자와 순서는 Web Crypto 난수를 사용합니다. 종류를 모두 해제하면 생성하지 않습니다. 비밀번호는 이 기기에서 만들지만 복사하면 클립보드에 남습니다. 재사용하지 말고 비밀번호 관리자에 보관하세요. 생성만으로 계정 보안을 보장하지 않습니다.", fr: "Choisissez 8–64 caractères et au moins un type. Chaque type apparaît au moins une fois ; le reste et l’ordre utilisent Web Crypto. Aucun type signifie aucun mot de passe. Génération locale, mais la copie utilise le presse-papiers. Évitez la réutilisation et utilisez un gestionnaire. Cela ne garantit pas la sécurité du compte.", de: "8–64 Zeichen und mindestens eine Zeichenart wählen. Jede gewählte Art kommt vor; Rest und Reihenfolge nutzen Web Crypto. Ohne Auswahl kein Passwort. Lokal erzeugt, beim Kopieren aber in der Zwischenablage. Nicht wiederverwenden; Passwortmanager nutzen. Keine Garantie gegen Kontoangriffe.", es: "Elija 8–64 caracteres y al menos un tipo. Todos los tipos elegidos aparecen; el resto y el orden usan Web Crypto. Sin tipos no hay contraseña. Se genera localmente, pero copiar usa el portapapeles. No reutilice y guarde en un gestor. No garantiza la seguridad de la cuenta.", pt: "Escolha 8–64 caracteres e ao menos um tipo. Cada tipo escolhido aparece; o restante e a ordem usam Web Crypto. Sem tipos não há senha. Geração local, mas a cópia usa a área de transferência. Não reutilize e guarde em um gerenciador. Não garante a segurança da conta.", ja: "8〜64文字と1つ以上の文字種を選びます。選んだ種類を必ず含み、残りと順序はWeb Crypto乱数を使います。未選択では生成しません。端末内で生成しますがコピーはクリップボードに残ります。再利用せず管理アプリに保存してください。アカウントの安全を保証するものではありません。", zh: "选择8–64字符及至少一种类型。每种所选类型至少出现一次，其余字符和顺序使用Web Crypto随机数。全部取消则不生成。在本机生成，但复制会进入剪贴板。不要重复使用，应保存到密码管理器。生成密码不保证账号安全。", "zh-TW": "選擇8–64字元及至少一種類型。每種所選類型至少出現一次，其餘字元與順序使用Web Crypto亂數。全部取消則不產生。在本機產生，但複製會進入剪貼簿。不要重複使用，應保存到密碼管理器。不保證帳號安全。", ar: "اختر 8–64 حرفًا ونوعًا واحدًا على الأقل. يظهر كل نوع مختار مرة على الأقل ويستخدم الباقي وترتيبه عشوائية Web Crypto. بلا أنواع لا توجد كلمة مرور. التوليد محلي لكن النسخ يدخل الحافظة. لا تعِد استخدامها واحفظها في مدير كلمات مرور. لا يضمن ذلك أمن الحساب." },
    reference: ["Web Crypto getRandomValues", "https://developer.mozilla.org/en-US/docs/Web/API/Crypto/getRandomValues"],
  },
} satisfies Record<string, { examples: string[]; note: Record<Locale, string>; reference: string[] }>;

export function getFunctionalContent(locale: Locale, id: string): Partial<ToolText> {
  if (!(id in content)) return {};
  const entry = content[id as keyof typeof content];
  return { longDescription: entry.note[locale], examples: entry.examples, whyUse: "", usageContext: "", faq: [], references: { [entry.reference[0]]: entry.reference[1] }, seo: "" };
}
