import type { Locale } from "@/lib/site";

export const IP_COPY: Record<Locale, {
  title: string;
  description: string;
  copy: string;
  refresh: string;
  copied: string;
  loading: string;
  error: string;
  country: string;
  region: string;
  city: string;
  timezone: string;
  isp: string;
  browser: string;
  os: string;
  device: string;
  language: string;
  locationNote: string;
  vpnNote: string;
  unavailable: string;
  mobile: string;
  tablet: string;
  desktop: string;
  details: string;
  source: string;
  protocol: string;
}> = {
  "en": {
    "title": "Your public IP",
    "description": "Address observed for this request. A VPN, proxy or mobile network may change the address.",
    "copy": "Copy IP",
    "refresh": "Refresh",
    "copied": "Copied",
    "loading": "Loading IP information…",
    "error": "Unable to retrieve your IP. Please try again.",
    "country": "Country",
    "region": "Region",
    "city": "City",
    "timezone": "IP time zone",
    "isp": "Network provider",
    "browser": "Browser",
    "os": "Operating system",
    "device": "Device",
    "language": "Browser language",
    "locationNote": "Location is approximate and may identify a network exit rather than your home. Missing details are shown as unavailable.",
    "vpnNote": "VPN use and support for the other IP version cannot be determined from this request.",
    "unavailable": "Not available",
    "mobile": "Mobile",
    "tablet": "Tablet",
    "desktop": "Desktop",
    "details": "Network and device details",
    "source": "The public IP comes from the request, or ipify when needed. Approximate location and network data come from IPinfo.",
    "protocol": "Connection protocol"
  },
  "ko": {
    "title": "공용 IP 주소",
    "description": "현재 요청에서 확인된 주소입니다. VPN, 프록시, 이동통신망에 따라 달라질 수 있습니다.",
    "copy": "IP 복사",
    "refresh": "새로고침",
    "copied": "복사됨",
    "loading": "IP 정보 조회 중…",
    "error": "IP를 가져오지 못했습니다. 다시 시도하세요.",
    "country": "국가",
    "region": "지역",
    "city": "도시",
    "timezone": "IP 시간대",
    "isp": "네트워크 사업자",
    "browser": "브라우저",
    "os": "운영체제",
    "device": "기기",
    "language": "브라우저 언어",
    "locationNote": "위치는 대략적인 정보이며 집이 아닌 네트워크 접속 지점일 수 있습니다. 없는 정보는 확인 불가로 표시합니다.",
    "vpnNote": "이 요청만으로 VPN 사용 여부나 다른 IP 버전의 지원 여부는 판단할 수 없습니다.",
    "unavailable": "확인 불가",
    "mobile": "모바일",
    "tablet": "태블릿",
    "desktop": "데스크톱",
    "details": "네트워크 및 기기 정보",
    "source": "공용 IP는 요청 정보 또는 필요한 경우 ipify에서, 대략적인 위치와 네트워크 정보는 IPinfo에서 가져옵니다.",
    "protocol": "접속 프로토콜"
  },
  "fr": {
    "title": "Votre IP publique",
    "description": "Adresse observée pour cette requête. Un VPN, un proxy ou un réseau mobile peut la modifier.",
    "copy": "Copier l’IP",
    "refresh": "Actualiser",
    "copied": "Copié",
    "loading": "Recherche de l’IP…",
    "error": "Impossible d’obtenir votre IP. Réessayez.",
    "country": "Pays",
    "region": "Région",
    "city": "Ville",
    "timezone": "Fuseau de l’IP",
    "isp": "Opérateur réseau",
    "browser": "Navigateur",
    "os": "Système",
    "device": "Appareil",
    "language": "Langue du navigateur",
    "locationNote": "La localisation est approximative et peut désigner une sortie réseau plutôt que votre domicile. Les informations absentes sont indiquées comme indisponibles.",
    "vpnNote": "Cette requête ne permet pas de déterminer l’usage d’un VPN ni la prise en charge de l’autre version IP.",
    "unavailable": "Indisponible",
    "mobile": "Mobile",
    "tablet": "Tablette",
    "desktop": "Ordinateur",
    "details": "Informations réseau et appareil",
    "source": "L’IP publique provient de la requête ou, si nécessaire, d’ipify. La localisation approximative et le réseau proviennent d’IPinfo.",
    "protocol": "Protocole de connexion"
  },
  "de": {
    "title": "Ihre öffentliche IP",
    "description": "Für diese Anfrage beobachtete Adresse. VPN, Proxy oder Mobilfunknetz können sie verändern.",
    "copy": "IP kopieren",
    "refresh": "Aktualisieren",
    "copied": "Kopiert",
    "loading": "IP wird abgerufen…",
    "error": "IP konnte nicht abgerufen werden. Erneut versuchen.",
    "country": "Land",
    "region": "Region",
    "city": "Stadt",
    "timezone": "IP-Zeitzone",
    "isp": "Netzbetreiber",
    "browser": "Browser",
    "os": "Betriebssystem",
    "device": "Gerät",
    "language": "Browsersprache",
    "locationNote": "Der Standort ist ungefähr und kann einen Netzausgang statt Ihrer Wohnung bezeichnen. Fehlende Angaben werden als nicht verfügbar angezeigt.",
    "vpnNote": "Aus dieser Anfrage lassen sich weder VPN-Nutzung noch Unterstützung der anderen IP-Version bestimmen.",
    "unavailable": "Nicht verfügbar",
    "mobile": "Mobilgerät",
    "tablet": "Tablet",
    "desktop": "Computer",
    "details": "Netzwerk- und Gerätedaten",
    "source": "Die öffentliche IP stammt aus der Anfrage oder bei Bedarf von ipify. Ungefähre Standort- und Netzwerkdaten stammen von IPinfo.",
    "protocol": "Verbindungsprotokoll"
  },
  "es": {
    "title": "Tu IP pública",
    "description": "Dirección observada en esta solicitud. Una VPN, un proxy o una red móvil puede cambiarla.",
    "copy": "Copiar IP",
    "refresh": "Actualizar",
    "copied": "Copiado",
    "loading": "Consultando IP…",
    "error": "No se pudo obtener tu IP. Inténtalo de nuevo.",
    "country": "País",
    "region": "Región",
    "city": "Ciudad",
    "timezone": "Zona horaria de la IP",
    "isp": "Operador de red",
    "browser": "Navegador",
    "os": "Sistema operativo",
    "device": "Dispositivo",
    "language": "Idioma del navegador",
    "locationNote": "La ubicación es aproximada y puede señalar una salida de red en lugar de tu domicilio. Los datos ausentes se muestran como no disponibles.",
    "vpnNote": "Esta solicitud no permite determinar si usas una VPN ni si se admite la otra versión IP.",
    "unavailable": "No disponible",
    "mobile": "Móvil",
    "tablet": "Tableta",
    "desktop": "Ordenador",
    "details": "Datos de red y dispositivo",
    "source": "La IP pública procede de la solicitud o de ipify cuando es necesario. La ubicación aproximada y la red proceden de IPinfo.",
    "protocol": "Protocolo de conexión"
  },
  "pt": {
    "title": "Seu IP público",
    "description": "Endereço observado nesta solicitação. VPN, proxy ou rede móvel podem alterá-lo.",
    "copy": "Copiar IP",
    "refresh": "Atualizar",
    "copied": "Copiado",
    "loading": "Consultando IP…",
    "error": "Não foi possível obter seu IP. Tente novamente.",
    "country": "País",
    "region": "Região",
    "city": "Cidade",
    "timezone": "Fuso horário do IP",
    "isp": "Operadora de rede",
    "browser": "Navegador",
    "os": "Sistema operacional",
    "device": "Dispositivo",
    "language": "Idioma do navegador",
    "locationNote": "A localização é aproximada e pode indicar uma saída da rede em vez da sua residência. Dados ausentes aparecem como indisponíveis.",
    "vpnNote": "Esta solicitação não permite determinar o uso de VPN nem o suporte à outra versão IP.",
    "unavailable": "Indisponível",
    "mobile": "Celular",
    "tablet": "Tablet",
    "desktop": "Computador",
    "details": "Dados de rede e dispositivo",
    "source": "O IP público vem da solicitação ou, quando necessário, do ipify. A localização aproximada e a rede vêm do IPinfo.",
    "protocol": "Protocolo de conexão"
  },
  "ja": {
    "title": "公開IPアドレス",
    "description": "このリクエストで確認したアドレスです。VPN、プロキシ、モバイル回線で変わることがあります。",
    "copy": "IPをコピー",
    "refresh": "更新",
    "copied": "コピー済み",
    "loading": "IP情報を取得中…",
    "error": "IPを取得できませんでした。もう一度お試しください。",
    "country": "国",
    "region": "地域",
    "city": "都市",
    "timezone": "IPのタイムゾーン",
    "isp": "ネットワーク事業者",
    "browser": "ブラウザ",
    "os": "OS",
    "device": "端末",
    "language": "ブラウザの言語",
    "locationNote": "位置情報は概算で、自宅ではなくネットワークの出口を示すことがあります。取得できない情報は不明と表示します。",
    "vpnNote": "このリクエストだけではVPNの使用や別のIPバージョンの対応状況を判定できません。",
    "unavailable": "不明",
    "mobile": "モバイル",
    "tablet": "タブレット",
    "desktop": "パソコン",
    "details": "ネットワークと端末の情報",
    "source": "公開IPはリクエスト、必要に応じてipifyから取得します。概算の位置とネットワーク情報はIPinfoから取得します。",
    "protocol": "接続プロトコル"
  },
  "zh": {
    "title": "公网 IP 地址",
    "description": "此请求中观测到的地址。VPN、代理或移动网络可能改变该地址。",
    "copy": "复制 IP",
    "refresh": "刷新",
    "copied": "已复制",
    "loading": "正在查询 IP…",
    "error": "无法获取 IP，请重试。",
    "country": "国家",
    "region": "地区",
    "city": "城市",
    "timezone": "IP 时区",
    "isp": "网络运营商",
    "browser": "浏览器",
    "os": "操作系统",
    "device": "设备",
    "language": "浏览器语言",
    "locationNote": "位置仅为估计，可能显示网络出口而非住宅。缺失信息显示为无法获取。",
    "vpnNote": "仅凭此请求无法判断 VPN 使用情况或是否支持另一 IP 版本。",
    "unavailable": "无法获取",
    "mobile": "手机",
    "tablet": "平板",
    "desktop": "电脑",
    "details": "网络和设备信息",
    "source": "公网 IP 来自请求信息，必要时通过 ipify 获取。大致位置及网络信息来自 IPinfo。",
    "protocol": "连接协议"
  },
  "zh-TW": {
    "title": "公用 IP 位址",
    "description": "此請求中觀測到的位址。VPN、代理或行動網路可能改變此位址。",
    "copy": "複製 IP",
    "refresh": "重新整理",
    "copied": "已複製",
    "loading": "正在查詢 IP…",
    "error": "無法取得 IP，請重試。",
    "country": "國家",
    "region": "地區",
    "city": "城市",
    "timezone": "IP 時區",
    "isp": "網路業者",
    "browser": "瀏覽器",
    "os": "作業系統",
    "device": "裝置",
    "language": "瀏覽器語言",
    "locationNote": "位置僅為估計，可能顯示網路出口而非住家。缺少的資訊顯示為無法取得。",
    "vpnNote": "僅憑此請求無法判斷 VPN 使用情況或是否支援另一 IP 版本。",
    "unavailable": "無法取得",
    "mobile": "手機",
    "tablet": "平板",
    "desktop": "電腦",
    "details": "網路與裝置資訊",
    "source": "公用 IP 來自請求資訊，必要時透過 ipify 取得。大致位置及網路資訊來自 IPinfo。",
    "protocol": "連線協定"
  },
  "ar": {
    "title": "عنوان IP العام",
    "description": "العنوان الذي رُصد لهذا الطلب. قد يتغير بسبب VPN أو وكيل أو شبكة الهاتف.",
    "copy": "نسخ IP",
    "refresh": "تحديث",
    "copied": "تم النسخ",
    "loading": "جارٍ جلب معلومات IP…",
    "error": "تعذر جلب عنوان IP. حاول مجددًا.",
    "country": "الدولة",
    "region": "المنطقة",
    "city": "المدينة",
    "timezone": "المنطقة الزمنية للعنوان",
    "isp": "مشغل الشبكة",
    "browser": "المتصفح",
    "os": "نظام التشغيل",
    "device": "الجهاز",
    "language": "لغة المتصفح",
    "locationNote": "الموقع تقريبي وقد يشير إلى مخرج الشبكة بدلًا من منزلك. تظهر المعلومات المفقودة على أنها غير متاحة.",
    "vpnNote": "لا يمكن تحديد استخدام VPN أو دعم إصدار IP الآخر من هذا الطلب وحده.",
    "unavailable": "غير متاح",
    "mobile": "هاتف",
    "tablet": "جهاز لوحي",
    "desktop": "حاسوب",
    "details": "معلومات الشبكة والجهاز",
    "source": "يأتي IP العام من الطلب أو من ipify عند الحاجة. ويأتي الموقع التقريبي ومعلومات الشبكة من IPinfo.",
    "protocol": "بروتوكول الاتصال"
  }
};
