import type { Locale } from "@/lib/site";

export type LegalContent = {
  about: {
    title: string;
    intro: string;
    whatWeOffer: { heading: string; items: string[] };
    approach: { heading: string; items: { title: string; body: string }[] };
    whoItsFor: { heading: string; items: string[] };
    whyWeBuilt: { heading: string; body: string };
    goal: { heading: string; body: string };
    /** 하위 호환용 (구 UI에서 content 배열을 참조할 경우) */
    content: string[];
  };
  privacy: { title: string; content: { section: string; body: string }[] };
  terms: { title: string; content: { section: string; body: string }[] };
  contact: {
    title: string;
    intro: string;
    welcomeItems: string[];
    emailHeading: string;
    email: string;
    reportDescription: string;
    reportItems: string[];
    responseHeading: string;
    responseBody: string;
    suggestionsHeading: string;
    suggestionsBody: string;
    businessHeading: string;
    businessBody: string;
    beforeContactHeading: string;
    beforeContactItems: string[];
    closing: string;
    /** 하위 호환용 */
    content: string;
  };
};

export const LEGAL_TEXTS: Record<Locale, LegalContent> = {
  en: {
    about: {
      title: "About Apps24",
      intro: "Apps24 is a multilingual online tools website for everyday browser-based tasks. It brings together practical utilities that can be opened and used quickly without installation. The pages are kept simple so you can find a tool, finish a task, and move on without unnecessary steps.",
      whatWeOffer: {
        heading: "What we provide",
        items: [
          "Text formatting and conversion",
          "Image compression and optimization",
          "JSON formatting and validation",
          "Password generation",
          "QR code and barcode generation",
          "Unit conversion and quick calculations",
        ],
      },
      approach: {
        heading: "How it works",
        items: [
          { title: "Simple and fast", body: "The tools are built to open quickly and work through a short, clear flow." },
          { title: "No installation required", body: "Most tools can be used directly in the browser without downloads or sign-up." },
          { title: "Browser-based processing", body: "Many tools process input locally in the browser whenever possible." },
          { title: "Clear page structure", body: "Each page follows the same simple pattern: a short intro, useful sections, and a clear return path to the tools." },
        ],
      },
      whoItsFor: {
        heading: "Who it helps",
        items: [
          "Students working with text and formatting",
          "Developers checking JSON, encoding, and technical data",
          "Designers handling colors and visual assets",
          "Small businesses creating labels and QR codes",
          "General users looking for quick online tools",
          "Anyone who needs quick conversions and checks",
        ],
      },
      whyWeBuilt: {
        heading: "Why we built it",
        body: "Many online tools are cluttered, fragmented, or harder to use than they should be. Apps24 focuses on practical browser tools that are easy to open and use, with pages kept lightweight and easy to scan.",
      },
      goal: {
        heading: "What we're building",
        body: "We are continuing to add useful web tools that solve common tasks in a simple way. We also keep the layout consistent so the site stays easy to understand.",
      },
      content: [
        "Apps24 is a multilingual online tools website for everyday browser-based tasks.",
        "We provide lightweight browser tools for text formatting, image compression, JSON validation, password generation, QR codes, and more.",
        "Our goal is to maintain a practical library of tools that are easy to open and use.",
      ],
    },
    privacy: {
      title: "Privacy Policy",
      content: [
        { section: "Introduction", body: "This policy explains how Apps24 handles data when you use the site." },
        { section: "Data Collection", body: "Most tools process input locally in your browser. Some features may use third-party services when live results are needed." },
        { section: "Log Files", body: "Like other websites, we use log files for traffic analysis and maintenance. This includes IP addresses, browser types, and timestamps, which are not linked to personally identifiable information." },
        { section: "Browser Storage", body: "Some tools store user preferences locally on your device using browser storage such as localStorage." },
        { section: "Third-Party Services", body: "Features such as IP lookup may use external providers to display network and location details." },
        { section: "Data Minimization", body: "We only use the information needed to operate the site and handle support requests." },
        { section: "Policy Updates", body: "If this policy changes, we will update this page so the current version is always available here." },
        { section: "Contact", body: "If you have questions about this policy, contact us." },
      ],
    },
    terms: {
      title: "Terms of Service",
      content: [
        { section: "Acceptance of Terms", body: "By accessing Apps24, you agree to be bound by these terms of service and all applicable laws and regulations." },
        { section: "Use License", body: "The tools on this site are provided for personal and commercial use. You may not copy, modify, reverse engineer, or redistribute our code without permission." },
        { section: "Disclaimer", body: "The tools are provided 'as is'. We do not guarantee accuracy or suitability for every use case." },
        { section: "Acceptable Use", body: "Please use the tools in a lawful and reasonable way and avoid actions that could disrupt the site or other users." },
        { section: "User Responsibility", body: "Please review output before relying on it in work, publishing, or other important use cases." },
        { section: "Service Changes", body: "We may improve, replace, or remove tools over time as the site evolves." },
        { section: "Limitations", body: "Apps24 is not liable for damages arising from the use or inability to use the tools on the site." },
      ],
    },
    contact: {
      title: "Contact Apps24",
      intro: "If you have questions, bug reports, or suggestions, contact us.",
      welcomeItems: [
        "Tool errors or bugs",
        "Incorrect output or formatting issues",
        "Feature suggestions",
        "Language or translation improvements",
        "Business inquiries",
        "General feedback about the website",
        "Pages affected",
        "Steps to reproduce",
        "Expected and actual result",
      ],
      emailHeading: "Email Support",
      email: "support@apps24.io",
      reportDescription: "If you are reporting an issue, please include as much detail as possible:",
      reportItems: [
        "The tool name",
        "The page URL",
        "The browser or device you used",
        "A short description of the issue",
        "A screenshot if available",
        "The expected result",
        "The actual result",
      ],
      responseHeading: "Response Time",
      responseBody: "We aim to review inquiries as quickly as possible. Response time may vary depending on the request.",
      suggestionsHeading: "Suggestions and Feedback",
      suggestionsBody: "If you have ideas to improve usability or new tools you would like to see, we would be glad to hear from you.",
      businessHeading: "Business and Partnership Inquiries",
      businessBody: "For business or partnership inquiries, please email us with a clear subject line and a short summary so we can review your request efficiently.",
      beforeContactHeading: "Before You Contact Us",
      beforeContactItems: ["About Us", "Privacy Policy", "Terms of Service"],
      closing: "Thank you for visiting Apps24.",
      content: "If you have questions, feedback, or suggestions, feel free to contact us at support@apps24.io.",
    },
  },

  ko: {
    about: {
      title: "Apps24 소개",
      intro: "Apps24는 일상적인 브라우저 작업을 빠르게 처리할 수 있도록 만든 다국어 온라인 도구 사이트입니다. 설치 없이 바로 열어 쓸 수 있는 실용적인 유틸리티를 한곳에 모았습니다. 필요한 도구를 빨리 찾고, 짧은 흐름으로 바로 작업을 끝낼 수 있게 구성했습니다.",
      whatWeOffer: {
        heading: "제공하는 도구",
        items: [
          "텍스트 서식 정리와 변환",
          "이미지 압축과 최적화",
          "JSON 서식화와 유효성 검사",
          "비밀번호 생성",
          "QR 코드와 바코드 생성",
          "단위 변환과 빠른 계산",
        ],
      },
      approach: {
        heading: "작동 방식",
        items: [
          { title: "간단하고 빠른 흐름", body: "도구를 열고 바로 작업할 수 있도록 짧고 명확한 흐름으로 구성했습니다." },
          { title: "설치가 필요 없음", body: "대부분의 도구는 다운로드나 회원가입 없이 브라우저에서 바로 사용할 수 있습니다." },
          { title: "브라우저 내 처리", body: "가능한 경우 입력값을 브라우저에서 직접 처리하도록 설계했습니다." },
          { title: "명확한 페이지 구조", body: "각 페이지는 짧은 소개, 필요한 섹션, 그리고 도구로 돌아가기 쉬운 구성으로 맞췄습니다." },
        ],
      },
      whoItsFor: {
        heading: "이용 대상",
        items: [
          "텍스트와 서식을 다루는 학생",
          "JSON, 인코딩, 기술 데이터를 확인하는 개발자",
          "색상과 시각 자료를 다루는 디자이너",
          "라벨과 QR 코드를 만드는 소규모 사업자",
          "빠른 온라인 도구가 필요한 일반 사용자",
          "빠른 변환과 확인이 필요한 사용자",
        ],
      },
      whyWeBuilt: {
        heading: "만든 이유",
        body: "복잡하거나 무거운 온라인 도구 대신, 바로 열어 바로 쓸 수 있는 실용적인 도구를 제공하기 위해 만들었습니다. 페이지도 가볍고 읽기 쉽게 유지했습니다.",
      },
      goal: {
        heading: "현재 목표",
        body: "자주 쓰는 웹 작업을 빠르게 처리할 수 있는 도구 모음을 계속 정리하고 있습니다. 구조도 일관되게 유지해서 처음 보는 사용자도 쉽게 이해할 수 있게 하겠습니다.",
      },
      content: [
        "Apps24는 일상적인 브라우저 작업을 빠르게 처리할 수 있도록 만든 다국어 온라인 도구 사이트입니다.",
        "텍스트 변환, 이미지 압축, JSON 검사, 비밀번호 생성, QR 코드 등 실용적인 브라우저 기반 도구를 제공합니다.",
        "저희의 목표는 쉽게 열고 바로 쓸 수 있는 도구 모음을 유지하는 것입니다.",
      ],
    },
    privacy: {
      title: "개인정보처리방침",
      content: [
        { section: "소개", body: "본 정책은 Apps24를 이용할 때 데이터가 어떻게 처리되는지 설명합니다." },
        { section: "데이터 수집", body: "대부분의 도구는 브라우저에서 입력값을 로컬로 처리합니다. 일부 기능은 실시간 결과가 필요할 때 외부 서비스를 사용할 수 있습니다." },
        { section: "로그 파일", body: "트래픽 분석 및 유지보수를 위해 로그 파일을 사용합니다. IP 주소, 브라우저 유형, 타임스탬프가 포함되나 개인 식별 정보와 연결되지 않습니다." },
        { section: "브라우저 저장소", body: "일부 도구는 localStorage와 같은 브라우저 저장소를 사용해 사용자 환경설정을 로컬 기기에 저장합니다." },
        { section: "제3자 서비스", body: "IP 조회와 같은 기능은 네트워크 및 위치 정보를 표시하기 위해 외부 제공업체의 데이터를 사용할 수 있습니다." },
        { section: "데이터 최소화", body: "서비스 운영과 문의 응답에 필요한 정보만 사용하며, 가능한 한 적은 정보만 다루도록 설계했습니다." },
        { section: "정책 업데이트", body: "정책이 변경되면 이 페이지를 함께 업데이트하여 현재 버전을 확인할 수 있게 합니다." },
        { section: "문의", body: "이 정책에 대해 궁금하신 점이 있으시면 문의해 주세요." },
      ],
    },
    terms: {
      title: "이용약관",
      content: [
        { section: "약관 동의", body: "Apps24에 접속함으로써 귀하는 본 이용약관 및 관련 법규를 준수할 것에 동의하게 됩니다." },
        { section: "이용 라이선스", body: "본 사이트의 도구는 개인적 및 상업적 용도로 제공됩니다. 명시적 허가 없이 코드를 복사, 수정, 역설계 또는 재배포할 수 없습니다." },
        { section: "면책 조항", body: "도구는 '있는 그대로' 제공됩니다. 모든 사용 사례에 대해 정확성이나 적합성을 보증하지 않습니다." },
        { section: "허용되는 사용", body: "도구는 합법적이고 적절한 방식으로 사용해야 하며, 사이트나 다른 사용자의 이용을 방해하는 행위는 삼가야 합니다." },
        { section: "사용자 책임", body: "업무, 게시 또는 중요한 용도로 사용하기 전에 결과를 직접 확인해야 합니다." },
        { section: "서비스 변경", body: "사이트가 발전함에 따라 도구를 개선, 교체 또는 제거할 수 있습니다." },
        { section: "책임 제한", body: "Apps24는 사이트 도구의 이용 또는 이용 불능으로 인해 발생하는 손해에 대해 책임지지 않습니다." },
      ],
    },
    contact: {
      title: "Apps24 문의",
      intro: "질문, 버그 신고 또는 제안이 있으시면 문의해 주세요.",
      welcomeItems: [
        "도구 오류 또는 버그",
        "잘못된 출력 또는 형식 문제",
        "기능 제안",
        "언어 또는 번역 개선",
        "비즈니스 문의",
        "웹사이트에 대한 일반 피드백",
        "영향받는 페이지",
        "재현 단계",
        "예상 결과와 실제 결과",
      ],
      emailHeading: "이메일 지원",
      email: "support@apps24.io",
      reportDescription: "문제를 신고하실 경우 가능한 한 자세한 정보를 포함해 주세요:",
      reportItems: [
        "도구 이름",
        "페이지 URL",
        "사용한 브라우저 또는 기기",
        "문제에 대한 간략한 설명",
        "가능하면 스크린샷",
        "예상한 결과",
        "실제 결과",
      ],
      responseHeading: "응답 시간",
      responseBody: "저희는 최대한 빠르게 문의를 검토하겠습니다. 요청 유형에 따라 답변 시간은 달라질 수 있습니다.",
      suggestionsHeading: "제안 및 피드백",
      suggestionsBody: "사용성 개선 아이디어나 추가되었으면 하는 도구가 있으면 기꺼이 듣겠습니다.",
      businessHeading: "비즈니스 및 파트너십 문의",
      businessBody: "비즈니스 또는 파트너십 문의는 명확한 제목과 간단한 요약을 넣어 이메일로 보내 주시면 효율적으로 검토하겠습니다.",
      beforeContactHeading: "문의 전 확인사항",
      beforeContactItems: ["소개", "개인정보처리방침", "이용약관"],
      closing: "Apps24를 방문해 주셔서 감사합니다.",
      content: "질문, 피드백 또는 제안이 있으시면 support@apps24.io로 문의해 주세요.",
    },
  },

  fr: {
    about: {
      title: "À propos d'Apps24",
      intro: "Apps24 est un site d'outils en ligne multilingue pour les tâches quotidiennes dans le navigateur. Il regroupe des utilitaires pratiques à ouvrir et utiliser rapidement, sans installation. Les pages restent courtes et lisibles pour faciliter la recherche d'un outil et l'exécution d'une tâche.",
      whatWeOffer: {
        heading: "Ce que nous proposons",
        items: [
          "Mise en forme et conversion de texte",
          "Compression et optimisation d'images",
          "Mise en forme et validation JSON",
          "Génération de mots de passe",
          "Génération de codes QR et de codes-barres",
          "Conversion d'unités et calculs rapides",
        ],
      },
      approach: {
        heading: "Comment cela fonctionne",
        items: [
          { title: "Simple et rapide", body: "Les outils sont conçus pour s'ouvrir vite et suivre un flux court et clair." },
          { title: "Sans installation", body: "La plupart des outils peuvent être utilisés directement dans le navigateur, sans téléchargement ni inscription." },
          { title: "Traitement dans le navigateur", body: "Lorsque c'est possible, les données sont traitées localement dans le navigateur." },
          { title: "Structure de page claire", body: "Chaque page garde la même structure simple avec une introduction courte, des sections utiles et un retour facile vers les outils." },
        ],
      },
      whoItsFor: {
        heading: "À qui cela s'adresse",
        items: [
          "Étudiants travaillant avec du texte et de la mise en forme",
          "Développeurs vérifiant JSON, l'encodage et les données techniques",
          "Designers gérant les couleurs et les visuels",
          "Petites entreprises créant des étiquettes et des codes QR",
          "Utilisateurs cherchant des outils en ligne rapides",
          "Utilisateurs qui ont besoin de conversions et de vérifications rapides",
        ],
      },
      whyWeBuilt: {
        heading: "Pourquoi nous l'avons créé",
        body: "De nombreux outils en ligne sont trop compliqués ou dispersés. Apps24 se concentre sur des utilitaires pratiques, faciles à ouvrir et à utiliser, avec des pages légères et faciles à parcourir.",
      },
      goal: {
        heading: "Ce que nous construisons",
        body: "Nous continuons à ajouter des outils web utiles pour résoudre les tâches courantes de manière simple. Nous gardons aussi une structure cohérente pour que le site reste facile à comprendre.",
      },
      content: [
        "Apps24 est un site d'outils en ligne multilingue pour les tâches quotidiennes dans le navigateur.",
        "Nous proposons des outils légers pour la mise en forme de texte, la compression d'images, la validation JSON et plus encore.",
        "Notre objectif est de maintenir une bibliothèque pratique d'outils faciles à utiliser.",
      ],
    },
    privacy: {
      title: "Politique de confidentialité",
      content: [
        { section: "Introduction", body: "Cette politique explique comment Apps24 traite les données lorsque vous utilisez le site." },
        { section: "Collecte de données", body: "La plupart des outils traitent les données localement dans votre navigateur. Certaines fonctionnalités peuvent utiliser des services tiers lorsque des résultats en direct sont nécessaires." },
        { section: "Fichiers journaux", body: "Comme d'autres sites, nous utilisons des fichiers journaux pour l'analyse du trafic et la maintenance. Cela inclut les adresses IP, les types de navigateurs et les horodatages, qui ne sont pas liés à des informations personnellement identifiables." },
        { section: "Stockage du navigateur", body: "Certains outils enregistrent les préférences localement sur votre appareil à l'aide du stockage du navigateur, comme localStorage." },
        { section: "Services tiers", body: "Des fonctionnalités comme la recherche d'adresse IP peuvent utiliser des fournisseurs externes pour afficher les détails du réseau et de la localisation." },
        { section: "Minimisation des données", body: "Nous n'utilisons que les informations nécessaires au fonctionnement du site et au traitement des demandes d'assistance." },
        { section: "Mises à jour de la politique", body: "Si cette politique change, nous mettrons cette page à jour afin que la version actuelle soit toujours disponible ici." },
        { section: "Contact", body: "Si vous avez des questions sur cette politique, veuillez nous contacter." },
      ],
    },
    terms: {
      title: "Conditions d'utilisation",
      content: [
        { section: "Acceptation des conditions", body: "En accédant à Apps24, vous acceptez d'être lié par ces conditions d'utilisation et toutes les lois et réglementations applicables." },
        { section: "Licence d'utilisation", body: "Les outils de ce site sont fournis pour un usage personnel et commercial. Vous ne pouvez pas copier, modifier, décompiler ou redistribuer notre code sans permission." },
        { section: "Avertissement", body: "Les outils sont fournis 'en l'état'. Nous ne garantissons pas qu'ils soient exacts ou adaptés à chaque usage." },
        { section: "Utilisation acceptable", body: "Veuillez utiliser les outils de manière légale et raisonnable, et éviter toute action qui pourrait perturber le site ou les autres utilisateurs." },
        { section: "Responsabilité de l'utilisateur", body: "Veuillez vérifier les résultats avant de les utiliser dans un travail, une publication ou tout autre usage important." },
        { section: "Évolution du service", body: "Nous pouvons améliorer, remplacer ou supprimer des outils au fil du temps à mesure que le site évolue." },
        { section: "Limitations", body: "Apps24 ne pourra pas être tenu responsable des dommages résultant de l'utilisation ou de l'impossibilité d'utiliser les outils du site." },
      ],
    },
    contact: {
      title: "Contacter Apps24",
      intro: "Si vous avez des questions, des bugs à signaler ou des suggestions, n'hésitez pas à nous contacter.",
      welcomeItems: [
        "Erreurs ou bugs d'outils",
        "Problèmes de sortie incorrecte ou de mise en forme",
        "Suggestions de fonctionnalités",
        "Améliorations linguistiques ou de traduction",
        "Demandes commerciales",
        "Commentaires généraux sur le site",
        "Pages concernées",
        "Étapes pour reproduire",
        "Résultat attendu et résultat obtenu",
      ],
      emailHeading: "Support par e-mail",
      email: "support@apps24.io",
      reportDescription: "Si vous signalez un problème, veuillez inclure autant de détails que possible :",
      reportItems: [
        "Le nom de l'outil",
        "L'URL de la page",
        "Le navigateur ou l'appareil utilisé",
        "Une courte description du problème",
        "Une capture d'écran si disponible",
        "Le résultat attendu",
        "Le résultat obtenu",
      ],
      responseHeading: "Délai de réponse",
      responseBody: "Nous essayons de traiter les demandes aussi rapidement que possible. Le délai de réponse peut varier selon la demande.",
      suggestionsHeading: "Suggestions et commentaires",
      suggestionsBody: "Si vous avez des idées pour améliorer la convivialité ou des outils à ajouter, nous serions ravis de vous entendre.",
      businessHeading: "Demandes commerciales et partenariats",
      businessBody: "Pour les demandes commerciales ou de partenariat, veuillez nous contacter par e-mail avec un objet clair et un bref résumé.",
      beforeContactHeading: "Avant de nous contacter",
      beforeContactItems: ["À propos de nous", "Politique de confidentialité", "Conditions d'utilisation"],
      closing: "Merci de visiter Apps24.",
      content: "Si vous avez des questions ou suggestions, contactez-nous à support@apps24.io.",
    },
  },

  ja: {
    about: {
      title: "Apps24について",
      intro: "Apps24は、日常のブラウザ作業をすばやく処理するための多言語オンラインツールサイトです。インストールなしでそのまま開いて使える実用的なユーティリティをまとめています。ページは短く、必要な機能をすぐ見つけられるように整理しています。",
      whatWeOffer: {
        heading: "提供するツール",
        items: [
          "テキストの書式変換",
          "画像の圧縮と最適化",
          "JSONの書式化と検証",
          "パスワード生成",
          "QRコードとバーコードの生成",
          "単位変換と簡単な計算",
        ],
      },
      approach: {
        heading: "使い方",
        items: [
          { title: "シンプルで高速", body: "短くわかりやすい流れで、すぐに使えるよう設計しています。" },
          { title: "インストール不要", body: "多くのツールはダウンロードやサインアップなしで使えます。" },
          { title: "ブラウザ内処理", body: "可能な場合は、入力内容をブラウザ内で処理します。" },
          { title: "わかりやすいページ構成", body: "各ページは短い説明、必要なセクション、そしてツールへ戻りやすい導線でそろえています。" },
        ],
      },
      whoItsFor: {
        heading: "対象ユーザー",
        items: [
          "テキストや書式を扱う学生",
          "JSONやエンコーディングを確認する開発者",
          "色や画像を扱うデザイナー",
          "ラベルやQRコードを作成する小規模事業者",
          "すぐ使えるオンラインツールを探している一般ユーザー",
          "素早い変換や確認が必要なユーザー",
        ],
      },
      whyWeBuilt: {
        heading: "Apps24を作った理由",
        body: "多くのオンラインツールは複雑だったり、まとまりがなかったりします。Apps24は、すぐ開いて使える実用的なツールに絞ってまとめています。ページも軽く、読みやすく保っています。",
      },
      goal: {
        heading: "現在の取り組み",
        body: "よく使うWeb作業を簡単に処理できるツールを順番に整えています。見た目と構成も統一して、初めてでも理解しやすい状態を保ちます。",
      },
      content: [
        "Apps24は、日常のブラウザ作業をすばやく処理するための多言語オンラインツールサイトです。",
        "テキスト変換、画像圧縮、JSON検証、パスワード生成、QRコードなどの実用的なツールを提供します。",
        "すぐ開いて使えるツールをまとめることを目指しています。",
      ],
    },
    privacy: {
      title: "プライバシーポリシー",
      content: [
        { section: "はじめに", body: "このポリシーでは、Apps24の利用時にデータをどのように扱うかを説明します。" },
        { section: "データ収集", body: "ほとんどのツールはブラウザ内でローカル処理されますが、一部の機能ではライブ結果のために外部サービスを利用する場合があります。" },
        { section: "ログファイル", body: "トラフィック分析とメンテナンスのためにログファイルを使用します。IPアドレス、ブラウザの種類、タイムスタンプが含まれますが、個人識別情報とは連携しません。" },
        { section: "ブラウザ保存", body: "一部のツールは、localStorage などのブラウザ保存領域を使って設定を端末に保存します。" },
        { section: "第三者サービス", body: "IP検索のような機能では、ネットワーク情報や位置情報を表示するために外部プロバイダーを利用する場合があります。" },
        { section: "データの最小化", body: "サイト運営とお問い合わせ対応に必要な情報だけを扱うようにしています。" },
        { section: "ポリシーの更新", body: "内容を変更した場合は、このページを更新して最新の内容を確認できるようにします。" },
        { section: "お問い合わせ", body: "このポリシーについてご質問があれば、お問い合わせください。" },
      ],
    },
    terms: {
      title: "利用規約",
      content: [
        { section: "規約への同意", body: "Apps24にアクセスすることで、本利用規約および適用されるすべての法律・規制に拘束されることに同意します。" },
        { section: "使用ライセンス", body: "本サイトのツールは個人および商業目的で提供されます。明示的な許可なしにコードをコピー、変更、リバースエンジニアリング、再配布することはできません。" },
        { section: "免責事項", body: "ツールは「現状のまま」提供されます。すべての用途に対して正確性や適合性を保証しません。" },
        { section: "適切な利用", body: "ツールは法的かつ適切な方法で使用し、サイトや他の利用者の妨げになる行為は避けてください。" },
        { section: "利用者の責任", body: "仕事、公開、重要な用途に使う前に、必ず結果を確認してください。" },
        { section: "サービスの変更", body: "サイトの進化に合わせて、ツールの改善、置き換え、削除を行う場合があります。" },
        { section: "制限事項", body: "Apps24はサイトのツールの使用または使用不能から生じる損害について責任を負いません。" },
      ],
    },
    contact: {
      title: "Apps24へのお問い合わせ",
      intro: "ご質問、バグ報告、ご提案がございましたら、お気軽にお問い合わせください。",
      welcomeItems: [
        "ツールのエラーやバグ",
        "誤った出力や書式の問題",
        "機能の提案",
        "言語や翻訳の改善",
        "ビジネスに関するお問い合わせ",
        "ウェブサイトに関する一般的なフィードバック",
        "該当ページ",
        "再現手順",
        "期待した結果と実際の結果",
      ],
      emailHeading: "メールサポート",
      email: "support@apps24.io",
      reportDescription: "問題を報告される場合は、できるだけ詳しい情報をお知らせください：",
      reportItems: [
        "ツール名",
        "ページURL",
        "使用したブラウザまたはデバイス",
        "問題の簡単な説明",
        "可能であればスクリーンショット",
        "期待した結果",
        "実際の結果",
      ],
      responseHeading: "回答時間",
      responseBody: "お問い合わせはできるだけ早く確認いたします。内容によっては回答まで少し時間をいただく場合があります。",
      suggestionsHeading: "ご提案とフィードバック",
      suggestionsBody: "使いやすさの改善アイデアや追加してほしいツールがあれば、ぜひお聞かせください。",
      businessHeading: "ビジネス・パートナーシップのお問い合わせ",
      businessBody: "ビジネス関連の連絡やパートナーシップのお問い合わせは、明確な件名と簡単な要約を付けてメールでご連絡ください。",
      beforeContactHeading: "お問い合わせ前に",
      beforeContactItems: ["概要", "プライバシーポリシー", "利用規約"],
      closing: "Apps24をご利用いただきありがとうございます。",
      content: "ご質問やご提案はsupport@apps24.ioまでお問い合わせください。",
    },
  },

  zh: {
    about: {
      title: "关于 Apps24",
      intro: "Apps24 是一个多语言在线工具网站，面向日常浏览器任务。我们把实用工具集中在一起，方便您无需安装即可快速使用。",
      whatWeOffer: {
        heading: "我们提供的工具",
        items: [
          "文本格式化与转换",
          "图像压缩与优化",
          "JSON 格式化与验证",
          "密码生成",
          "QR 码与条形码生成",
        ],
      },
      approach: {
        heading: "工作方式",
        items: [
          { title: "简单快速", body: "工具采用清晰的界面和简短的流程，便于快速完成任务。" },
          { title: "无需安装", body: "大多数工具都可以直接在浏览器中使用，无需下载或注册。" },
          { title: "浏览器内处理", body: "在可能的情况下，输入内容会在浏览器中直接处理。" },
        ],
      },
      whoItsFor: {
        heading: "适合哪些用户",
        items: [
          "处理文本和格式的学生",
          "检查 JSON、编码和技术数据的开发者",
          "处理颜色和视觉素材的设计师",
          "创建标签和 QR 码的小型企业",
          "寻找快速在线工具的普通用户",
        ],
      },
      whyWeBuilt: {
        heading: "我们为什么创建 Apps24",
        body: "许多在线工具要么过于零散，要么使用起来不够顺手。Apps24 专注于容易打开、容易使用的实用工具。",
      },
      goal: {
        heading: "当前目标",
        body: "我们正在持续整理可快速处理常见网页任务的工具。",
      },
      content: [
        "Apps24 是一个多语言在线工具网站，面向日常浏览器任务。",
        "我们提供轻量级工具，用于文本格式化、图像压缩、JSON 验证、密码生成、QR 码等。",
        "我们的目标是维护一个实用、易用的在线工具集合。",
      ],
    },
    privacy: {
      title: "隐私政策",
      content: [
        { section: "简介", body: "本政策说明您使用 Apps24 时我们如何处理数据。" },
        { section: "数据收集", body: "大多数工具都会在您的浏览器中本地处理数据，但某些功能在需要实时结果时可能会使用第三方服务。" },
        { section: "日志文件", body: "与其他网站一样，我们使用日志文件进行流量分析和维护，包括 IP 地址、浏览器类型和时间戳，这些信息不与个人身份信息关联。" },
        { section: "浏览器存储", body: "某些工具会使用 localStorage 等浏览器存储，在您的设备上本地保存偏好设置。" },
        { section: "第三方服务", body: "像 IP 查询这样的功能可能会使用外部提供商来显示网络和位置信息。" },
        { section: "联系", body: "如果您对本政策有疑问，请联系我们。" },
      ],
    },
    terms: {
      title: "服务条款",
      content: [
        { section: "条款接受", body: "通过访问 Apps24，您同意受本服务条款及所有适用法律法规的约束。" },
        { section: "使用许可", body: "本网站的工具供个人和商业使用提供。未经明确许可，您不得复制、修改、逆向工程或重新分发我们的代码。" },
        { section: "免责声明", body: "工具按“原样”提供。我们不保证其对所有用途都准确或适用。" },
        { section: "限制", body: "Apps24 对因使用或无法使用本网站工具而产生的损害概不负责。" },
      ],
    },
    contact: {
      title: "联系 Apps24",
      intro: "如果您有问题、错误报告或建议，请随时联系我们。",
      welcomeItems: [
        "工具错误或漏洞",
        "输出错误或格式问题",
        "功能建议",
        "语言或翻译改进",
        "商业咨询",
        "关于网站的一般反馈",
      ],
      emailHeading: "电子邮件支持",
      email: "support@apps24.io",
      reportDescription: "如果您要反映问题，请尽可能提供详细信息：",
      reportItems: [
        "工具名称",
        "页面 URL",
        "您使用的浏览器或设备",
        "问题的简短描述",
        "如有可能，请附截图",
      ],
      responseHeading: "回复时间",
      responseBody: "我们尽量尽快审查查询。回复可能需要一些时间。",
      suggestionsHeading: "建议与反馈",
      suggestionsBody: "如果您有改善可用性的想法或希望添加的工具，我们很乐意听取。",
      businessHeading: "商业与合作伙伴咨询",
      businessBody: "对于商业或合作伙伴咨询，请通过电子邮件联系我们，并附上清晰的主题行。",
      beforeContactHeading: "联系我们之前",
      beforeContactItems: ["关于我们", "隐私政策", "服务条款"],
      closing: "感谢您访问 Apps24。",
      content: "如有问题或建议，请通过 support@apps24.io 联系我们。",
    },
  },

  "zh-TW": {
    about: {
      title: "關於 Apps24",
      intro: "Apps24 是一個多語言線上工具網站，面向日常瀏覽器工作。我們把實用工具集中在一起，方便您無需安裝即可快速使用。頁面結構保持簡潔，方便快速找到工具並完成工作。",
      whatWeOffer: {
        heading: "我們提供的工具",
        items: [
          "文字格式化與轉換",
          "圖片壓縮與最佳化",
          "JSON 格式化與驗證",
          "密碼產生",
          "QR 碼與條碼產生",
          "單位轉換與快速計算",
        ],
      },
      approach: {
        heading: "運作方式",
        items: [
          { title: "簡單快速", body: "工具採用清楚的介面與簡短流程，方便快速完成任務。" },
          { title: "無需安裝", body: "大多數工具都可以直接在瀏覽器中使用，不需要下載或註冊。" },
          { title: "瀏覽器內處理", body: "在可行的情況下，輸入內容會直接在瀏覽器中處理。" },
          { title: "清楚的頁面結構", body: "每個頁面都維持相同的簡單結構：簡短介紹、實用分區，以及返回工具的清楚路徑。" },
        ],
      },
      whoItsFor: {
        heading: "適合哪些使用者",
        items: [
          "處理文字和格式的學生",
          "檢查 JSON、編碼與技術資料的開發者",
          "處理顏色與視覺素材的設計師",
          "建立標籤與 QR 碼的小型企業",
          "尋找快速線上工具的一般使用者",
          "需要快速轉換和檢查的使用者",
        ],
      },
      whyWeBuilt: {
        heading: "我們為什麼創建 Apps24",
        body: "許多線上工具要麼過於零散，要麼使用起來不夠順手。Apps24 專注於容易打開、容易使用的實用工具，並盡量保持頁面輕量、易讀。",
      },
      goal: {
        heading: "目前目標",
        body: "我們正在持續整理可快速處理常見網頁任務的工具，同時保持結構一致，讓新使用者也容易理解。",
      },
      content: [
        "Apps24 是一個多語言線上工具網站，面向日常瀏覽器工作。",
        "我們提供輕量級工具，用於文字格式化、圖片壓縮、JSON 驗證、密碼產生、QR 碼等。",
        "我們的目標是維持一個實用、易用的線上工具集合。",
      ],
    },
    privacy: {
      title: "隱私政策",
      content: [
        { section: "簡介", body: "Apps24 優先保護您的隱私。本政策概述了我們在您使用我們的服務時如何處理資料。" },
        { section: "資料收集", body: "大多數工具都會在您的瀏覽器中本機處理資料，但某些功能在需要即時結果時可能會向第三方服務請求少量資料。" },
        { section: "日誌檔案", body: "與其他網站一樣，我們使用日誌檔案進行流量分析和維護，包括 IP 位址、瀏覽器類型和時間戳，這些資訊不與個人身份資訊關聯。" },
        { section: "瀏覽器儲存", body: "某些工具會使用 localStorage 等瀏覽器儲存，在您的裝置上本地保存偏好設定。" },
        { section: "第三方服務", body: "像 IP 查詢這類功能可能會使用外部供應商來顯示網路與位置資訊。" },
        { section: "資料最小化", body: "我們只使用網站運作和處理支援請求所必需的資訊。" },
        { section: "政策更新", body: "如果本政策有變更，我們會更新此頁面，讓您始終可以查看最新版本。" },
        { section: "聯絡", body: "如果您對我們的隱私慣例有疑問，請聯絡我們。" },
      ],
    },
    terms: {
      title: "服務條款",
      content: [
        { section: "條款接受", body: "透過存取 Apps24，您同意受本服務條款及所有適用法律法規的約束。" },
        { section: "使用授權", body: "本網站的工具供個人和商業使用提供。未經明確許可，您不得修改、逆向工程或重新散布我們的程式碼。" },
        { section: "免責聲明", body: "Apps24 的資料按「原樣」提供。我們不對工具的準確性或可靠性作任何保證。" },
        { section: "合理使用", body: "請以合法且合理的方式使用工具，避免任何可能干擾網站或其他使用者的行為。" },
        { section: "使用者責任", body: "在工作、發布或其他重要用途之前，請先自行檢查結果。" },
        { section: "服務變更", body: "隨著網站發展，我們可能會改進、替換或移除部分工具。" },
        { section: "限制", body: "Apps24 對因使用或無法使用本網站工具而產生的任何損害概不負責。" },
      ],
    },
    contact: {
      title: "聯絡 Apps24",
      intro: "如果您有問題、錯誤回報或建議，請隨時聯絡我們。",
      welcomeItems: [
        "工具錯誤或漏洞",
        "輸出錯誤或格式問題",
        "功能建議",
        "語言或翻譯改進",
        "商業諮詢",
        "關於網站的一般回饋",
        "受影響的頁面",
        "重現步驟",
        "預期結果與實際結果",
      ],
      emailHeading: "電子郵件支援",
      email: "support@apps24.io",
      reportDescription: "如果您要回報問題，請盡可能提供詳細資訊：",
      reportItems: [
        "工具名稱",
        "頁面 URL",
        "您使用的瀏覽器或裝置",
        "問題的簡短描述",
        "如有可能，請附截圖",
        "預期結果",
        "實際結果",
      ],
      responseHeading: "回覆時間",
      responseBody: "我們盡量盡快審查查詢。回覆時間會因請求類型而異。",
      suggestionsHeading: "建議與回饋",
      suggestionsBody: "我們正在不斷改進 Apps24 並新增新工具。如果您希望在網站上看到某個工具，或者有改善可用性的想法，我們很樂意聽取。",
      businessHeading: "商業與合作夥伴諮詢",
      businessBody: "對於商業相關溝通、合作夥伴討論或網站相關提案，請透過電子郵件聯絡我們，並附上清晰的主旨和簡短說明，以便我們更有效地審查您的請求。",
      beforeContactHeading: "聯絡我們之前",
      beforeContactItems: ["關於我們", "隱私政策", "服務條款"],
      closing: "感謝您訪問 Apps24。",
      content: "如有問題或建議，請透過 support@apps24.io 聯絡我們。",
    },
  },

  pt: {
    about: {
      title: "Sobre o Apps24",
      intro: "O Apps24 é um site de ferramentas online multilíngue para tarefas do dia a dia no navegador. Reunimos utilitários práticos que podem ser abertos e usados rapidamente, sem instalação. As páginas são mantidas simples para facilitar a busca pela ferramenta certa e a execução da tarefa.",
      whatWeOffer: {
        heading: "O que oferecemos",
        items: [
          "Formatação e conversão de texto",
          "Compressão e otimização de imagens",
          "Formatação e validação de JSON",
          "Geração de senhas",
          "Geração de códigos QR e de barras",
          "Conversão de unidades e cálculos rápidos",
        ],
      },
      approach: {
        heading: "Como funciona",
        items: [
          { title: "Simples e rápido", body: "As ferramentas são feitas para abrir rápido e seguir um fluxo curto e claro." },
          { title: "Sem instalação", body: "A maioria das ferramentas pode ser usada diretamente no navegador, sem download ou cadastro." },
          { title: "Processamento no navegador", body: "Quando possível, os dados são processados localmente no navegador." },
          { title: "Estrutura de página clara", body: "Cada página segue o mesmo padrão simples: introdução curta, seções úteis e um caminho fácil de volta às ferramentas." },
        ],
      },
      whoItsFor: {
        heading: "Para quem serve",
        items: [
          "Estudantes que trabalham com texto e formatação",
          "Desenvolvedores que verificam JSON, codificação e dados técnicos",
          "Designers que lidam com cores e materiais visuais",
          "Pequenas empresas que criam etiquetas e códigos QR",
          "Usuários que procuram ferramentas online rápidas",
          "Usuários que precisam de conversões e verificações rápidas",
        ],
      },
      whyWeBuilt: {
        heading: "Por que criamos",
        body: "Muitas ferramentas online são complicadas ou espalhadas demais. O Apps24 foca em utilitários práticos, fáceis de abrir e usar, com páginas leves e fáceis de ler.",
      },
      goal: {
        heading: "O que estamos construindo",
        body: "Continuamos adicionando ferramentas úteis para resolver tarefas comuns de forma simples. Também mantemos uma estrutura consistente para o site continuar fácil de entender.",
      },
      content: [
        "O Apps24 é um site de ferramentas online multilíngue para tarefas do dia a dia no navegador.",
        "Oferecemos ferramentas leves para formatação de texto, compressão de imagens, validação de JSON, geração de senhas, códigos QR e mais.",
        "Nosso objetivo é manter uma biblioteca prática de ferramentas fáceis de usar.",
      ],
    },
    privacy: {
      title: "Política de Privacidade",
      content: [
        { section: "Introdução", body: "Esta política explica como o Apps24 trata os dados quando você usa o site." },
        { section: "Coleta de dados", body: "A maioria das ferramentas processa os dados localmente no seu navegador. Alguns recursos podem usar serviços de terceiros quando resultados em tempo real forem necessários." },
        { section: "Arquivos de log", body: "Como outros sites, usamos arquivos de log para análise de tráfego e manutenção. Isso inclui endereços IP, tipos de navegadores e carimbos de data/hora, que não estão vinculados a informações pessoalmente identificáveis." },
        { section: "Armazenamento do navegador", body: "Algumas ferramentas salvam preferências localmente no seu dispositivo usando armazenamento do navegador, como localStorage." },
        { section: "Serviços de terceiros", body: "Recursos como a consulta de IP podem usar provedores externos para exibir detalhes de rede e localização." },
        { section: "Minimização de dados", body: "Usamos apenas as informações necessárias para operar o site e responder às solicitações de suporte." },
        { section: "Atualizações da política", body: "Se esta política mudar, atualizaremos esta página para que a versão atual esteja sempre disponível aqui." },
        { section: "Contato", body: "Se você tiver perguntas sobre esta política, entre em contato conosco." },
      ],
    },
    terms: {
      title: "Termos de Serviço",
      content: [
        { section: "Aceitação dos termos", body: "Ao acessar o Apps24, você concorda em se sujeitar a estes termos de serviço e a todas as leis e regulamentos aplicáveis." },
        { section: "Licença de uso", body: "As ferramentas deste site são fornecidas para uso pessoal e comercial. Você não pode copiar, modificar, fazer engenharia reversa ou redistribuir nosso código sem permissão." },
        { section: "Isenção de responsabilidade", body: "As ferramentas são fornecidas 'como estão'. Não garantimos precisão ou adequação para todos os casos de uso." },
        { section: "Uso aceitável", body: "Use as ferramentas de forma legal e razoável e evite ações que possam prejudicar o site ou outros usuários." },
        { section: "Responsabilidade do usuário", body: "Antes de usar resultados em trabalho, publicação ou outras finalidades importantes, revise a saída cuidadosamente." },
        { section: "Mudanças no serviço", body: "Podemos melhorar, substituir ou remover ferramentas ao longo do tempo conforme o site evolui." },
        { section: "Limitações", body: "O Apps24 não será responsável por quaisquer danos decorrentes do uso ou da impossibilidade de usar as ferramentas do site." },
      ],
    },
    contact: {
      title: "Contato Apps24",
      intro: "Se você tiver perguntas, relatórios de erro ou sugestões, sinta-se à vontade para nos contatar.",
      welcomeItems: [
        "Erros ou bugs nas ferramentas",
        "Saída incorreta ou problemas de formatação",
        "Sugestões de recursos",
        "Melhorias de idioma ou tradução",
        "Consultas comerciais",
        "Feedback geral sobre o site",
        "Páginas afetadas",
        "Etapas para reproduzir",
        "Resultado esperado e resultado real",
      ],
      emailHeading: "Suporte por e-mail",
      email: "support@apps24.io",
      reportDescription: "Se você está reportando um problema, inclua o máximo de detalhes possíveis:",
      reportItems: [
        "O nome da ferramenta",
        "A URL da página",
        "O navegador ou dispositivo que você usou",
        "Uma breve descrição do problema",
        "Uma captura de tela, se disponível",
        "O resultado esperado",
        "O resultado real",
      ],
      responseHeading: "Tempo de resposta",
      responseBody: "Procuramos revisar as consultas o mais rápido possível. O tempo de resposta pode variar de acordo com o tipo de solicitação.",
      suggestionsHeading: "Sugestões e feedback",
      suggestionsBody: "Se você tiver ideias para melhorar a usabilidade ou ferramentas que gostaria de ver no site, ficamos felizes em ouvi-lo.",
      businessHeading: "Consultas comerciais e de parceria",
      businessBody: "Para consultas comerciais ou de parceria, entre em contato por e-mail com um assunto claro e um breve resumo.",
      beforeContactHeading: "Antes de nos contatar",
      beforeContactItems: ["Sobre nós", "Política de Privacidade", "Termos de Serviço"],
      closing: "Obrigado por visitar o Apps24.",
      content: "Se tiver perguntas ou sugestões, entre em contato conosco em support@apps24.io.",
    },
  },

  es: {
    about: {
      title: "Acerca de Apps24",
      intro: "Apps24 es un sitio web de herramientas en línea multilingüe para tareas cotidianas en el navegador. Reunimos utilidades prácticas que se pueden abrir y usar rápido, sin instalación. Las páginas se mantienen simples para encontrar la herramienta correcta y completar la tarea sin pasos innecesarios.",
      whatWeOffer: {
        heading: "Lo que ofrecemos",
        items: [
          "Formato y conversión de texto",
          "Compresión y optimización de imágenes",
          "Formato y validación de JSON",
          "Generación de contraseñas",
          "Generación de códigos QR y de barras",
          "Conversión de unidades y cálculos rápidos",
        ],
      },
      approach: {
        heading: "Cómo funciona",
        items: [
          { title: "Simple y rápido", body: "Las herramientas están hechas para abrir rápido y seguir un flujo corto y claro." },
          { title: "Sin instalación", body: "La mayoría de las herramientas se pueden usar directamente en el navegador, sin descarga ni registro." },
          { title: "Procesamiento en el navegador", body: "Cuando es posible, los datos se procesan localmente en el navegador." },
          { title: "Estructura clara de página", body: "Cada página sigue el mismo patrón simple: una introducción breve, secciones útiles y un camino fácil para volver a las herramientas." },
        ],
      },
      whoItsFor: {
        heading: "Para quién sirve",
        items: [
          "Estudiantes que trabajan con texto y formato",
          "Desarrolladores que verifican JSON, codificación y datos técnicos",
          "Diseñadores que manejan colores y materiales visuales",
          "Pequeñas empresas que crean etiquetas y códigos QR",
          "Usuarios que buscan herramientas en línea rápidas",
          "Usuarios que necesitan conversiones y comprobaciones rápidas",
        ],
      },
      whyWeBuilt: {
        heading: "Por qué lo creamos",
        body: "Muchas herramientas en línea son complicadas o están demasiado dispersas. Apps24 se centra en utilidades prácticas, fáciles de abrir y usar, con páginas ligeras y fáciles de leer.",
      },
      goal: {
        heading: "Lo que estamos construyendo",
        body: "Seguimos agregando herramientas útiles para resolver tareas comunes de forma simple. También mantenemos una estructura coherente para que el sitio siga siendo fácil de entender.",
      },
      content: [
        "Apps24 es un sitio web de herramientas en línea multilingüe para tareas cotidianas en el navegador.",
        "Ofrecemos herramientas ligeras para formato de texto, compresión de imágenes, validación de JSON, generación de contraseñas, códigos QR y más.",
        "Nuestro objetivo es mantener una biblioteca práctica de herramientas fáciles de usar.",
      ],
    },
    privacy: {
      title: "Política de Privacidad",
      content: [
        { section: "Introducción", body: "Esta política explica cómo Apps24 maneja los datos cuando usa el sitio." },
        { section: "Recopilación de datos", body: "La mayoría de las herramientas procesa los datos localmente en su navegador. Algunas funciones pueden usar servicios de terceros cuando se necesitan resultados en vivo." },
        { section: "Archivos de registro", body: "Como otros sitios web, usamos archivos de registro para análisis de tráfico y mantenimiento. Esto incluye direcciones IP, tipos de navegadores y marcas de tiempo, que no están vinculadas a información de identificación personal." },
        { section: "Almacenamiento del navegador", body: "Algunas herramientas guardan preferencias localmente en su dispositivo usando el almacenamiento del navegador, como localStorage." },
        { section: "Servicios de terceros", body: "Funciones como la búsqueda de IP pueden usar proveedores externos para mostrar detalles de red y ubicación." },
        { section: "Minimización de datos", body: "Solo usamos la información necesaria para operar el sitio y responder a las solicitudes de soporte." },
        { section: "Actualizaciones de la política", body: "Si esta política cambia, actualizaremos esta página para que la versión actual esté siempre disponible aquí." },
        { section: "Contacto", body: "Si tiene preguntas sobre esta política, contáctenos." },
      ],
    },
    terms: {
      title: "Términos de Servicio",
      content: [
        { section: "Aceptación de términos", body: "Al acceder a Apps24, acepta regirse por estos términos de servicio y todas las leyes y regulaciones aplicables." },
        { section: "Licencia de uso", body: "Las herramientas de este sitio se proporcionan para uso personal y comercial. No puede copiar, modificar, aplicar ingeniería inversa ni redistribuir nuestro código sin permiso." },
        { section: "Aviso legal", body: "Las herramientas se proporcionan 'tal cual'. No garantizamos precisión ni adecuación para todos los casos de uso." },
        { section: "Uso aceptable", body: "Use las herramientas de forma legal y razonable, y evite acciones que puedan perjudicar el sitio o a otros usuarios." },
        { section: "Responsabilidad del usuario", body: "Antes de usar resultados en el trabajo, la publicación u otros usos importantes, revise la salida cuidadosamente." },
        { section: "Cambios en el servicio", body: "Podemos mejorar, reemplazar o eliminar herramientas con el tiempo a medida que evoluciona el sitio." },
        { section: "Limitaciones", body: "Apps24 no será responsable de daños que surjan por el uso o la imposibilidad de usar las herramientas del sitio." },
      ],
    },
    contact: {
      title: "Contactar Apps24",
      intro: "Si tiene preguntas, informes de errores o sugerencias, no dude en contactarnos.",
      welcomeItems: [
        "Errores o fallos en las herramientas",
        "Resultados incorrectos o problemas de formato",
        "Sugerencias de funciones",
        "Mejoras de idioma o traducción",
        "Consultas comerciales",
        "Comentarios generales sobre el sitio web",
        "Páginas afectadas",
        "Pasos para reproducir",
        "Resultado esperado y resultado real",
      ],
      emailHeading: "Soporte por correo electrónico",
      email: "support@apps24.io",
      reportDescription: "Si está reportando un problema, incluya la mayor cantidad de detalles posible:",
      reportItems: [
        "El nombre de la herramienta",
        "La URL de la página",
        "El navegador o dispositivo que utilizó",
        "Una breve descripción del problema",
        "Una captura de pantalla si está disponible",
        "El resultado esperado",
        "El resultado real",
      ],
      responseHeading: "Tiempo de respuesta",
      responseBody: "Intentamos revisar las consultas lo más rápido posible. El tiempo de respuesta puede variar según el tipo de solicitud.",
      suggestionsHeading: "Sugerencias y comentarios",
      suggestionsBody: "Si tiene ideas para mejorar la usabilidad o herramientas que le gustaría ver en el sitio, nos complacería escucharle.",
      businessHeading: "Consultas comerciales y de asociación",
      businessBody: "Para consultas comerciales o de asociación, contáctenos por correo electrónico con una línea de asunto clara y un breve resumen.",
      beforeContactHeading: "Antes de contactarnos",
      beforeContactItems: ["Sobre nosotros", "Política de Privacidad", "Términos de Servicio"],
      closing: "Gracias por visitar Apps24.",
      content: "Si tiene preguntas o sugerencias, contáctenos en support@apps24.io.",
    },
  },

  de: {
    about: {
      title: "Über Apps24",
      intro: "Apps24 ist eine mehrsprachige Website mit Online-Tools für alltägliche Aufgaben im Browser. Wir bündeln praktische Werkzeuge, die sich ohne Installation schnell öffnen und nutzen lassen. Die Seiten sind bewusst schlank gehalten, damit Sie ein Tool schnell finden und die Aufgabe direkt erledigen können.",
      whatWeOffer: {
        heading: "Was wir anbieten",
        items: [
          "Textformatierung und -konvertierung",
          "Bildkomprimierung und -optimierung",
          "JSON-Formatierung und -Validierung",
          "Passwortgenerierung",
          "QR-Code- und Barcode-Generierung",
          "Einheitenumrechnung und schnelle Berechnungen",
        ],
      },
      approach: {
        heading: "So funktioniert es",
        items: [
          { title: "Einfach und schnell", body: "Die Tools sind so aufgebaut, dass sie schnell laden und in einem kurzen, klaren Ablauf funktionieren." },
          { title: "Keine Installation", body: "Die meisten Tools lassen sich direkt im Browser ohne Download oder Registrierung verwenden." },
          { title: "Browserseitige Verarbeitung", body: "Wenn möglich, werden Eingaben direkt im Browser verarbeitet." },
          { title: "Klare Seitenstruktur", body: "Jede Seite folgt demselben einfachen Muster: kurze Einführung, nützliche Abschnitte und ein leichter Weg zurück zu den Tools." },
        ],
      },
      whoItsFor: {
        heading: "Für wen es gedacht ist",
        items: [
          "Studenten, die mit Text und Formatierung arbeiten",
          "Entwickler, die JSON, Kodierung und technische Daten prüfen",
          "Designer, die Farben und visuelle Materialien verwalten",
          "Kleine Unternehmen, die Etiketten und QR-Codes erstellen",
          "Allgemeine Nutzer, die schnelle Online-Tools suchen",
          "Nutzer, die schnelle Umrechnungen und Prüfungen benötigen",
        ],
      },
      whyWeBuilt: {
        heading: "Warum wir es gebaut haben",
        body: "Viele Online-Tools sind zu kompliziert oder zu verstreut. Apps24 konzentriert sich auf praktische Werkzeuge, die sich leicht öffnen und nutzen lassen, mit schlanken und gut lesbaren Seiten.",
      },
      goal: {
        heading: "Was wir aufbauen",
        body: "Wir fügen weiterhin nützliche Web-Tools hinzu, die häufige Aufgaben einfach lösen. Gleichzeitig halten wir die Struktur konsistent, damit die Website leicht verständlich bleibt.",
      },
      content: [
        "Apps24 ist eine mehrsprachige Website mit Online-Tools für alltägliche Aufgaben im Browser.",
        "Wir bieten leichtgewichtige Werkzeuge für Textformatierung, Bildkomprimierung, JSON-Validierung, Passwortgenerierung, QR-Codes und mehr.",
        "Unser Ziel ist es, eine praktische Bibliothek leicht nutzbarer Tools zu pflegen.",
      ],
    },
    privacy: {
      title: "Datenschutzrichtlinie",
      content: [
        { section: "Einführung", body: "Diese Richtlinie erklärt, wie Apps24 Daten behandelt, wenn Sie die Website nutzen." },
        { section: "Datenerfassung", body: "Die meisten Tools verarbeiten Daten lokal in Ihrem Browser. Einige Funktionen können bei Bedarf Drittanbieterdienste für Live-Ergebnisse nutzen." },
        { section: "Log-Dateien", body: "Wie andere Websites verwenden wir Log-Dateien für Verkehrsanalyse und Wartung. Dies umfasst IP-Adressen, Browsertypen und Zeitstempel, die nicht mit persönlich identifizierbaren Informationen verknüpft sind." },
        { section: "Browser-Speicher", body: "Einige Tools speichern Einstellungen lokal auf Ihrem Gerät mithilfe von Browser-Speicher wie localStorage." },
        { section: "Drittanbieter-Dienste", body: "Funktionen wie die IP-Suche können externe Anbieter verwenden, um Netzwerk- und Standortdetails anzuzeigen." },
        { section: "Datenminimierung", body: "Wir verwenden nur die Informationen, die für den Betrieb der Website und die Bearbeitung von Support-Anfragen erforderlich sind." },
        { section: "Aktualisierungen der Richtlinie", body: "Wenn sich diese Richtlinie ändert, aktualisieren wir diese Seite, damit hier immer die aktuelle Version verfügbar ist." },
        { section: "Kontakt", body: "Wenn Sie Fragen zu dieser Richtlinie haben, kontaktieren Sie uns bitte." },
      ],
    },
    terms: {
      title: "Nutzungsbedingungen",
      content: [
        { section: "Annahme der Bedingungen", body: "Durch den Zugriff auf Apps24 stimmen Sie zu, an diese Nutzungsbedingungen und alle geltenden Gesetze und Vorschriften gebunden zu sein." },
        { section: "Nutzungslizenz", body: "Die Tools auf dieser Website werden für den persönlichen und kommerziellen Gebrauch bereitgestellt. Sie dürfen unseren Code ohne ausdrückliche Genehmigung nicht kopieren, modifizieren, zurückentwickeln oder weiterverteilen." },
        { section: "Haftungsausschluss", body: "Die Tools werden 'wie besehen' bereitgestellt. Wir garantieren nicht, dass sie für jeden Anwendungsfall genau oder geeignet sind." },
        { section: "Zulässige Nutzung", body: "Bitte nutzen Sie die Tools auf rechtmäßige und vernünftige Weise und vermeiden Sie Aktionen, die die Website oder andere Nutzer beeinträchtigen könnten." },
        { section: "Verantwortung des Nutzers", body: "Bitte prüfen Sie Ergebnisse vor der Nutzung in Arbeit, Veröffentlichung oder anderen wichtigen Anwendungsfällen." },
        { section: "Änderungen am Dienst", body: "Wir können Tools im Laufe der Zeit verbessern, ersetzen oder entfernen, während sich die Website weiterentwickelt." },
        { section: "Einschränkungen", body: "Apps24 ist nicht für Schäden verantwortlich, die aus der Nutzung oder der Unfähigkeit entstehen, die Tools auf der Website zu nutzen." },
      ],
    },
    contact: {
      title: "Apps24 kontaktieren",
      intro: "Wenn Sie Fragen, Fehlerberichte oder Vorschläge haben, zögern Sie nicht, uns zu kontaktieren.",
      welcomeItems: [
        "Tool-Fehler oder Bugs",
        "Falsche Ausgabe oder Formatierungsprobleme",
        "Funktionsvorschläge",
        "Sprach- oder Übersetzungsverbesserungen",
        "Geschäftliche Anfragen",
        "Allgemeines Feedback zur Website",
        "Betroffene Seiten",
        "Schritte zum Reproduzieren",
        "Erwartetes und tatsächliches Ergebnis",
      ],
      emailHeading: "E-Mail-Support",
      email: "support@apps24.io",
      reportDescription: "Wenn Sie ein Problem melden, geben Sie bitte so viele Details wie möglich an:",
      reportItems: [
        "Der Tool-Name",
        "Die Seiten-URL",
        "Der verwendete Browser oder das verwendete Gerät",
        "Eine kurze Beschreibung des Problems",
        "Ein Screenshot, falls verfügbar",
        "Das erwartete Ergebnis",
        "Das tatsächliche Ergebnis",
      ],
      responseHeading: "Antwortzeit",
      responseBody: "Wir bemühen uns, Anfragen so schnell wie möglich zu bearbeiten. Die Antwortzeit kann je nach Anfrageart variieren.",
      suggestionsHeading: "Vorschläge und Feedback",
      suggestionsBody: "Wenn Sie Ideen zur Verbesserung der Benutzerfreundlichkeit oder Vorschläge für neue Tools haben, hören wir Sie gerne.",
      businessHeading: "Geschäftliche und Partnerschaftsanfragen",
      businessBody: "Für geschäftliche oder Partnerschaftsanfragen kontaktieren Sie uns bitte per E-Mail mit einer klaren Betreffzeile und einer kurzen Zusammenfassung.",
      beforeContactHeading: "Bevor Sie uns kontaktieren",
      beforeContactItems: ["Über uns", "Datenschutzrichtlinie", "Nutzungsbedingungen"],
      closing: "Vielen Dank für Ihren Besuch bei Apps24.",
      content: "Wenn Sie Fragen oder Vorschläge haben, kontaktieren Sie uns unter support@apps24.io.",
    },
  },

  ar: {
    about: {
      title: "حول Apps24",
      intro: "Apps24 هو موقع أدوات إلكترونية متعدد اللغات للمهام اليومية داخل المتصفح. نجمع أدوات عملية يمكن فتحها واستخدامها بسرعة من دون تثبيت. كما نحافظ على صفحات قصيرة وواضحة لتسهيل العثور على الأداة المناسبة وإنجاز المهمة مباشرة.",
      whatWeOffer: {
        heading: "ما نقدمه",
        items: [
          "تنسيق النصوص وتحويلها",
          "ضغط الصور وتحسينها",
          "تنسيق JSON والتحقق منه",
          "توليد كلمات المرور",
          "توليد رموز QR والباركود",
          "تحويل الوحدات والحسابات السريعة",
        ],
      },
      approach: {
        heading: "كيف يعمل",
        items: [
          { title: "بسيط وسريع", body: "صُممت الأدوات لتفتح بسرعة وتعمل عبر خطوات قصيرة وواضحة." },
          { title: "من دون تثبيت", body: "يمكن استخدام معظم الأدوات مباشرة في المتصفح من دون تنزيل أو تسجيل." },
          { title: "المعالجة داخل المتصفح", body: "عند الإمكان، تتم معالجة الإدخال محلياً داخل المتصفح." },
          { title: "بنية صفحة واضحة", body: "كل صفحة تتبع النمط نفسه: مقدمة قصيرة، أقسام مفيدة، وطريق سهل للعودة إلى الأدوات." },
        ],
      },
      whoItsFor: {
        heading: "لمن هو مخصص",
        items: [
          "الطلاب الذين يعملون مع النصوص والتنسيق",
          "المطورون الذين يتحققون من JSON والترميز والبيانات التقنية",
          "المصممون الذين يتعاملون مع الألوان والمواد المرئية",
          "الشركات الصغيرة التي تنشئ الملصقات ورموز QR",
          "المستخدمون الباحثون عن أدوات سريعة عبر الإنترنت",
          "المستخدمون الذين يحتاجون إلى تحويلات وفحوصات سريعة",
        ],
      },
      whyWeBuilt: {
        heading: "لماذا أنشأناه",
        body: "أدوات كثيرة على الإنترنت معقدة أو موزعة بشكل غير عملي. يركز Apps24 على أدوات عملية يسهل فتحها واستخدامها، مع صفحات خفيفة وسهلة القراءة.",
      },
      goal: {
        heading: "ما الذي نبنيه",
        body: "نواصل إضافة أدوات ويب مفيدة تحل المهام الشائعة بطريقة بسيطة. كما نحافظ على بنية ثابتة حتى يبقى الموقع واضحاً وسهل الفهم.",
      },
      content: [
        "Apps24 هو موقع أدوات إلكترونية متعدد اللغات للمهام اليومية داخل المتصفح.",
        "نقدم أدوات خفيفة لتنسيق النصوص وضغط الصور والتحقق من JSON وتوليد كلمات المرور ورموز QR والمزيد.",
        "هدفنا هو الحفاظ على مكتبة عملية من الأدوات سهلة الاستخدام.",
      ],
    },
    privacy: {
      title: "سياسة الخصوصية",
      content: [
        { section: "مقدمة", body: "توضح هذه السياسة كيفية تعامل Apps24 مع البيانات عند استخدام الموقع." },
        { section: "جمع البيانات", body: "تتم معالجة معظم الأدوات محليًا داخل متصفحك. قد تستخدم بعض الميزات خدمات خارجية عند الحاجة إلى نتائج مباشرة." },
        { section: "ملفات السجل", body: "مثل المواقع الأخرى، نستخدم ملفات السجل لتحليل حركة المرور والصيانة. يشمل ذلك عناوين IP وأنواع المتصفحات والطوابع الزمنية، وهي ليست مرتبطة بمعلومات تعريف شخصية." },
        { section: "تخزين المتصفح", body: "تقوم بعض الأدوات بحفظ التفضيلات محليًا على جهازك باستخدام تخزين المتصفح مثل localStorage." },
        { section: "خدمات الطرف الثالث", body: "قد تستخدم ميزات مثل البحث عن عنوان IP مزودين خارجيين لعرض تفاصيل الشبكة والموقع." },
        { section: "تقليل البيانات", body: "نستخدم فقط المعلومات اللازمة لتشغيل الموقع والتعامل مع طلبات الدعم." },
        { section: "تحديثات السياسة", body: "إذا تغيرت هذه السياسة، سنقوم بتحديث هذه الصفحة حتى تبقى النسخة الحالية متاحة هنا دائماً." },
        { section: "التواصل", body: "إذا كانت لديك أسئلة حول هذه السياسة، يرجى التواصل معنا." },
      ],
    },
    terms: {
      title: "شروط الخدمة",
      content: [
        { section: "قبول الشروط", body: "بالوصول إلى Apps24، فإنك توافق على الالتزام بشروط الخدمة هذه وجميع القوانين واللوائح المعمول بها." },
        { section: "ترخيص الاستخدام", body: "تُقدَّم الأدوات الموجودة على هذا الموقع للاستخدام الشخصي والتجاري. لا يجوز نسخ كودنا أو تعديله أو إجراء هندسة عكسية عليه أو إعادة توزيعه دون إذن صريح." },
        { section: "إخلاء المسؤولية", body: "تُقدَّم الأدوات 'كما هي'. لا نضمن الدقة أو الملاءمة لكل حالة استخدام." },
        { section: "الاستخدام المقبول", body: "يرجى استخدام الأدوات بطريقة قانونية ومعقولة، وتجنب أي تصرف قد يضر بالموقع أو بالمستخدمين الآخرين." },
        { section: "مسؤولية المستخدم", body: "يرجى مراجعة النتائج قبل استخدامها في العمل أو النشر أو أي استخدام مهم آخر." },
        { section: "تغييرات الخدمة", body: "قد نقوم بتحسين الأدوات أو استبدالها أو إزالتها مع مرور الوقت مع تطور الموقع." },
        { section: "القيود", body: "لن تكون Apps24 مسؤولة عن الأضرار الناجمة عن استخدام أو عدم القدرة على استخدام الأدوات الموجودة على الموقع." },
      ],
    },
    contact: {
      title: "التواصل مع Apps24",
      intro: "إذا كانت لديك أسئلة أو بلاغات عن أخطاء أو اقتراحات، فلا تتردد في التواصل معنا.",
      welcomeItems: [
        "أخطاء أو مشكلات في الأدوات",
        "مخرجات غير صحيحة أو مشكلات في التنسيق",
        "اقتراحات ميزات",
        "تحسينات لغوية أو في الترجمة",
        "استفسارات تجارية",
        "تعليقات عامة حول الموقع",
        "الصفحات المتأثرة",
        "خطوات إعادة المشكلة",
        "النتيجة المتوقعة والنتيجة الفعلية",
      ],
      emailHeading: "الدعم عبر البريد الإلكتروني",
      email: "support@apps24.io",
      reportDescription: "إذا كنت تبلغ عن مشكلة، يُرجى تضمين أكبر قدر من التفاصيل:",
      reportItems: [
        "اسم الأداة",
        "رابط الصفحة",
        "المتصفح أو الجهاز المستخدم",
        "وصف مختصر للمشكلة",
        "لقطة شاشة إن أمكن",
        "النتيجة المتوقعة",
        "النتيجة الفعلية",
      ],
      responseHeading: "وقت الاستجابة",
      responseBody: "نسعى إلى مراجعة الاستفسارات في أسرع وقت ممكن. قد يختلف وقت الرد بحسب نوع الطلب.",
      suggestionsHeading: "الاقتراحات والتعليقات",
      suggestionsBody: "إذا كانت لديك أفكار لتحسين سهولة الاستخدام أو أدوات تودّ رؤيتها على الموقع، فسنكون سعداء بسماعك.",
      businessHeading: "استفسارات الأعمال والشراكات",
      businessBody: "للاستفسارات المتعلقة بالأعمال أو الشراكات، يُرجى التواصل معنا عبر البريد الإلكتروني مع سطر موضوع واضح وملخص قصير.",
      beforeContactHeading: "قبل التواصل معنا",
      beforeContactItems: ["من نحن", "سياسة الخصوصية", "شروط الخدمة"],
      closing: "شكراً لزيارتك Apps24.",
      content: "إذا كانت لديك أسئلة أو اقتراحات، يُرجى التواصل معنا عبر support@apps24.io.",
    },
  },
};
