import { LOCALES, type Locale } from "@/lib/site";
import type { ToolDefinition } from "@/features/tools/types";

export const TOOLS: ToolDefinition[] = [
  {
    id: "ruler",
    slug: "ruler",
    category: "measurement",
    titleKey: "tools.ruler.title",
    descriptionKey: "tools.ruler.description",
    keywords: ["online ruler", "mm ruler", "inch ruler", "screen ruler"],
    accentColor: "#6366f1",
    icon: "R",
    order: 1,
    featured: true,
    status: "stable",
    locales: [...LOCALES],
    implementationKey: "ruler",
  },
  {
    id: "wordcounter",
    slug: "wordcounter",
    category: "text",
    titleKey: "tools.wordcounter.title",
    descriptionKey: "tools.wordcounter.description",
    keywords: ["word count", "character count", "text analyzer"],
    accentColor: "#3b82f6",
    icon: "WC",
    order: 2,
    featured: true,
    status: "stable",
    locales: [...LOCALES],
    implementationKey: "wordCounter",
  },
  {
    id: "countdown",
    slug: "countdown",
    category: "time",
    titleKey: "tools.countdown.title",
    descriptionKey: "tools.countdown.description",
    keywords: ["countdown timer", "timer online", "online alarm"],
    accentColor: "#8b5cf6",
    icon: "CT",
    order: 3,
    featured: true,
    status: "stable",
    locales: [...LOCALES],
    implementationKey: "countdown",
  },
  {
    id: "digitalclock",
    slug: "digitalclock",
    category: "time",
    titleKey: "tools.digitalclock.title",
    descriptionKey: "tools.digitalclock.description",
    keywords: ["digital clock", "online clock", "current time"],
    accentColor: "#6366f1",
    icon: "CLK",
    order: 4,
    featured: true,
    status: "stable",
    locales: [...LOCALES],
    implementationKey: "digitalClock",
  },
  {
    id: "screenlamp",
    slug: "screenlamp",
    category: "display",
    titleKey: "tools.screenlamp.title",
    descriptionKey: "tools.screenlamp.description",
    keywords: ["screen lamp", "white screen", "brightness test"],
    accentColor: "#f59e0b",
    icon: "SL",
    order: 5,
    featured: true,
    status: "stable",
    locales: [...LOCALES],
    implementationKey: "screenLamp",
  },
  {
    id: "qrgenerator",
    slug: "qrgenerator",
    category: "generator",
    titleKey: "tools.qrgenerator.title",
    descriptionKey: "tools.qrgenerator.description",
    keywords: ["qr code generator", "create qr code", "free qr code"],
    accentColor: "#10b981",
    icon: "QR",
    order: 6,
    featured: true,
    status: "stable",
    locales: [...LOCALES],
    implementationKey: "barcodeGenerator",
  },
  {
    id: "barcodegenerator",
    slug: "barcodegenerator",
    category: "generator",
    titleKey: "tools.barcodegenerator.title",
    descriptionKey: "tools.barcodegenerator.description",
    keywords: ["barcode generator", "code128", "create barcode"],
    accentColor: "#10b981",
    icon: "BC",
    order: 7,
    featured: true,
    status: "stable",
    locales: [...LOCALES],
    implementationKey: "barcodeGenerator",
  },
  {
    id: "dummytext",
    slug: "dummytext",
    category: "utility",
    titleKey: "tools.dummytext.title",
    descriptionKey: "tools.dummytext.description",
    keywords: ["lorem ipsum", "dummy text", "korean lorem ipsum"],
    accentColor: "#64748b",
    icon: "TXT",
    order: 8,
    featured: true,
    status: "stable",
    locales: [...LOCALES],
    implementationKey: "dummyText",
  },
  {
    id: "imagecompressor",
    slug: "image-compressor",
    category: "image",
    titleKey: "tools.imagecompressor.title",
    descriptionKey: "tools.imagecompressor.description",
    keywords: ["image compressor", "webp converter", "compress image online"],
    accentColor: "#ec4899",
    icon: "IMG",
    order: 9,
    featured: true,
    status: "stable",
    locales: [...LOCALES],
    implementationKey: "imageCompressor",
  },
  {
    id: "caseconverter",
    slug: "case-converter",
    category: "text",
    titleKey: "tools.caseconverter.title",
    descriptionKey: "tools.caseconverter.description",
    keywords: ["case converter", "uppercase", "lowercase", "title case"],
    accentColor: "#06b6d4",
    icon: "Aa",
    order: 10,
    featured: true,
    status: "stable",
    locales: [...LOCALES],
    implementationKey: "caseConverter",
  },
  {
    id: "jsonformatter",
    slug: "json-formatter",
    category: "utility",
    titleKey: "tools.jsonformatter.title",
    descriptionKey: "tools.jsonformatter.description",
    keywords: ["json formatter", "json validator", "beautify json"],
    accentColor: "#f97316",
    icon: "{ }",
    order: 11,
    featured: true,
    status: "stable",
    locales: [...LOCALES],
    implementationKey: "jsonFormatter",
  },
  {
    id: "passwordgenerator",
    slug: "password-generator",
    category: "security",
    titleKey: "tools.passwordgenerator.title",
    descriptionKey: "tools.passwordgenerator.description",
    keywords: ["password generator", "secure password", "random password"],
    accentColor: "#ef4444",
    icon: "Key",
    order: 12,
    featured: true,
    status: "stable",
    locales: [...LOCALES],
    implementationKey: "passwordGenerator",
  },
  {
    id: "textdiffchecker",
    slug: "text-diff-checker",
    category: "text",
    titleKey: "tools.textdiffchecker.title",
    descriptionKey: "tools.textdiffchecker.description",
    keywords: ["text diff", "compare text", "diff checker"],
    accentColor: "#10b981",
    icon: "Δ",
    order: 13,
    featured: true,
    status: "stable",
    locales: [...LOCALES],
    implementationKey: "textDiffChecker",
  },
  {
    id: "base64encoder",
    slug: "base64-encoder-decoder",
    category: "utility",
    titleKey: "tools.base64encoder.title",
    descriptionKey: "tools.base64encoder.description",
    keywords: ["base64", "encoder", "decoder", "base64 converter"],
    accentColor: "#6366f1",
    icon: "b64",
    order: 14,
    featured: true,
    status: "stable",
    locales: [...LOCALES],
    implementationKey: "base64Encoder",
  },
  {
    id: "colorconverter",
    slug: "color-code-converter",
    category: "utility",
    titleKey: "tools.colorconverter.title",
    descriptionKey: "tools.colorconverter.description",
    keywords: ["color converter", "hex to rgb", "rgb to hsl", "color picker"],
    accentColor: "#f43f5e",
    icon: "🎨",
    order: 15,
    featured: true,
    status: "stable",
    locales: [...LOCALES],
    implementationKey: "colorConverter",
  },
  {
    id: "unitconverter",
    slug: "unit-converter",
    category: "measurement",
    titleKey: "tools.unitconverter.title",
    descriptionKey: "tools.unitconverter.description",
    keywords: ["unit converter", "metric conversion", "measurement converter", "inch to cm", "kg to lbs"],
    accentColor: "#8b5cf6",
    icon: "📏",
    order: 16,
    featured: true,
    status: "stable",
    locales: [...LOCALES],
    implementationKey: "unitConverter",
  },
  {
    id: "percentagecalculator",
    slug: "percentage-calculator",
    category: "utility",
    titleKey: "tools.percentagecalculator.title",
    descriptionKey: "tools.percentagecalculator.description",
    keywords: ["percentage calculator", "discount calculator", "percentage increase", "percentage decrease", "percent of"],
    accentColor: "#ec4899",
    icon: "🔢",
    order: 17,
    featured: true,
    status: "stable",
    locales: [...LOCALES],
    implementationKey: "percentageCalculator",
  },
  {
    id: "iplookup",
    slug: "ip-lookup",
    category: "network",
    titleKey: "tools.iplookup.title",
    descriptionKey: "tools.iplookup.description",
    keywords: ["what is my ip", "ip lookup", "ip address", "my ip", "ip checker", "vpn check"],
    accentColor: "#0ea5e9",
    icon: "🌐",
    order: 18,
    featured: true,
    status: "stable",
    locales: [...LOCALES],
    implementationKey: "ipLookup",
  },
];

export function getVisibleTools(locale?: Locale) {
  return TOOLS.filter((tool) => {
    const localeOk = locale ? tool.locales.includes(locale) : true;
    return tool.status !== "hidden" && localeOk;
  }).sort((a, b) => a.order - b.order);
}

export function getToolBySlug(slug: string, locale?: Locale) {
  return TOOLS.find((tool) => {
    const localeOk = locale ? tool.locales.includes(locale) : true;
    return tool.slug === slug && localeOk;
  });
}

export function getStaticToolParams() {
  return TOOLS.flatMap((tool) =>
    LOCALES.flatMap((locale) =>
      tool.locales.includes(locale) ? [{ locale, slug: tool.slug }] : [],
    ),
  );
}
